meerk40t/meerk40t

ElementProperty.py, JobSpooler.py, Keymap.py, LaserProject.py, LaserRender.py, LaserSceneView.py, LhymicroWriter.py, MeerK40t.py, ProjectNodes.py, RasterPlotter.py, path.py, test/test_LhymicroWriter.py
Still has some refresh issues and clearly goes slower than it should. Fixes a couple long standing bugs and should work on migrating the LaserProject God Object into reasonable subclasses for the renderer tree/nodes and a standard project hub. Which would be highly important to keep the front end GUI elements apart from the rest. So CLI or other interfaces remain reasonable. Also, includes some basic keymapping.
=> Early Intro to 9

Controller.py, JobSpooler.py, LaserSceneView.py, LhymicroWriter.py, MeerK40t.py
Colors buttons to be more consistent and less red.
When running the scene background is red.
Fixes to emergency stop.
=> Better colors

README.md
An install argument was missing.
=> Fix apt-get command

Console.py, Kernel.py, LaserServer.py, PathProperty.py, RuidaDevice.py, wxMeerK40t.py
Features Frozen from 0.6.0
Bugs Unfixed from 0.6.0
=> Notes & Improvements

Kernel.py, LaserOperation.py, LaserRender.py, LhystudiosDevice.py, OperationPreprocessor.py, Widget.py, svgelements.py, wxMeerK40t.py, zinglplotter.py
=> Minor Dev 0.6.10

meerk40t/core/cutcode.py, meerk40t/core/elements.py, meerk40t/core/planner.py, meerk40t/gui/laserrender.py, meerk40t/gui/simulation.py, meerk40t/gui/widget.py, meerk40t/kernel.py
Still needs a few major changes.
=> 0.7.0 optimize

meerk40t/core/elements.py, meerk40t/svgelements.py
Previous code to handle Shapes with no stroke would work for text->path objects, but not for e.g. things that looked like cut segments (red and thin) but were really thin red fill and no stroke which would be classified as raster rather than cut.
This code simply uses fill colour as backup if there is no stroke and then classifies accordingly. It ends up being simpler as a consequence.
Dot support would not have previously worked because it was on an `elif` that would never be reached. Corrected Dot support has been commented out because there is no support elsewhere for Dot operations.
SVGelements had a bug on calculating colour distance (missing brackets) which I have fixed. During debugging I also fixed a bunch of __repr__ stuff in SVGelements and these are also included.
=> Improve classification to use fill colours if no stroke

meerk40t/core/elements.py, meerk40t/core/planner.py, meerk40t/gui/wxmeerk40t.py
Corrects Special Operation: Interrupt
=> Correct Interrupt

meerk40t/core/elements.py, meerk40t/gui/wxmeerk40t.py, meerk40t/kernel.py
Minor Console Fixes used for the wiki, better linking of some commands and bug fixes. Also, minor hidden commands for the previous control values.
=> Console Fixes

meerk40t/core/cutcode.py, meerk40t/core/elements.py, meerk40t/gui/lhystudios/lhystudiosdrivergui.py, meerk40t/gui/operationproperty.py
1. Provide an improved classification algorithm
2. Add a default operation flag (including console support)
3. Improve the labelling of elements to include element type and to provide more information if there are no Inkscape labels or SVG ids in the xml.
4. Improve tooltips in Operation Properties.
Note: There are commits for more files to add - please do not test or merge until I indicate that all changes have been uploaded.
=> Improve classification algorithm

meerk40t/core/elements.py
Add in a filter command for operations
Fix enable and disable
=> Operation Commands Filter

meerk40t/gui/operationproperty.py
This was intended much earlier and sort of stuck there providing little information now provides the information correctly.
* Correct crash for Step Value > 20.
* Adds in proper previews of the raster type.
=> Operation Properties Preview Fix

meerk40t/core/planner.py, meerk40t/gui/operationproperty.py
"return" for plan returns laser operations
=> Fix Crash for Non-Raster-Image OperationProperties

meerk40t/core/bindalias.py, meerk40t/core/elements.py, meerk40t/core/output.py, meerk40t/device/basedevice.py, meerk40t/gui/bufferview.py, meerk40t/gui/devicemanager.py, meerk40t/gui/executejob.py, meerk40t/gui/jobspooler.py, meerk40t/gui/panes/spoolerpanel.py, meerk40t/gui/scene/scenewidgets.py, meerk40t/gui/simulation.py, meerk40t/kernel.py
```
alias r ruidadesign -s
r
r is not a registered command in this context: lhystudios
```
Bug corrected.
=> Minor Bugs Hunt

meerk40t/core/elements.py, meerk40t/core/svg_io.py, meerk40t/device/lhystudios/lhystudiosemulator.py, meerk40t/device/ruida/ruidadevice.py, meerk40t/dxf/dxf_io.py, meerk40t/image/imagetools.py
Reverts meerk40t/meerk40t#511
I need to redo this
=> Revert "Raster Ops not matched to exact colors as default"

meerk40t/core/elements.py, meerk40t/core/planner.py, meerk40t/core/plotplanner.py, meerk40t/device/lhystudios/lhystudiosdevice.py, meerk40t/gui/scene/scenewidgets.py
Quick run through and fix of some major RC9 bugs.
Speed up move of objects.
Added `tree bounds`
Properly process bounds of objects during elementwidget manipulations
Correct walk routine for process plots.
=> RC10 Corrections

meerk40t/core/elements.py, meerk40t/gui/wxmeerk40t.py
* Includes #536 in error.
* Adds in Drag and Drop support for groups into ops
=> Add Drag-N-Drop for Groups into Ops

meerk40t/gui/wxmeerk40t.py
Corrects the Hide to remove Pane lifecycle routine
=> Fix pane lifecycle for close

meerk40t/core/elements.py, meerk40t/extra/vectrace.py, meerk40t/gui/panes/camerapanel.py, meerk40t/gui/rasterwizard.py, meerk40t/image/imagetools.py
.filter type image tools cannot run on palette images
=> Minor Bug Fixes for RC10->RC11

meerk40t/core/elements.py
This primarily does the following differently:
1. Any element with fill is treated as a raster. Previously an element with stroke and fill of different colors was treated as both a stroke and a raster which misclassified logos created as several layers of fills & strokes.
2. Strokes which are pure grey (R=G=B) are also treated as raster.
I will append some test cases in comments once I create the PR.
=> Further attempt at a solid classification

.github/workflows/win/meerk40t.spec
Reverts meerk40t/meerk40t#567
Well. It didn't fix the bug and I need to research it better.
=> Revert "Reverse source and dest of locales. Hopefully that fixes bug."

.github/workflows/ci.yml, .github/workflows/win/meerk40t.spec
Fix locale issue
Fix mechanism to manually trigger build (in this case it does fallback to using git short hash rather than the git tag version)
=> Github Actions build changes

meerk40t/core/planner.py, meerk40t/gui/rasterwizard.py, meerk40t/gui/wxmeerk40t.py, meerk40t/image/imagetools.py
Correct getbbox crash and unneeded truncation.
=> Avoid empty bbox crash #548

meerk40t/core/elements.py, meerk40t/gui/settings.py
Uses RC1 Classification code and gives a checkbox in settings to activate the legacy code instead of the modern code.
=> Add Legacy Classify Option, circa RC1

meerk40t/core/webhelp.py, meerk40t/gui/wxmeerk40t.py
@tatarize  - I have no idea what is causing it, but this change stops the webhelp functionality from launching a web page.
Works on master branch, doesn't work on this branch.
Can you help?
=> Add link to beginners wiki

meerk40t/device/lhystudios/lhystudiosdevice.py
* Permits the use of `%` in the lhymicro-gl code as a special command for the controller.
* The use of % does the checksum xor with 0xFF
* The rejection of the packet with a 207 error is ignored, and said to be correct.
* No retry attempt is made.
To test this `egv ~IPP%$~` and you can see if you `channel open 0/usb_send` and `channel open 0/recv` that this was just rejected. You can do this a bunch in the middle of actual values rastering processes etc and it won't process any of that stuff. Spaces get a bit weird and it might actually send the data correctly for one packet if you exceed 30 digits and it needs to break that data into different bits.
=> Process checksum-fail command.

meerk40t/gui/keymap.py
That function got moved, was not corrected.
=> Fix Keymap Crash bug

meerk40t/image/imagetools.py
Add in an `image slash` command to slash an image horizontally at a given y value.
=> Add `image slash`, correct return values for `image slice`

meerk40t/gui/panes/camerapanel.py
* Add Set URI loader from right-click.
* Fix right click crash issues. %d format.
=> Add Set URI, fix crash issues.

.github/workflows/win/file_version.txt, meerk40t/main.py, setup.cfg
The idea here is to have the version bump waiting in the wings in case we want to push a new version.
=> Version 0.7.4-beta3

.github/workflows/win/file_version.txt, meerk40t/gui/mwindow.py, meerk40t/gui/operationproperty.py, meerk40t/gui/panes/laserpanel.py, meerk40t/gui/scene/scenewidgets.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py, meerk40t/kernelserver.py, meerk40t/main.py, meerk40t/svgelements.py, setup.cfg
Finalize changes for 0.7.4
* Check through all crash logs.
* Fix optimize checkbox on main window
* Fix restore color picker for OperationProperty
=> 0.7.4 Finalize

meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenewidgets.py
=> Mouse Cursor Debugging and Correction.

meerk40t/core/cutcode.py, meerk40t/core/planner.py
Addresses a predicted issue with Merge Passes and Step Repeat as discussed in, and introduced by, #677.
=> Fix merge_passes with step_repeat

.github/workflows/win/file_version.txt, meerk40t/core/drivers.py, meerk40t/core/elements.py, meerk40t/core/output.py, meerk40t/core/spoolers.py, meerk40t/device/basedevice.py, meerk40t/gui/panes/devicespanel.py, meerk40t/gui/panes/laserpanel.py, meerk40t/main.py, setup.cfg
* Version bump
* Laserpane combo fix
* Right click open in system (needs checking for other OSes).
=> 0.7.5 beta1

meerk40t/core/drivers.py
No longer shall our Macs sound like the ghost of Stephen Hawking exclaiming the word "DING!"
=> Killed off the creepy "ding" on Macs.

meerk40t/gui/wxmeerk40t.py, meerk40t/kernel.py, meerk40t/main.py
1. Allow batch to include "channel print console" to retain console printing
2. Indent command output with 4 spaces to distinguish commands from their output
=> Minor batch and console improvements

meerk40t/kernel.py, meerk40t/main.py
1. Improve various `__repr__`
2. Enhance threaded call with *args... 
3. Add bootstrap("finished")... 
4. Improve signal channel formatting
5. Minor comment improvements
=> Various kernel improvements

meerk40t/core/elements.py, meerk40t/device/lhystudios/lhystudiosdevice.py
Modifies the operation speed command to allow, `operation* speed -d +2%` or `operation* speed -1`.
=> Modify operation speed command to set speeds by percent.

meerk40t/gui/wxmtree.py
0.7.5b1 sometimes does not show operations children.
=> Fix ops node not showing children

meerk40t/gui/panes/camerapanel.py, meerk40t/gui/panes/toolbarcontrol.py, meerk40t/gui/scene/scene.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmribbon.py
Corrects camera multiple window launching which broke in 0.7.4b1
=> Correct Camera Multiple Windows

meerk40t/core/planner.py
It can save so much time, and it's likely the default most people want.
lmk if I should have gone about this some other way :)
=> Reduce travel time 'on' by default

meerk40t/device/ch341/ch341.py, meerk40t/device/lhystudios/lhystudiosdevice.py, meerk40t/device/moshi/moshiblob.py, meerk40t/device/moshi/moshidevice.py, meerk40t/gui/moshi/moshicontrollergui.py
* Testing Moshiboard refinements.
Should correct several moshiboard errors. especially dealing with disconnecting and connection and thread interoperability.
=> Moshiboard Refinements

locale/de/LC_MESSAGES/meerk40t.po
Started to update the German translations
=> Language updates DE in meerk40t

.github/workflows/win/file_version.txt, meerk40t/main.py, setup.cfg
Should be version bump for the beta. We can check if there's anything else in the 0.7.5 line before a full release but betas should be pretty doable.
=> 0.7.5-beta2 Version Bump

.github/workflows/win/file_version.txt, meerk40t/core/cutcode.py, meerk40t/core/elements.py, meerk40t/gui/consoleproperty.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py, meerk40t/main.py, setup.cfg
* Prevents rastercut from being considered by the group expecting code.
* Adds first for rastercut, so it's considered in ordering for distances in new mode.
=> Fixes Nuke-Beta2 Crash bug.

locale/de/LC_MESSAGES/meerk40t.po, meerk40t/core/elements.py
a) extend tranlsations in elements.py
b) add/amend translations into DE_Locale
=> Extend translations

meerk40t/core/elements.py
I found it very annoying that the scene on file load was random - so here is a fix.
=> Fix scene zoom on file load

meerk40t/core/bindalias.py, meerk40t/gui/keymap.py
1. Provide update functionality if default bind / alias is updated in code and user has not changed the default.
2. Fix Keybind window blank after `bind default`.
=> Fix bind alias issues

meerk40t/core/cutcode.py, meerk40t/core/elements.py, meerk40t/core/planner.py, meerk40t/gui/wxmmain.py
Whilst working on raster optimisations I noticed that some open paths were not being burned.
This is a fix for that plus some other minor potential bugs I spotted plus some minor optimisations.
=> Fix some open elements not being (fully) burned

.github/ISSUE_TEMPLATE/config.yml
Experts need more flexibility to submit issues.
=> Reenable old-style Github issues.

meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenewidgets.py, meerk40t/gui/scene/toolwidgets.py, meerk40t/main.py, meerk40t/tools/zinglplotter.py, setup.cfg
1. Enable Python 3.10 for Pypi
2. Python 3.6 introduced math.tau so remove unneeded code setting up tau.
=> Python version stuff

meerk40t/core/drivers.py, meerk40t/core/output.py, meerk40t/device/basedevice.py, meerk40t/device/ch341/libusb.py, meerk40t/device/ch341/windll.py, meerk40t/device/grbl/grbldevice.py, meerk40t/device/moshi/moshiblob.py, meerk40t/device/moshi/moshidevice.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py, meerk40t/image/imagetools.py, meerk40t/kernel.py
Part 1 of several PRs to fix codacy errors.
Most of these should be obviously transparent, but changes to meerk40t/core/drivers.py for `opt_jog_mode` almost certainly need double checking.
=> Fix critical codacy errors

locale/de/LC_MESSAGES/meerk40t.po, meerk40t/gui/simulation.py, meerk40t/gui/wxmribbon.py, translate.py
Fix / Extend missing translations
a) DE-Locale
b) Fix in Simulation-Window
c) Add missing tooltip
=> Fix / Extend missing translations

meerk40t/core/elements.py
Remove incorrect raising of a syntax error, fixes [#882](https://github.com/meerk40t/meerk40t/issues/822)
=> Fix incorrect syntax error for 'matrix'

meerk40t/core/elements.py, meerk40t/gui/operationproperty.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxutils.py, meerk40t/kernel.py
This is an interim PR with some minor changes.
I am submitting this now as the next step are major changes to elements.py to add context menu help text and tweak right click menu functionality, and to avoid a headache rolling these changes forwards into 0.8.x these would probably be better once the restructuring done in 0.8 has been retrofitted to 0.7 and rolled forward.
=> Misc UI improvements

meerk40t/gui/preferences.py, meerk40t/gui/rotarysettings.py
The 0.7.0 branch rotary will not be fully correct this must be left to 0.8.0. As such these rotary options are disabled as they were not hooked up and will not be hooked up in this branch.
=> Rotary uses unused settings, turns those off.

meerk40t/core/cutcode.py
I don't know how these got lost. Caused failing tests. May cause running to fail. Though I dunno.
Either way, approve and merge. (don't bother waiting for me to merge this).
=> Fix cutcode imports.

meerk40t/core/elements.py
#826.
Testing font-size parameter rather than scale.
=> Add font-size parameter to text command

meerk40t/camera/plugin.py, meerk40t/core/elements.py, meerk40t/core/planner.py, meerk40t/core/spoolers.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py, meerk40t/image/imagetools.py, meerk40t/kernel/exceptions.py, meerk40t/kernel/functions.py, meerk40t/kernel/kernel.py, meerk40t/lihuiyu/device.py, meerk40t/ruida/device.py
Use of the Python syntax error results in syntax errors in panes being ignored and main window not opening!!!
=> Use bespoke exception for CommandSyntaxErrors

.github/workflows/win.yml
Added these so that they get better exposure in 0.8.x RCs
=> Add grbl, balor dependencies to windows build yaml

meerk40t/gui/panes/consolepanel.py, meerk40t/gui/wxmeerk40t.py, meerk40t/kernel.py
I have tested this on Windows and Linux and it works. Cannot test on mac,
=> Fix ansi console legacy7 branch

meerk40t/device/lhystudios/lhystudiosdevice.py, meerk40t/gui/panes/consolepanel.py, meerk40t/gui/wxmeerk40t.py, meerk40t/kernel.py
Correct s the broken line where I called the h_switch_g line rather than v_switch_g line.
=> Fix Issue #881 Vertical regular raster broken.

meerk40t/gui/navigationpanels.py
Fix Size Panel
(Further refinements for Trafo-panel at a later point)
=> Fix SizePanel

meerk40t/core/elements.py, meerk40t/core/units.py
- Fix remaining old length conversions
- Add syntax check for invalid lengths
=> Fix shape, polyline, polygon et al

meerk40t/gui/scenewidgets/selectionwidget.py
Skewed shape now follows cursor
=> Make skew more predictable

meerk40t/gui/panes/consolepanel.py, meerk40t/kernel.py, meerk40t/main.py
* Does not crash with bytes being sent over channel.
* Does not determine ANSI-support rather asks for it within console, eg window 7 Pycharm IDE uses PowerShell which does support ANSI.
* Swaps RichText to read ansi-directly with much faster/better parsing of the sent text.
* Significantly less processing.
=> Correct and Properly Fix ANSI bugs

meerk40t/gui/scenewidgets/selectionwidget.py
Should feel much snappier now - had to to drop bounding-box rectangles while skewing or rotating but that's a small price to pay I think
=> Optimisations / Fixes for item manipulation

meerk40t/gui/wxmmain.py, meerk40t/gui/wxmribbon.py
Not extremely elegant (and not yet linked to console command tool) - but hey it does the job ;-)
=> Highlight active tool

meerk40t/gui/scenewidgets/selectionwidget.py
- Apply same logic as in 0.7 branch for skew and rotation
- Make rotcenter behaviour consistent
=> RotCenter fix, fix skew/improve rotation behaviour

meerk40t/gui/wxmribbon.py
=> Fix untoggle behaviour for ribbon

.github/workflows/win/file_version.txt, meerk40t/main.py, setup.cfg
=> 0.7.6 Beta 3 Version Bump

meerk40t/core/elements.py
Wasn't recognized as parameter names and variable names did not match (has this always been the case?)
=> Fix startangle in shape

.github/workflows/win/file_version.txt, meerk40t/core/cutcode.py, meerk40t/core/plotplanner.py, meerk40t/gui/panes/consolepanel.py, meerk40t/main.py, setup.cfg
* Corrects keymap right-click menu.
* Corrected delete functionality. (Still an edge case of hard select during delete going slowly).
=> 0.7.6 Beta 4

meerk40t/gui/panes/consolepanel.py
Correct speed issues with console not being scrolled panel type
=> Scrolled Console

meerk40t/gui/scene/scene.py, meerk40t/gui/scenewidgets/gridwidget.py, meerk40t/gui/scenewidgets/guidewidget.py
- Fix for inverted X- and Y-axis (e.g. for GRBL)
- Extended functionality within context-menu:
=> Magnets: Fix for GRBL + extensions

meerk40t/gui/scenewidgets/guidewidget.py
Should work now with all devices
=> Magnet: Fix toggle (again)

meerk40t/gui/scenewidgets/selectionwidget.py
=> Rotation: Code tweaks after feedback

meerk40t/gui/scenewidgets/selectionwidget.py
Make sure handling handles remain visible and dont overlap for low zoom-factors or small-sized selections
=> Better handling of small-sized selections

meerk40t/core/node/elemnode.py, meerk40t/core/node/node.py, meerk40t/gui/scenewidgets/elementswidget.py
* adds in `points`, `update_point` `add_point` and `revalidate_point` functions
=> Node.points test api code

meerk40t/gui/scenewidgets/selectionwidget.py
call invalidated_node instead of setting  _bounds_dirty
plus some black-induced formatting
=> Acknowledge new points_dirty flag

meerk40t/balormk/main.py, meerk40t/core/cutplan.py, meerk40t/core/elements.py, meerk40t/core/node/laserop.py, meerk40t/core/node/node.py, meerk40t/core/node/rootnode.py, meerk40t/core/parameters.py, meerk40t/core/planner.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmtree.py, meerk40t/tools/pathtools.py
* Add in properties for Hatch.
* Add in hatch op node.
* Add in hatch op to properly run a hatch.
=> Hatch Operation

meerk40t/core/elements.py
Fix incorrect usage of device.width / height
=> Fix align bedcenter

meerk40t/gui/scenewidgets/selectionwidget.py
=> Make sure that text at manipulation boxes does not overlap

meerk40t/gui/scenewidgets/selectionwidget.py
Proper hover-consume behaviour
=> Fix rotcenter/move cursor issue

meerk40t/balormk/main.py, meerk40t/core/elements.py, meerk40t/core/node/elem_ellipse.py, meerk40t/core/node/elem_line.py, meerk40t/core/node/elem_path.py, meerk40t/core/node/elem_polyline.py, meerk40t/core/node/elem_rect.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_hatch.py, meerk40t/core/node/op_image.py, meerk40t/core/planner.py, meerk40t/core/svg_io.py, meerk40t/extra/cag.py, meerk40t/extra/embroider.py, meerk40t/gui/laserrender.py
I recently changed the Element Paths over to use stroke, and fill directly and to permit functions to be attached to the nodes themselves. This fundamentally changed the Elements routines and causes code that used these elements parts to crash and fail in many ways. First time around I fixed as many bugs as I could, this is the second patch of them.
=> Second Round of Bug Fixes

meerk40t/core/elements.py, meerk40t/core/svg_io.py, meerk40t/gui/scene/widget.py
- Loading / importing of images crashed due to check for non-existing attributes
- Fixed saving for images
- Fix a widget draw error on the way
=> Fix save / load / classification error for images

meerk40t/balor/command_list.py, meerk40t/balormk/BalorDriver.py, meerk40t/core/elements.py, meerk40t/core/node/elem_text.py, meerk40t/core/node/op_hatch.py, meerk40t/core/parameters.py, meerk40t/gui/laserrender.py, meerk40t/gui/propertypanels/operationpropertymain.py, test/test_imagetools_actualize.py, test/test_length.py, test/test_wobble.py
* Should correct inconsistent density wobble issues
=> Correct Balor Wobbles

meerk40t/gui/position.py
Extend the functionality of the position panel to allow mass-changes of width / height / X / Y
=> Allow individual mass changes

meerk40t/core/cutplan.py
See recent comment on https://github.com/meerk40t/meerk40t/issues/1028
=> Sophist-UK fix for issue #1028

meerk40t/gui/scene/guicolors.py, meerk40t/gui/scene/scene.py, meerk40t/gui/scenewidgets/attractionwidget.py, meerk40t/gui/scenewidgets/gridwidget.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/wxmscene.py
A new 'grid' command in the scene-context to allow a secondary rectangular grid with optional scaling and shifted origin (main use case rotary) as well as a circular grid (mainly for Galvo).
```
scene grid
```
displays the current parameters, e.g.
```
[20:04:09] scene grid
[20:04:09]     Grid-Parameters:
[20:04:09]     Primary: On
[20:04:09]     Secondary: On
[20:04:09]        scale-x: 3.00
[20:04:09]        scale-y: 1.50
[20:04:09]     Circular: On
```
```
scene grid primary
```
toggles the primary grid
```
scene grid secondary <cx> <cy> <scalex> <scaley>
```
toggles the secondary grid and sets the center to \<cx\> \<cy\> and the scale compared to the regular coordinates.
**NB: if you dont provide any parameters then the scale defaults to that in the rotary settings**
```
scene grid …
```
=> Secondary + Circular grid

meerk40t/core/fonts.py, meerk40t/core/svg_io.py, meerk40t/gui/laserrender.py, meerk40t/gui/propertypanels/textproperty.py
Use explicit attribute conversion as implicit one failed
=> Fix svg to wx font translation

meerk40t/core/fonts.py
Px to pt conversion
One last outstanding fix: text position after import is still wrong...
=> FIx font size

meerk40t/core/elements.py, meerk40t/core/node/groupnode.py
a) Fix empty (and btw non-empty) group bbox bug
b) Fix group elements
=> Fix for some group errors

meerk40t/core/planner.py, meerk40t/core/units.py, meerk40t/gui/executejob.py
Some minor fixes + optical changes for step_repeat:
- Show information about offset_value
- Fix crashes if empty elelement list
- Show proper distances for width and height when invoke from planner window
=> Changes + Fixes for step_repeat

meerk40t/core/wordlist.py, meerk40t/gui/wordlisteditor.py
a) Fix combobox display
b) remove pickle (uses json instead, as this is already used)
=> Some fixes for wordlist

meerk40t/core/elements.py, meerk40t/core/node/elem_ellipse.py, meerk40t/core/node/elem_line.py, meerk40t/core/node/elem_path.py, meerk40t/core/node/elem_polyline.py, meerk40t/core/node/elem_rect.py, meerk40t/core/node/node.py, meerk40t/core/svg_io.py, meerk40t/gui/laserrender.py
Acknowledge fill-rule attribute:
Should fix [Issue 1020](https://github.com/meerk40t/meerk40t/issues/1020)
=> svg fill-rule acknowledgement 

meerk40t/core/cutplan.py
According to comment in PR https://github.com/meerk40t/meerk40t/pull/1030
=> sophist-uk fix for fix

meerk40t/balormk/BalorDriver.py, meerk40t/core/cutcode.py, meerk40t/core/node/op_hatch.py, meerk40t/core/svg_io.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/tools/pathtools.py
* in some cases balor moves are cut-to erroneously.
=> Attempt to fix balor hatching move-to being cut.

meerk40t/gui/scenewidgets/elementswidget.py, meerk40t/gui/wxmmain.py
Add promised and advertised configuration option for selection method (wasn't commited...)
=> Make selection method configurable

meerk40t/gui/scene/scene.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/toolellipse.py, meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/toolwidgets/toolpolyline.py, meerk40t/gui/toolwidgets/toolrect.py, meerk40t/gui/wxmscene.py
Remember the last used colors for stroke and fill for the creation of new elements
=> Remember last stroke/fill colors for new elements

.github/workflows/mac11_pyinst.yml
=> mac-autorun-build-fix

meerk40t/balormk/main.py, meerk40t/core/node/op_hatch.py, meerk40t/core/units.py, meerk40t/fill/fills.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/propertypanels/operationpropertymain.py, test/test_fill.py
* Implement units.Angle
* Implement redlight offset and redlight angle
* Implement scanline fill
=> Implement redlight offset and redlight angle for balor

meerk40t/gui/scenewidgets/gridwidget.py
Constrains the amount of grid lines / grid points to be calculated to the visible area of the scene - should improve the speed of drawing in higher zoom levels substantially
=> Speedup grid widget

meerk40t/gui/scene/scenespacewidget.py, meerk40t/gui/scenewidgets/bedwidget.py, meerk40t/gui/scenewidgets/gridwidget.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/simulation.py
- Optimise drawing of circular grid at high zoom levels
- Establish max zoom level
=> Optimise drawing of circular grid

meerk40t/gui/scenewidgets/selectionwidget.py
Functionality got lost somewhere around the way after node definition changed
=> Fix copy while dragging

meerk40t/gui/scene/guicolors.py, meerk40t/gui/wxmmain.py
if for whatever reasons GUI colors become degenerate, i.e. identical to the bedcolor, then the colorschme will be reset to default
=> Recognise degenerate GUI colors

meerk40t/core/elements.py, meerk40t/gui/navigationpanels.py
- the "circular" trace option was missing, was available in tracegen though
- fix typo
=> Add "circular" to trace

meerk40t/camera/gui/camerapanel.py, meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenepanel.py, meerk40t/gui/scene/scenespacewidget.py, meerk40t/gui/scene/widget.py, meerk40t/gui/scenewidgets/attractionwidget.py, meerk40t/gui/scenewidgets/bedwidget.py, meerk40t/gui/scenewidgets/buttonwidget.py, meerk40t/gui/scenewidgets/elementswidget.py, meerk40t/gui/scenewidgets/gridwidget.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/scenewidgets/rectselectwidget.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/tooldraw.py, meerk40t/gui/toolwidgets/toolellipse.py, meerk40t/gui/toolwidgets/toolmeasure.py, meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/toolwidgets/toolpolyline.py, meerk40t/gui/toolwidgets/toolrect.py, meerk40t/gui/toolwidgets/toolrelocate.py, meerk40t/gui/toolwidgets/tooltext.py, meerk40t/gui/toolwidgets/toolvector.py
If you have snap enabled then the creation of elements will more WYSIWYG instead of WYGIWIITGY ;-)
=> Extend event with nearest_snap

meerk40t/core/elements.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmribbon.py
Some minor fixes / enhancements
- Add regmark [add|free|clear] command
- Make disabled buttons in ribbonbar stand out more
- Assign shortcut to "Reset Windows" Menu-Item 
- Make sure Guide figures don't overlap
-
=> Miscellaneous 

meerk40t/extra/hershey.py, meerk40t/main.py, meerk40t/svgelements.py, meerk40t/tools/shxparser.py
Adds in `linetext` command. Requires you to have `.SHX` files in your meerk40t directory.
E. G. `C:\Users\Tat\AppData\Local\MeerK40t\` and you need to specify the `-f` command to point to the right file at least once.
=> SHX Line Font Parser

meerk40t/core/planner.py
Needs some rework, all assignments are gone after it...
=> Just prevent the crash for return plan

meerk40t/camera/gui/camerapanel.py, meerk40t/gui/scenewidgets/attractionwidget.py
open console and provide the search range:
```
set cam_search_range 20 
```
will look at the first 20 indices of cv2 cameras
=> Make camera search range configurable

meerk40t/gui/wxmribbon.py
Huge files will mk40 collapse, here's one of many steps to remedy that
=> Make sure ribbonbar.onpaint is thread safe

meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py
Make generation of preview icons somewhat smarter. Still there's more room for improvement
=> 1st attempt at Tree Optimisation

meerk40t/gui/propertypanels/textproperty.py
=> Additional attributes in text-propertypanel

meerk40t/balormk/device.py, meerk40t/balormk/driver.py, meerk40t/balormk/gui/gui.py, meerk40t/balormk/lmc_controller.py
* Completely sheds all old Balor code and rewrites things from scratch. Note this means there's a lot of bugs in it.
* Combines controller with list and short command capabilities.
* Does not pre-compile jobs (this was a serious problem in Balor code).
=> Update Balor/Galvo to the next level.

meerk40t/balormk/gui/gui.py, meerk40t/camera/gui/camerapanel.py, meerk40t/gui/auitoolbars.py, meerk40t/gui/wxmribbon.py
* Permits a toggle multi-button which allows you to select a state, and click it. Then it will toggle between this state and the toggle state.
https://user-images.githubusercontent.com/3302478/177042231-87e9a4b3-7e2c-4fda-be3d-5ad080247ca1.mp4
=> Adds and Implements Hybrid/Toggle button

.github/workflows/win/file_version.txt, meerk40t/gui/laserrender.py, meerk40t/main.py, meerk40t/svgelements.py, setup.cfg
* Prevent Nan to int crash in drawing routine
=> Minor Crash Prevention for Legacy7

meerk40t/camera/gui/camerapanel.py, meerk40t/core/elements.py, meerk40t/gui/wxmtree.py
- fix error message when clicking on the camera button without prior identification 
- Remove yet another unnecessary tree rebuild
=> Small fixes

.github/workflows/win/file_version.txt, meerk40t/core/cutplan.py, meerk40t/main.py, setup.cfg
* Some CLI issues crept in and running from pure-python CLI for basic operations no longer works.
=> Version 7: Correct CLI issues.

meerk40t/gui/wxmmain.py, meerk40t/gui/wxmribbon.py
=> Two more geometry tools + individual enable-rules

meerk40t/lihuiyu/device.py
Mostly this fixes a bug in TCP code where the viewbuffer value would not return a value but rather crash.
Thanks to Lexan for pointing this out.
=> Correct and Update the M2 Nano TCP connection.

meerk40t/core/planner.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/executejob.py, meerk40t/gui/wxmtree.py
a) Make sure job optimisation options appear
b) Get rid of Node:None in tree
=> Smaller fixes

meerk40t/balormk/device.py, meerk40t/balormk/lmc_controller.py, meerk40t/balormk/mock_connection.py, meerk40t/balormk/usb_connection.py, meerk40t/kernel/kernel.py
* raw lets you send data to the laser and play with that that way. This works as a testing apparatus.
=> Galvo Next: Add in special `raw` galvo command

meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py
* Corrects M2-Nano not correctly entering rastering mode
=> Correct Raster/Image M2Nano-(Thanks Darkfibre)

meerk40t/balormk/device.py, meerk40t/balormk/lmc_controller.py, meerk40t/core/node/elem_image.py, meerk40t/core/spoolers.py
=> Galvo Next: Incremental Corrections

meerk40t/kernel/kernel.py
_find substring_ will identify commands that contain the given substring
=> Add find command

meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenespacewidget.py
Align mouse-scrollwheel zoom to the joint preference-value
=> zoom_factor -> zoom_level

meerk40t/core/node/node.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_hatch.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py, meerk40t/dxf/dxf_io.py, meerk40t/gui/mwindow.py, meerk40t/gui/plugin.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/image/imagetools.py
* If we attempt to restore a window position and that window isn't on a display, we don't do that. You get default positions if you don't have a monitor in that location able to deal with that window position.
* Corrects the window loading and position saving.
=> Correct Display Position issues. Multi-display failure & Recovery

meerk40t/kernel/jobs.py, meerk40t/kernel/kernel.py
* Allows you to tell how many times a timer has run and to run extremely simple index varying.
=> Minor tweaks to Kernel timers

meerk40t/core/elements.py, meerk40t/core/node/util_console.py, meerk40t/core/node/util_input.py, meerk40t/core/node/util_output.py, meerk40t/core/node/util_wait.py
Utility Nodes should disable and enable.
Their states should save to svg.
Their states should save to default operations.
=> Utility Nodes Disable/Enable Parameter Saving

meerk40t/gui/scene/scene.py, meerk40t/gui/toolwidgets/toolribbon.py, meerk40t/gui/wxmscene.py
Ribbon Tool with Animation Scene code.
Ribbon uses the animation of the scene to draw a ribbon example.
=> Animate Scene, +Ribbon Tool

meerk40t/gui/scene/scene.py, meerk40t/gui/scenewidgets/buttonwidget.py, meerk40t/gui/scenewidgets/cyclocycloidwidget.py, meerk40t/gui/scenewidgets/relocatewidget.py, meerk40t/gui/wxmeerk40t.py, meerk40t/kernel/kernel.py
* Provides animated adjustments for cyclocycloid widget.
* Fix a serious performance issue with regards to kernel and main-thread execution jobs.
* Move animations back to main-thread executions.
=> Provide better advanced Widget Code examples.

meerk40t/core/elements.py, meerk40t/extra/cag.py, meerk40t/gui/scene/scene.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/tooldraw.py, meerk40t/gui/toolwidgets/toolellipse.py, meerk40t/gui/toolwidgets/toolpoint.py, meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/toolwidgets/toolpolyline.py, meerk40t/gui/toolwidgets/toolrect.py, meerk40t/gui/toolwidgets/toolribbon.py, meerk40t/gui/toolwidgets/tooltext.py, meerk40t/gui/toolwidgets/toolvector.py, meerk40t/gui/wxmscene.py, test/test_core_elements.py
a) Make classification of new elements user-configurable
b) Use default colors / fills as set in the status-colorbar for newly created elements
=> Classification for new elements+ default colors

meerk40t/gui/utilitywidgets/checkboxwidget.py, meerk40t/gui/wxmscene.py
Include checkbox widget give a quick example of the usage.
console: `checkbox`
=> Checkbox Widget Example

meerk40t/gui/scene/scenespacewidget.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py
Add in a quick example of scene focus animation.
https://user-images.githubusercontent.com/3302478/181661585-ce44e944-b5a0-4d91-a06f-3e243cfd67d0.mp4
=> Animate Zoom for `scene focus`.

meerk40t/gui/devicepanel.py, meerk40t/gui/keymap.py, meerk40t/kernel/kernel.py
a) Allow multi-deletion
b) Get back to start with abolute defaults if needed
c) Some optical plus functional extensions to device panel
=> Some work around the keybind/device panel

meerk40t/core/elements.py, meerk40t/fill/fills.py, meerk40t/gui/statusbarwidgets/infowidget.py
a) Put a bandaid on ZerodivisionError as report by paiin
b) Allow suppression of statistics in statusbar
=> One 'fix' / one improvement

meerk40t/core/cutcode.py, meerk40t/core/spoolers.py
Spooler listing should be much more mild than it actually currently is, this could also affect spooler gui.
=> Correct Major Lag Listing Spooler

meerk40t/camera/gui/camerapanel.py
Already fixed it but got buried once again on me trying to juggle too many branches at once... (is as well part of [PR 1223](https://github.com/meerk40t/meerk40t/pull/1223) bu there are a lot of new things superimposed on it, that may need further work)
=> Fix camerapanel issue

meerk40t/core/svg_io.py
Correct scaling to be based on received PPI rather than default
=> Add `svg_viewport_bed` option.

meerk40t/balormk/driver.py, meerk40t/camera/gui/camerapanel.py, meerk40t/core/spoolers.py, meerk40t/grbl/device.py, meerk40t/gui/spoolerpanel.py, meerk40t/gui/statusbarwidgets/infowidget.py, meerk40t/gui/wxmmain.py, meerk40t/lihuiyu/device.py, meerk40t/moshi/device.py
a) Provide infos about burn progress in statusbar
b) Display some history about finshed jobs in spoolerpanel
=> Statusbar info for burn progress / Burn history

meerk40t/balormk/device.py, meerk40t/balormk/gui/balorconfig.py, meerk40t/core/elements.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_hatch.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py, meerk40t/device/dummydevice.py, meerk40t/device/gui/warningpanel.py, meerk40t/grbl/device.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/gui/wxmtree.py, meerk40t/kernel/context.py, meerk40t/kernel/settings.py, meerk40t/lihuiyu/device.py, meerk40t/lihuiyu/gui/lhydrivergui.py, meerk40t/moshi/device.py, meerk40t/moshi/gui/moshidrivergui.py, meerk40t/ruida/device.py
Allow individual settings per device
=> Make operation warning-level device dependent and user-configurable

meerk40t/gui/devicepanel.py, meerk40t/gui/simulation.py, meerk40t/gui/wxmeerk40t.py
Fixes:
a) Devicepanel: Color follows device activation
b) Simulation: Fix f-induced crash
c) Simulation fix crash after 'send to laser'
Extension:
d) Allow modification of optimisation parameters inside simulation window
=> Some more fixes / Simulation window extension

meerk40t/balormk/device.py, meerk40t/gui/icons.py, meerk40t/gui/plugin.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/wxmtree.py
* Testing wxPython for Python 3.10 finding any errors etc.
=> Minor tweaks for 3.10 wxPython 4.2

.github/workflows/codeql-analysis.yml, .github/workflows/mac11_pyinst.yml, .github/workflows/python-code-quality.yml, .github/workflows/ubuntu.yml, .github/workflows/unittests.yml, requirements-gui.txt, requirements-nogui.txt, requirements.txt
Removed wxpython dependencies from actions that wouldn't use it.
Renamed requirements.txt to requirements-nogui.txt
Renamed requirements-gui.txt to requirements.txt
=> Some github actions cleanup

meerk40t/gui/about.py, meerk40t/gui/simulation.py
a) Fix device selection in Simulation Window
b) Add additional debug information in the About-Box for future user queries
=> Fix device selection combo

meerk40t/balormk/device.py, meerk40t/balormk/driver.py, meerk40t/balormk/lmc_controller.py
* Checks MarkTime each time project finishes.
* `raw` command shifts mode if we call a short command out of order in a list command.
* removed list to short sync for light on and other port writes
=> Minor Tweaks To Galvo Device

meerk40t/core/spoolers.py, meerk40t/gui/spoolerpanel.py
a) Calculate in spooler the time of the cutplan execution (just like in simulator)
b) Update the current time / estimates in spooler panel
=> More consistent time estimates in spooler

meerk40t/core/elements.py
(or we eliminate the context menu item)
=> Reestablish reify (has still some merits)

meerk40t/core/elements.py, meerk40t/core/svg_io.py, meerk40t/gui/wxmmain.py
* Correct saving of regmarks
* Expand version save to allow additional save types
* Implement SVGZ
=> Add svgz save type, expand versions saving

meerk40t/balormk/gui/baloroperationproperties.py, meerk40t/core/elements.py, meerk40t/core/node/elem_image.py, meerk40t/core/node/util_console.py, meerk40t/core/svg_io.py, meerk40t/core/wordlist.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/laserpanel.py, meerk40t/gui/laserrender.py, meerk40t/gui/plugin.py, meerk40t/gui/preferences.py, meerk40t/gui/propertypanels/groupproperties.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/propertypanels/propertywindow.py, meerk40t/gui/propertypanels/textproperty.py, meerk40t/gui/simulation.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py, meerk40t/gui/wxutils.py, meerk40t/kernel/kernel.py, meerk40t/lihuiyu/gui/lhyaccelgui.py, meerk40t/lihuiyu/gui/lhycontrollergui.py, meerk40t/lihuiyu/gui/lhydrivergui.py, meerk40t/moshi/gui/moshidrivergui.py, meerk40t/rotary/gui/rotarysettings.py, test/test_core_plotplanner.py
* Correct special console, cancel bug.
* Wait Node, cancel issue.
* Fixed API issues with `tree_prompt` types.
* Fixed gui-thread interruption for linux.
* Make jobspooler open consistently
=> Fix several small bugs tiger found

meerk40t/gui/choicepropertypanel.py
=> Sync choicepropertypanels across multiple panels

meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/statusbarwidgets/strokewidget.py
=> Some info about a path in the property panel

.github/workflows/win/file_version.txt, meerk40t/balormk/gui/gui.py, meerk40t/core/elements.py, meerk40t/core/node/elem_ellipse.py, meerk40t/core/node/elem_image.py, meerk40t/core/node/elem_line.py, meerk40t/core/node/elem_numpath.py, meerk40t/core/node/elem_path.py, meerk40t/core/node/elem_point.py, meerk40t/core/node/elem_polyline.py, meerk40t/core/node/elem_rect.py, meerk40t/core/node/elem_text.py, meerk40t/core/svg_io.py, meerk40t/grbl/gui/gui.py, meerk40t/gui/about.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/laserpanel.py, meerk40t/gui/preferences.py, meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenespacewidget.py, meerk40t/gui/statusbarwidgets/strokewidget.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py, meerk40t/kernel/context.py, meerk40t/lihuiyu/gui/gui.py, meerk40t/main.py, meerk40t/moshi/gui/gui.py, setup.cfg
* Add module_delegate deference
* Correct .settings from loaded files
* Correct load file with `fill` crash
* Correct duplicated id
* Correct missing id for text object
* Correct Point location
* Fix crash for Point without scaled_stroke value
* Correct Zoom-Level to Zoom-Factor
* Rename Zoom-Level to Zoom Margin
* Add in Pan Factor to settings
* Workaround for checkboxes in Linux
* Fix Mac About Wrapper
* Fix Mac About Crash due to socket-error
* Fix double-open window call
* Correct preferences failing to remove choice values
* Add in `module_close()` to dereference the choice listeners in panel
* Fix `winpath` values for device specific window (should have toggled, didn't).
=> Merge in Module Delegation

meerk40t/balormk/driver.py, meerk40t/core/cutcode.py, meerk40t/core/element_types.py, meerk40t/core/elements.py, meerk40t/core/node/rootnode.py, meerk40t/core/node/util_home.py, meerk40t/core/planner.py, meerk40t/grbl/device.py, meerk40t/gui/executejob.py, meerk40t/gui/laserrender.py, meerk40t/gui/mkdebug.py, meerk40t/gui/operation_info.py, meerk40t/gui/toolwidgets/toolribbon.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmribbon.py, meerk40t/gui/wxmtree.py, meerk40t/lihuiyu/device.py, meerk40t/moshi/device.py
Research is still needed for the goto operation. This however fixes the issue where home wouldn't integerate as part of the cutcode. With this, there are HomeCut and HomeOperations classes but it's not clear about the Origin operations and whether or not this should include various other aspects. For example the lack or origin points and origin and the `set_position` code.
=> Home Operations

meerk40t/extra/imageactions.py, meerk40t/gui/icons.py, meerk40t/gui/imagesplitter.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmtree.py, meerk40t/main.py
Some new actions based on selected elements:
a) Render the selected elements and cut the image into multiple pieces to allow for separate burning (or whatever) of oversized stuff
b) Create keyhole images by selecting elements plus an additional element that will act as mask or keyhole for the other elements
=> Imageactions

meerk40t/balormk/driver.py, meerk40t/core/cutcode.py, meerk40t/core/drivers.py, meerk40t/core/node/util_wait.py, meerk40t/core/planner.py, meerk40t/grbl/device.py, meerk40t/lihuiyu/device.py, meerk40t/moshi/device.py
* Move driver functions around.
* Make many driver functions protected if they shouldn't be called by a driver.
* Ensure wait and dwell commands are consistently in ms.
* Ensure most driver commands have consistent doc strings
=> Update devices for readability and consistency.

meerk40t/core/node/rootnode.py, meerk40t/core/spoolers.py, meerk40t/lihuiyu/device.py
If a plan has a ready job for a lihuiyu driver (though anything else but it might make faulty data since it won't have be cut-planned for the other driver. You can issue a `plan save_job <filename>` to save the egv data that would be produced. So `plan save_job m.egv` will send the data to output to an `m.egv` file.
=> Lihuiyu Driver planner `save_job` command.

meerk40t/svgelements.py
=> Svgelements 1.8.1

meerk40t/gui/laserrender.py
DRAW_MODE_PATH did only affect 'real' paths and not all shapes
=> Fix for suppression of shapes

meerk40t/core/node/elem_text.py, meerk40t/core/svg_io.py, meerk40t/gui/laserrender.py, meerk40t/gui/scene/scene.py, meerk40t/svgelements.py
Find font bounds by actually measuring the rendered font.
=> Hybrid Font Bounds

.vscode/settings.json, meerk40t/balormk/gui/balorconfig.py, meerk40t/core/planner.py, meerk40t/device/gui/defaultactions.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/gui/materialtest.py, meerk40t/gui/wxmtree.py, meerk40t/lihuiyu/gui/lhydrivergui.py, meerk40t/moshi/gui/moshidrivergui.py
Default Start / End operations are back (with a twist, you can add any console command now to both start and end).
Needs some validation, therefore no immediate merge
=> Default operations

meerk40t/camera/gui/camerapanel.py
Sets maximum fps on slider to 120.
Sets default fps to 30 (a very common camera fps value)
=> Camera fps

meerk40t/core/svg_io.py
* Load/Save Element Lock values.
* Load/Save internal Label values.
* Load/Save additional values for the ImageNode.
* Rename `my_label` as `_label`
=> Load/Save Element Lock

meerk40t/grbl/device.py, meerk40t/gui/wxmscene.py, meerk40t/moshi/device.py, meerk40t/moshi/gui/moshidrivergui.py
Reestablish/Introduce consistent home_bottom, home_right, flip_x, flip_y, swap_xy to moshi and grbl driver.
=> Add viewport parameters to moshi & grbl (changed)

meerk40t/extra/potrace.py, meerk40t/extra/vectrace.py, meerk40t/main.py
I had to create a different branch since I couldn't get any version of pypotrace to work for me to test that this compatibility and simplification routine works.
=> Use blacklevel for pypotrace compatibility.

.github/workflows/win/file_version.txt, meerk40t/balormk/gui/balorconfig.py, meerk40t/balormk/lmc_controller.py, meerk40t/core/cutplan.py, meerk40t/core/svg_io.py, meerk40t/grbl/device.py, meerk40t/gui/consolepanel.py, meerk40t/gui/laserrender.py, meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/simulation.py, meerk40t/gui/spoolerpanel.py, meerk40t/image/imagetools.py, meerk40t/main.py, meerk40t/svgelements.py, setup.cfg
=> Required Fixes for next beta

meerk40t/gui/wordlisteditor.py
Please note that this PR was created in a browser and has not been tested.
=> Improve WordList help text

meerk40t/core/elements.py, meerk40t/core/wordlist.py, meerk40t/extra/hershey.py, meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenepanel.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/toolwidgets/toollinetext.py, meerk40t/gui/wordlisteditor.py
a) Hershey-Textelements support variables now:
b) Better handling of duplication of wordlist references:
NB: includes as well the fix for adjusting the index of simple wordlist elements (ie non csv-import)
=> Wordlist for hershey fonts / better copy

.github/workflows/win/file_version.txt, meerk40t/kernel.py, meerk40t/main.py, meerk40t/svgelements.py, setup.cfg
=> 0.7.9 - Bug Fixes and Small Tweaks for Legacy7 Branch

meerk40t/core/units.py, meerk40t/gui/scenewidgets/gridwidget.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/scenewidgets/machineoriginwidget.py, meerk40t/lihuiyu/gui/lhydrivergui.py
* Correct some issues with machine origin. Use scene_to_show more consistently.
=> Correct machine origin

meerk40t/core/elements.py, meerk40t/core/node/elem_ellipse.py, meerk40t/core/node/elem_line.py, meerk40t/core/node/elem_path.py, meerk40t/core/node/elem_polyline.py, meerk40t/core/node/elem_rect.py, meerk40t/extra/imageactions.py
- Fix calculation of paint bounds
- Make sure changes to stroke / stroke_width lead to a recalculation of the bounds
=> Fix paint_bounds

meerk40t/core/elements.py, meerk40t/gui/laserrender.py
and fixed existing ouline command and renamed it to ``frame``
=> Outline command

meerk40t/core/elements.py, meerk40t/core/node/elem_point.py
Replaces all bezier curves with circular arcs, mostly for testing purposes.
=> Add `circle_arc_path` command.

meerk40t/core/node/elem_image.py, meerk40t/gui/propertypanels/imageproperty.py
- Will sync between main property and operation
- Makes sure scene shows correct picture from the very beginning
=> Deal more consistently with dither

meerk40t/core/elements.py, meerk40t/core/node/groupnode.py
resolves https://github.com/meerk40t/meerk40t/issues/1443
=> Add additional info to group label

meerk40t/gui/simulation.py
Some changes according to feedback
=> Timed simulation update

meerk40t/core/cutcode.py, meerk40t/gui/laserrender.py, meerk40t/gui/simulation.py
Add basic cutcode editing capability inside preview:
=> Add basic cutcode editor

meerk40t/grbl/device.py, meerk40t/gui/choicepropertypanel.py, meerk40t/moshi/device.py
Fixes some inconsistencies / non-working updates for moshi + grbl
=> Fixes for moshi + grbl settings

meerk40t/core/cutplan.py, meerk40t/core/planner.py, meerk40t/tools/pathtools.py
=> Allow tolerance for inner burn optimisations

meerk40t/core/element_commands.py, meerk40t/core/elements.py
* Update notewindow when the `note` command is used.
* Update notewindow when the file-new menu is used.
=> Note Corrections

meerk40t/core/element_commands.py, meerk40t/core/element_treeops.py, meerk40t/core/elements.py, meerk40t/core/node/README.md, meerk40t/core/node/elem_image.py, meerk40t/core/node/node.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_hatch.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py, meerk40t/core/node/refnode.py, meerk40t/core/undos.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/wxmtree.py
* Fix remaining issues in undo
=> Undo Correction

meerk40t/core/element_commands.py, meerk40t/core/elements.py
Fixes reported error of non-classified elements generated via the console
=> Classify: consistent treatment after complete cmd execution

meerk40t/core/element_treeops.py, meerk40t/core/undos.py
Several minor bug fixes.
* Note this is for minor bug fixes to be merged into main whenever. Not a bunch of weird features.
=> 0.8.2 bug fixes

meerk40t/core/cutcode/cubiccut.py, meerk40t/core/cutcode/cutcode.py, meerk40t/core/cutcode/cutgroup.py, meerk40t/core/cutcode/cutobject.py, meerk40t/core/cutcode/dwellcut.py, meerk40t/core/cutcode/gotocut.py, meerk40t/core/cutcode/homecut.py, meerk40t/core/cutcode/inputcut.py, meerk40t/core/cutcode/linecut.py, meerk40t/core/cutcode/outputcut.py, meerk40t/core/cutcode/plotcut.py, meerk40t/core/cutcode/quadcut.py, meerk40t/core/cutcode/rastercut.py, meerk40t/core/cutcode/rawcut.py, meerk40t/core/cutcode/setorigincut.py, meerk40t/core/cutcode/waitcut.py, meerk40t/core/cutplan.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_hatch.py, meerk40t/gui/laserrender.py, meerk40t/ruida/emulator.py
Remove Parameter class from Cutcode object.
=> Cutcode without parameter

meerk40t/core/cutplan.py, meerk40t/core/element_commands.py, meerk40t/fill/fills.py, meerk40t/tools/pathtools.py
Polycut some path with a polygon.
Currently this does a very basic check as to whether the node is inside the other cutting polygon or not and deletes those nodes which are not contained.
=> Adds in basic polycut function.

meerk40t/gui/icons.py, meerk40t/tools/livinghinges.py
Shape based hinges finally work. Still using non-numpy code as that does not seem to work properly.
~~Amend algorithm so that it breaks paths and not shortens them:~~
Done:
=> Living hinges

meerk40t/core/units.py, meerk40t/tools/livinghinges.py
a) Direct entry of cell-width/height and padding values
b) Preview of target shape
c) Allow preview to be turned off
d) Preview update in UI thread
=> Some usability updates

meerk40t/gui/propertypanels/propertywindow.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmribbon.py, meerk40t/tools/livinghinges.py
a) Additional toolbar button (plus slight rearrangement):
b) Fix for close button not closing
=> Additional toolbar button

meerk40t/core/element_commands.py, meerk40t/gui/choicepropertypanel.py
=> User defined delay before trace hull

meerk40t/core/node/elem_image.py, meerk40t/gui/propertypanels/rasterwizardpanels.py, meerk40t/image/imagetools.py
a) Reestablishes image manipulation
b) Fixes a couple of crashes for certain image types where no colors have been set
=> Reestablish image manipulation functionality 

meerk40t/tools/geomstr.py, test/test_geomstr.py
Adds math function to the Geomstr class.
* bbox for line, cubic, quad.
* extremes test for quad, cubic
* point() for line, cubic, quad
* arc_center() for arc
* arc_radius() for arc
=> Geomstr Math

meerk40t/core/cutcode/cutcode.py, meerk40t/core/cutcode/rastercut.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py
Fixing incorrect "native_speed" calculation (was taking "speed" as default which needs to be amended to be brought to native units)
=> Fix wrong time estimates (hopefully)

meerk40t/core/element_treeops.py, meerk40t/core/node/op_raster.py
a) Add dpi as possible display element
b) Apply tree operations not only to a single node but to all selected nodes (of the same type)
=> Selection aware treeops

meerk40t/gui/laserrender.py, meerk40t/tools/geomstr.py, test/test_geomstr.py
Wrote an easier function for finding the intersections between different geoms.
=> Geomstr Intersection Math

meerk40t/core/element_commands.py, meerk40t/core/element_treeops.py, meerk40t/core/node/elem_image.py, meerk40t/gui/propertypanels/imageproperty.py, meerk40t/gui/scenewidgets/selectionwidget.py
Bugfix for tree op dpi assignment
Recalculate proper image after rotation and resizing
=> Autocrop and proper image update

meerk40t/gui/spoolerpanel.py
Logged spooler history could still end up to be incompatible to latest extensions
=> Format conversion for logged spooler history

meerk40t/tools/geomstr.py, test/test_geomstr.py
Previous versions figured it was best to just take have geoms provide a `.geometry` interface, but rather than that it's probably a lot better to us the input type to decide for the primary options: Global (None), slice, int, array (5*complex), array(int).
Extra functions (global):
1. Merge (May get own subclass)
2. Generator
3. Two_Opt_Distance
=> Geometry/Geomstr Merging

meerk40t/core/element_commands.py
=> Add 'simplify' command for line segments

meerk40t/core/element_commands.py, meerk40t/core/elements.py, meerk40t/fill/patternfill.py, meerk40t/tools/livinghinges.py
Shouldn't break any upcoming changes coming from geometry
a) Apply 'simplify' to the created path
b) Try to bring down the necessity for more sophisticated checks by a quick check for outsideness
=> Living hinges - slight adjustments

meerk40t/core/elements.py
Use denominator of determinants to establish same slope
=> Use arithmetically more stable functions

meerk40t/core/node/op_raster.py, test/bootstrap.py, test/test_drivers_grbl.py, test/test_drivers_lihuiyu.py
=> Driver Tests

meerk40t/svgelements.py, meerk40t/tools/geomstr.py, test/test_geomstr.py
Port the Geomstr Changes from Living Hinge branch
=> Geomstr Changes from the geomstr-hinge branch

meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/toolellipse.py
Circle wasnt created if stayed with the mouse pointer on one of the two major axes
=> Fix circle creation bug

meerk40t/camera/gui/camerapanel.py
Make the functionality available in the camera panel as well
=> Add camera detection option to camera panel

meerk40t/balormk/controller.py, meerk40t/balormk/gui/balorcontroller.py
- Fix usage of wrong 'connected'-attribute
- Better recovery if no driver is found
=> Balor: Some gui fixes / better connectivity recovery

meerk40t/gui/navigationpanels.py, meerk40t/gui/propertypanels/attributes.py
=> Add ratio lock in object property panel

meerk40t/core/element_commands.py, meerk40t/gui/opassignment.py
=> Outline fixes

meerk40t/core/node/elem_line.py
=> Fix elem line crash

meerk40t/balormk/controller.py, meerk40t/balormk/device.py, meerk40t/balormk/gui/gui.py, meerk40t/balormk/plugin.py, meerk40t/core/elements.py, meerk40t/core/units.py, meerk40t/gui/wxmmain.py, meerk40t/image/imagetools.py, meerk40t/lihuiyu/plugin.py, meerk40t/ruida/device.py
Going through the minor bug fixes from the Crash Logs.
=> 0.8.2 bug fixes (Group A)

meerk40t/balormk/driver.py, meerk40t/core/drivers.py, meerk40t/core/spoolers.py, meerk40t/grbl/driver.py, meerk40t/gui/navigationpanels.py, meerk40t/lihuiyu/driver.py, meerk40t/moshi/driver.py
a) Add physical_home command to drivers, allowing override of logical home.
b) Add tooltip and right mouse click action to home button in jog panel
=> Add support for physical home

meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/propertypanels/imageproperty.py, meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/propertypanels/pointproperty.py, meerk40t/gui/propertypanels/textproperty.py, meerk40t/gui/wxmeerk40t.py
a) Separate 'lock'attribute from xy-panel
b) elem line did not have any property panel associated to it
=> Add propertypanel for elem line

meerk40t.py, meerk40t/core/cutplan.py, meerk40t/core/elements.py, meerk40t/core/exceptions.py, meerk40t/core/output.py, meerk40t/core/svg_io.py, meerk40t/device/ruida/ruidadevice.py, meerk40t/dxf/dxf_io.py, meerk40t/gui/lhystudios/lhystudiosdrivergui.py, meerk40t/gui/scene/scenewidgets.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py, meerk40t/kernel.py, meerk40t/svgelements.py, meerk40t/tools/rastergrouping.py, setup.py
Update Legacy 0.7.x branch with bug fixes from crash log.
=> Legacy 0.7.9 (Bug Fixes)

meerk40t/gui/wxmribbon.py
Toggle button with resize parameter could crash
=> Fix rare crash

meerk40t/extra/hershey.py, meerk40t/gui/toolwidgets/toolmeasure.py
a) Fix non appearing lines for measurement tool
b) Fix non appearing lines for Linetext tool
=> Two Linux fixes

meerk40t/gui/propertypanels/groupproperties.py, meerk40t/gui/wxmeerk40t.py
Display basic information about the file as the current default is just an empty panel which is confusing.
=> Add File Property Panel

meerk40t/gui/navigationpanels.py
Both are working on all elements now
=> Make trace behaviour in navigation panel consistent with laserpanel

meerk40t/grbl/controller.py, meerk40t/grbl/device.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/grbl/gui/grblserialcontroller.py, meerk40t/grbl/interpreter.py, meerk40t/grbl/mock_connection.py, meerk40t/grbl/serial_connection.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/spoolerpanel.py
* Use "option" for com ports, show description rather than underlying value.
=> ComPorts -> Serial Ports. Many GRBL improvements.

meerk40t/core/node/elem_path.py, meerk40t/core/svg_io.py
Fix loading and saving bugs for Stroke Scaling
=> Stroke scaling IO

meerk40t/extra/hershey.py, meerk40t/gui/hersheymanager.py, meerk40t/tools/ttfparser.py
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html
TTF is a pretty giant format but it's very well documented. I parse the needed tables to, in theory, make a vector font. However the CMAP4 is broken from my test font. And the contours are also wrong in some weird ways. Though the whole type and see the font appear thing is pretty nice.
=> True Type Font as vector font rendering

meerk40t/core/element_treeops.py, meerk40t/grbl/driver.py, meerk40t/gui/propertypanels/blobproperty.py, meerk40t/gui/propertypanels/opblobproperty.py, meerk40t/gui/wxmeerk40t.py
a) Fix involuntary deletion of blob when executing 'Remove unused' from tree
b) Add blob deletion option in tree
c) (Untested) code change to blob execution in grbl
d) Add property display panel for blobs (Hex-Codes)
=> Some blob handling + blop property panel

meerk40t/core/element_treeops.py, meerk40t/grbl/parser.py, meerk40t/gui/propertypanels/blobproperty.py
Speedup + alternative view
Some fixes to GRBL parser to allow at least basic import, some fixes outstanding:
a) $J unrecognised
b) Import does not acknowledge different origin, so mirrored in Y-axis (for standard GRBL origin bottom left)
c) Import has some flaws in recognising moves?!
MK: 
LaserGRBL:
But going in the right direction and fit for further testing
=> GRBL Parser - some fixes

meerk40t/grbl/device.py, meerk40t/grbl/driver.py
Allow GRBL line ending customization.
We by default had \r line-ending this was hard-coded into our gcode. produced. We can now select the type of line ends we would prefer in configuration.
=> GRBL Line Endings

meerk40t/core/element_treeops.py, meerk40t/grbl/parser.py, meerk40t/gui/dialogoptions.py, meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/gui/wxmeerk40t.py
A couple of enhancements for the GCode parsing
1.  Allow user-defined options for parsing (should still work with some sensible defaults in a cli only version)
2.  Allow interpretation of z-values as laser on (for CNC mills)
3.  Recreates operations out of GCode
4.  Allow multipass codes (eg milling down pockets) to be simplified
=> Add grbl conversion options

meerk40t/grbl/parser.py
=> grbl import: Take different origin options into account

meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_hatch.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py
Now that we make more use of descriptions of cutnodes a default value has been introduced
=> Add label default

meerk40t/gui/propertypanels/groupproperties.py
Show information how many elements (recursively) this node contains
=> Add more information to file/group property

meerk40t/gui/preferences.py, meerk40t/kernel/kernel.py, meerk40t/kernel/settings.py
=> Allow backup and restore of settings

meerk40t/gui/scene/scene.py, meerk40t/gui/utilitywidgets/cyclocycloidwidget.py
Makes it easier to modify the major and minor radius for the cyclocycloids by small amounts.
=> Minor tweaks to Cyclocycloid

meerk40t/core/element_treeops.py
I have encountered way too many nested groups in SVGs, so I decided to write a command to address this if needed:
Collapses unneeded nesting (single group under another group)
Example, before:
After:
=> Add group simplification command to tree operations

meerk40t/core/node/elem_text.py
=> Apply rotate parameter

meerk40t/core/node/elem_text.py, meerk40t/gui/propertypanels/textproperty.py
a) Make sure bounds are properly updated after changing attributes in propertypanel
b) Circumvent font family regex issue for now
=> Some more font fixes

meerk40t/gui/navigationpanels.py
=> Update Laserposition in Jog-Pane

locale/de/LC_MESSAGES/meerk40t.po, meerk40t/core/element_treeops.py, meerk40t/gui/hersheymanager.py, meerk40t/gui/toolwidgets/toollinetext.py, meerk40t/gui/wxmscene.py
a) Fix missing classification
b) Add import of ttf-Files from Windows-Font-Directory
c) Allow filtering of font-types during creation
d) More user-friendly interaction while having no fonts - icon will open font-manager instead of being disabled
=> Some Linetext fixes

meerk40t/gui/hersheymanager.py, meerk40t/gui/keymap.py, meerk40t/gui/preferences.py, meerk40t/gui/wordlisteditor.py, meerk40t/gui/wxmmain.py
=> Add Edit Menu

meerk40t/core/element_commands.py, meerk40t/core/elements.py, meerk40t/gui/wxmmain.py
Should work much better if not fine ;-)
=> Fixed group handling during align

meerk40t/core/element_treeops.py, meerk40t/gui/consolepanel.py, meerk40t/gui/executejob.py, meerk40t/gui/laserpanel.py, meerk40t/gui/simulation.py
Prevents multiple executions of plan stages in "Execute Job" window if user impatiently clicks the button multiple times...
=> Prevent duplicate exexution of plan steps

meerk40t/ch341/libusb.py, meerk40t/lihuiyu/controller.py, meerk40t/ruida/control.py, meerk40t/ruida/emulator.py, meerk40t/ruida/exceptions.py, meerk40t/ruida/plugin.py, meerk40t/ruida/rdjob.py
Implement the Job-Emulator division for Ruida.
This is slightly harder than with gcode where the demarcation was obvious. In this case what should be done in the emulator and what should be done by the job is a bit less well established.
=> Emulator/Job Division Ruida

meerk40t/core/element_treeops.py, meerk40t/gui/propertypanels/operationpropertymain.py
Simplify enabling/disabling/toggling of operations:
- On an operation level:
- On a global level:
=> Add menu-options for operation enabling

meerk40t/core/elements.py
Making sure nested groups are dealt with properly. Hopefully the very last fix required.
=> Another alignment fix

meerk40t/gui/alignment.py, meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenepanel.py, meerk40t/gui/scenewidgets/attractionwidget.py, meerk40t/gui/scenewidgets/bedwidget.py, meerk40t/gui/scenewidgets/elementswidget.py, meerk40t/gui/scenewidgets/gridwidget.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/simulation.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/toolcontainer.py, meerk40t/gui/toolwidgets/tooldraw.py, meerk40t/gui/toolwidgets/toolellipse.py, meerk40t/gui/toolwidgets/toollinetext.py, meerk40t/gui/toolwidgets/toolmeasure.py, meerk40t/gui/toolwidgets/toolnodeedit.py, meerk40t/gui/toolwidgets/toolpoint.py, meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/toolwidgets/toolpolyline.py, meerk40t/gui/toolwidgets/toolrect.py, meerk40t/gui/toolwidgets/toolrelocate.py, meerk40t/gui/toolwidgets/toolribbon.py, meerk40t/gui/toolwidgets/tooltext.py, meerk40t/gui/toolwidgets/toolvector.py, meerk40t/gui/wxmscene.py, meerk40t/gui/wxmtree.py, meerk40t/rotary/gui/rotarysettings.py
Refactor SceneWidgets to be more consistent.
* Remove non-valid scene stuff, place in wxmscene
* Refactor guide widget for readability.
=> Refactor SceneWidget

.github/workflows/codeql-analysis.yml
=> Update CodeQL to use v2

meerk40t/grbl/gcodejob.py
* Ensure all the gcode standard command lines have encoding.
* Add in various grbl specific errors
=> Gcode/Grbl Expansion

meerk40t/core/node/op_raster.py
``text Test`` wasn't classified
=> Fix missing elem text classification

meerk40t/core/element_commands.py
``property-set property value`` will allow the generic application of a new value to a node property.
```
property-set stroke blue
property-set x 2cm
property-set font_size 48
property-set lock 0
property-set label dummy
```
are all valid examples
=> Generic node attribute command

meerk40t/core/cutplan.py, meerk40t/core/laserjob.py, meerk40t/core/spoolers.py, meerk40t/core/units.py, meerk40t/lihuiyu/device.py
Minimized PR for jobs getting bounds.
=> Project Focus: Jobs get bounds

meerk40t/kernel/kernel.py, meerk40t/kernel/settings.py, meerk40t/main.py
Simplifies recovery from a faulty configuration
=> Command line option to ignore settings at startup

meerk40t/balormk/plugin.py, meerk40t/device/dummydevice.py, meerk40t/grbl/plugin.py, meerk40t/gui/devicepanel.py, meerk40t/lihuiyu/plugin.py, meerk40t/moshi/plugin.py, meerk40t/ruida/plugin.py
=> More sophisticated device selection dialog during creation

meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/toolwidgets/toolpolyline.py, meerk40t/gui/toolwidgets/toolvector.py
- Allow right mouse button to end design
- Add angle-snap while pressing the alt-key
=> Amend polyline, polygon vector tool

.github/workflows/mac11_pyinst.yml
that he didn't make a pull request for, and then complained because they didn't get included.
=> paiin's mac runner changes

meerk40t/core/laserjob.py, meerk40t/gui/spoolerpanel.py
a) Fix wrong estimate at job end
b) Fix display issue for passes in history
c) Restore time logic for history cleanup
=> Spooler fixes

.github/workflows/unittests.yml
jpirnay's ill-fated commit, cherry-picked into the proper location.
=> Change ubuntu-reference

meerk40t/extra/hershey.py, meerk40t/gui/toolwidgets/toollinetext.py
As the previous PR was having gitfu artifacts in it, this a new attempt to bring it forward
=> Fix Linetext tool if no/an invalid font was set

meerk40t/core/cutplan.py, meerk40t/core/planner.py
* The copy and copy-selected plan function only deviate by whether you copy all the operation or whether you copy the selected operation. These should be combined and simply use the command name to show those differences.
=> Combine `copy` and `copy-selected` functions

meerk40t/newly/controller.py
* Corrects raster speed for newly (previously it instantly unset)
=> Correct Raster Speed Newly

meerk40t/core/svg_io.py
* Adds an undo mark between elements loaded and operations replaced.
If your save file loads operations, the first undo will undo the operations change the second undo will undo the shapes.
=> Add an undo mark between elements loaded and operations replaced.

meerk40t/gui/navigationpanels.py, meerk40t/gui/position.py
Remove SizerPanel in Navigation and use another (reduced) instance of PositionPanel instead
=> Use existing pane for size in transformation

meerk40t/extra/imageactions.py, meerk40t/gui/propertypanels/imageproperty.py
- Fixed non-refresh after image keyhole and split
- Fixed some gui inconsistencies with image crop action
=> Some image fixes

meerk40t/core/elements/element_treeops.py
Allow the simple duplication of placement nodes to generate grids:
=> Add context menu option for grid placements

meerk40t/core/elements/element_treeops.py, meerk40t/gui/wxmscene.py
- Fixing residual bug from scene.pane introduction
-  Add context menu for regmark elements to act as magnet template
=> Fix magnet code

meerk40t/core/elements/elements.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py
Magnetlines are saved / restored - this might help with betaetas setup of a usable area:
1) Preparation
2) Use
=> Make magnets persistent

meerk40t/core/cutplan.py, meerk40t/core/planner.py, meerk40t/gui/busy.py, meerk40t/gui/executejob.py, meerk40t/gui/laserpanel.py, meerk40t/gui/simulation.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py
=> Visual feedback during planning stages

meerk40t/core/node/nutils.py
=> Fix Issue #1829,  do not yield empty cutgroups

meerk40t/grbl/device.py
Use perthou rather than percent.
#1860
=> Fixes issue #1860 reddot fractional strength

meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenepanel.py, meerk40t/gui/scene/widget.py, meerk40t/gui/scenewidgets/affinemover.py, meerk40t/gui/utilitywidgets/controlwidget.py, meerk40t/gui/wxmscene.py
Affine mover uses 3 points to calculate the affine transformation matrix and uses changes to those points to modify the selected paths.
=> Adds in Affine Mover for Selection Widget

meerk40t/core/webhelp.py
Help + Feature request/feedback takes you to: https://github.com/meerk40t/meerk40t/discussions/1318
This is a Poll:
(and is factually out of date since 0.8 is no longer in beta!!)
I am changing this to the new discussion page...
=> Improve feature request/feedback URL

meerk40t/gui/wxmmain.py
String changes only.  Source code changes on GH - **not tested**.
=> Improve Config/Scene/Snap tooltips and labels

meerk40t/core/elements/element_types.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/offset.py, meerk40t/core/elements/shapes.py, meerk40t/core/node/elem_ellipse.py, meerk40t/core/node/elem_line.py, meerk40t/core/node/elem_path.py, meerk40t/core/node/elem_point.py, meerk40t/core/node/elem_polyline.py, meerk40t/core/node/elem_rect.py, meerk40t/device/gui/formatterpanel.py, meerk40t/dxf/dxf_io.py, meerk40t/extra/ezd.py, meerk40t/extra/imageactions.py, meerk40t/gui/materialtest.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/toolellipse.py, meerk40t/gui/toolwidgets/toolrect.py, meerk40t/tools/kerftest.py, test/test_core_elements.py
* Remove most initialization based on svgelements node items
=> 0.9.x: Geom Node Initialization

meerk40t/gui/wxmtree.py
=> Mac tree fix - legacy8

meerk40t/core/elements/align.py, meerk40t/core/elements/branches.py, meerk40t/core/elements/materials.py, meerk40t/core/elements/shapes.py, meerk40t/device/gui/defaultactions.py, meerk40t/grbl/emulator.py, meerk40t/gui/scenewidgets/machineoriginwidget.py, meerk40t/gui/wxmscene.py, meerk40t/gui/wxmtree.py, meerk40t/ruida/rdjob.py, meerk40t/tools/pathtools.py
=> Codecy legacy8 patch

meerk40t/core/plotplanner.py
=> Correct dot_length vs implicit_dotlength value.

meerk40t/camera/plugin.py
Server will launch a basic mjpeg server for a camera.
=> Adds `server` command to camera.

meerk40t/camera/gui/camerapanel.py, meerk40t/gui/scene/scene.py, meerk40t/gui/scene/scenepanel.py, meerk40t/gui/simulation.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmscene.py, meerk40t/kernel/kernel.py
* Reduce the amount of checks for new scheduled jobs.
* Reduce the speed of checks for new signals
=> Use fewer resources

meerk40t/gui/laserpanel.py, meerk40t/gui/navigationpanels.py, meerk40t/gui/plugin.py, meerk40t/gui/simpleui.py, meerk40t/gui/wxmeerk40t.py, meerk40t/main.py
Add Simple-UI for very trivial interface and control UI. Suitable for a 5in rPI touch-screen.
#1944
=> Simple UI #1944

meerk40t/core/cutcode/cutcode.py, meerk40t/core/cutcode/rastercut.py, meerk40t/core/laserjob.py, meerk40t/core/node/op_image.py
* Check and tweak time-estimation routine for driver.
=> Corrections and Tweaks to Time-Estimate

.github/workflows/win/file_version.txt, meerk40t/core/cutcode/cutcode.py, meerk40t/core/cutcode/plotcut.py, meerk40t/core/cutcode/rastercut.py, meerk40t/core/laserjob.py, meerk40t/core/node/blobnode.py, meerk40t/core/node/elem_image.py, meerk40t/core/node/mixins.py, meerk40t/core/node/op_image.py, meerk40t/core/spoolers.py, meerk40t/extra/ezd.py, meerk40t/extra/updater.py, meerk40t/grbl/controller.py, meerk40t/gui/alignment.py, meerk40t/gui/laserpanel.py, meerk40t/gui/navigationpanels.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/gui/simulation.py, meerk40t/gui/spoolerpanel.py, meerk40t/gui/toolwidgets/toolnodeedit.py, meerk40t/main.py, meerk40t/ruida/device.py, meerk40t/ruida/emulator.py, setup.cfg
(cherry picked from commit 1cd4e7e2360ab0dfc50987502169cbcc757856bc)
cherry picked #1955
=> 0.8.x bug fixes

.github/workflows/win/file_version.txt, meerk40t/device/lhystudios/lhystudiosdevice.py, meerk40t/device/moshi/moshidevice.py, meerk40t/device/ruida/ruidadevice.py, meerk40t/gui/lhystudios/lhystudioscontrollergui.py, meerk40t/gui/wxmtree.py, meerk40t/image/imagetools.py, meerk40t/main.py, meerk40t/tools/rastergrouping.py, setup.cfg
Bug fixes for legacy 7 version.
=> Legacy 7: Bug Fixes.

meerk40t/extra/lbrn.py, meerk40t/internal_plugins.py
If the hope is to let people transition from lightburn to much more hackable software, we need to be able to parse the files they built-up in that time.
Processes most known object types. Does not yet work with groups, and children within those groups. And could easily mess up if there's something that isn't like what I saw before.
=> Lightburn file reader.

meerk40t/extra/ezd.py
Fix the extend axis commands (not read).
Also correct a strange multi-layer hatch object failure.
=> Corrections to ezd reader

meerk40t/balormk/controller.py, meerk40t/balormk/device.py
=> Galvo Rotary

meerk40t/core/elements/element_treeops.py, meerk40t/gui/navigationpanels.py, meerk40t/gui/position.py, meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/propertypanels/propertywindow.py
Fixes https://github.com/meerk40t/meerk40t/issues/1974
=> Sync updates on element move/scale

meerk40t/gui/ribbon.py, meerk40t/gui/wxmmain.py
a) button enabled status are updated now on page change
b) Reestablish right click mouse actions for some buttons
=> Ribbon bar fixes

meerk40t/core/treeop.py, meerk40t/extra/inkscape.py, meerk40t/gui/scenewidgets/machineoriginwidget.py, meerk40t/gui/simpleui.py, meerk40t/gui/wxmmain.py
- Fixes issue https://github.com/meerk40t/meerk40t/issues/1940
- Fixes the invalid shape of the machine origin widget on Linux
=> Address ampersand display issues

meerk40t/gui/ribbon.py
A couple of additional visual fixes
- avoid unneccesary label breaks
- show all icons on dropdown menu
=> Some more ribbonbar adjustments

meerk40t/balormk/controller.py, meerk40t/balormk/device.py
* adds `rotary_relative` command.
* add `rotary_home` command.
* add `rotary_pos -i 1` as acceptable command.
=> Rotary Tweaks

.github/workflows/win.yml
=> Fixes build issue. Lock Pillow 9.5.0, unrestrict wxPython, update Pyinstaller

meerk40t/gui/ribbon.py, meerk40t/gui/wxmribbon.py, meerk40t/gui/wxmtools.py
Does not address the fundamental refresh issue
=> Ribbonbar changes

meerk40t/gui/ribbon.py
Every ribbonbar needs its own job = unique jobname
=> Initial redraw fix

meerk40t/gui/ribbon.py, meerk40t/gui/wxmribbon.py, meerk40t/gui/wxmtools.py
=> RB: Auto orientation and multi column

meerk40t/gui/ribbon.py
=> Add vertical tabs

meerk40t/core/undos.py, meerk40t/extra/updater.py, meerk40t/gui/ribbon.py, meerk40t/gui/scenewidgets/elementswidget.py, meerk40t/gui/spoolerpanel.py, meerk40t/lihuiyu/tcp_connection.py
Addressing some of the bugreports in discord #bugreports
=> Multiple bugfixes

meerk40t/gui/wxmtree.py
Addresses https://github.com/meerk40t/meerk40t/issues/2018
=> Update Warn indicator more consistently

.github/workflows/win/file_version.txt, meerk40t/grbl/device.py, meerk40t/lihuiyu/device.py, meerk40t/main.py, meerk40t/moshi/device.py, meerk40t/ruida/device.py, setup.cfg
Corrects device rotary settings saving issue.
=> Corrects issue #2027

meerk40t/core/elements/offset.py, meerk40t/core/node/elem_polyline.py
a) The polyline nodes as_path was plain wrong - fixed - Not sure what consequences this has
b) The logic within the pyclipr wrapper to deal with artifacts got lost - reestablished
=> Two relevant fixes

translate_check.py
- Fixed a missed case 
- Added some documentation
- Addressed some codacy concerns
=> Fixes + doc for translate_check.py

meerk40t/core/elements/offset.py
=> Fixing offset-routine (kerf)

meerk40t/gui/wxmscene.py, meerk40t/lihuiyu/controller.py, meerk40t/lihuiyu/driver.py, meerk40t/moshi/driver.py
Fixes #2058 
* Anything writing an abort to realtime triggers `abort_waiting`. Abort waiting set to false on abort.
=> Fix issues #2058

meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/statusbarwidgets/infowidget.py
Reduce precision for simple information purposes
=> Reduced precision for info-calculation

meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmscene.py
Update for issue #2078 
This is intended to update the site though other elements need to get fixed and checked first and any updates the protocol implemented prior to the next 0.8.x series and the next RC for 0.9.1
=> Update crash log site

.github/workflows/win/file_version.txt, meerk40t/core/cutcode/plotcut.py, meerk40t/core/elements/offset.py, meerk40t/core/node/node.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py, meerk40t/core/planner.py, meerk40t/grbl/plugin.py, meerk40t/gui/scenewidgets/guidewidget.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmscene.py, meerk40t/lihuiyu/controller.py, meerk40t/lihuiyu/driver.py, meerk40t/main.py, meerk40t/moshi/driver.py, meerk40t/ruida/emulator.py, meerk40t/ruida/rdjob.py, setup.cfg
Correct some issues outlined in:
#2058
=> 0.8.x Bug Fixes Addendum

meerk40t/core/elements/elements.py, meerk40t/core/node/node.py, meerk40t/gui/basicops.py, meerk40t/gui/statusbarwidgets/defaultoperations.py
a) always create a copy of a default node
b) adjust the copy logic of node.py to have a full set of attributes
=> Adjust node assignment logic for default operations

meerk40t/gui/position.py
So far amending an elements / group of elements position was always the left top corner.
You can now change the position according to a user-definable position:
TL TC TR
CL CC CR
BL BC BR
=> Allow refined position setting

meerk40t/core/node/op_raster.py
=> remove no longer required matrix argument

meerk40t/extra/param_functions.py, meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/wxmmain.py
- Addition of ``cycloid`` as parametric command: ``cycloid 5cm 5cm 1cm 0.95cm 20``
- Addition of dragon fractal ``fractal_dragon`` as parametric command: ``fractal_dragon 4cm 4cm 0.1cm 10``
- Minor cosmetical fixes to highlight the selected subtools for the polygon tool
=> Cycloid/ Fractals

meerk40t/core/node/elem_point.py, meerk40t/core/node/node.py, meerk40t/core/parameters.py, test/test_drivers_lihuiyu.py, test/test_geomstr.py
This bug causes the updated operations within the same session to fail to update and to only use file-loaded level session setting.
=> Correct Operation Copy Bug

meerk40t/balormk/clone_loader.py, meerk40t/balormk/controller.py, meerk40t/balormk/device.py, meerk40t/balormk/usb_connection.py
`clone_init <file>` will save your clone file preference. The hashes will be used to determine the offset and it should check the local directory, the meerk40t directory, or if using windows %systemroot%/system32/driver (where the file often gets copied).
=> Use galvo-clone file first checking.

meerk40t/gui/icons.py, meerk40t/gui/laserpanel.py, meerk40t/gui/spoolerpanel.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxutils.py
Hopefully colors with better contrast in the laserpanel
old:
new:
=> Contrast colors

meerk40t/core/elements/elements.py, meerk40t/core/svg_io.py, meerk40t/gui/laserpanel.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py
Allow supression of colored items in the tree
=> Colored tree

.github/workflows/win.yml, README.md
* Due to a numpy issue where an incompatible windows7 32-bit numpy is provided we need to update this code to peg the version lower.
=> Commit windows7 changes for building

meerk40t/extra/updater.py, meerk40t/gui/about.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py
Allow specification how often mk should look for new versions: every startup, once per day, once per week
=> Check for Update Frequency

meerk40t/core/elements/offset.py, meerk40t/gui/propertypanels/attributes.py
Resolves https://github.com/meerk40t/meerk40t/issues/2149
=> Addresses issue #2149 for 0.8

meerk40t/gui/propertypanels/attributes.py
Resolves https://github.com/meerk40t/meerk40t/issues/2149
=> Address issue #2149 for 0.9

meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py
=> Enable High-DPI for Windows

meerk40t/fill/patternfill.py, meerk40t/fill/patterns.py, meerk40t/tools/livinghinges.py
- Some fixes to get on top of invalid stored parameters 
- Removed old code use and focus only on geomstr based routines
Open issue: geomstr.Clip is not working as expected
=> Living Hinges First Steps

.github/workflows/win/file_version.txt, meerk40t/core/elements/elements.py, meerk40t/core/elements/trace.py, meerk40t/core/node/mixins.py, meerk40t/dxf/dxf_io.py, meerk40t/extra/lbrn.py, meerk40t/grbl/controller.py, meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/propertypanels/pathproperty.py, meerk40t/gui/scenewidgets/bedwidget.py, meerk40t/lihuiyu/device.py, meerk40t/main.py, meerk40t/ruida/emulator.py, meerk40t/ruida/rdjob.py, setup.cfg, test/test_ruida.py
=> Crash Reports Bug Fixes

meerk40t/balormk/plugin.py, meerk40t/camera/plugin.py, meerk40t/grbl/plugin.py, meerk40t/gui/plugin.py, meerk40t/gui/wxmeerk40t.py, meerk40t/kernel/context.py, meerk40t/kernel/functions.py, meerk40t/kernel/settings.py, meerk40t/lihuiyu/plugin.py, meerk40t/moshi/plugin.py, meerk40t/newly/plugin.py, meerk40t/ruida/plugin.py, test/bootstrap.py, test/test_drivers_grbl.py, test/test_drivers_lihuiyu.py, test/test_kernel.py
* Fix Windows Reset.
* Fix other related issues.
=> Windows Reset Fix

meerk40t/tools/geomstr.py
=> Living Hinge Fix

meerk40t/tools/geomstr.py, meerk40t/tools/livinghinges.py
=> Fix invalid hinge shift

meerk40t/internal_plugins.py, meerk40t/tools/geomstr.py, meerk40t/tools/livinghinges.py
Several bugfixes:
- ensure complete fill
- prevent endless loop
- crash at startup due to missing plugin invocation
=> Hinge pattern

meerk40t/tools/geomstr.py, test/test_geomstr.py
* Between two segments the error within the first segmentation could be such that it was actually out of that segment. The Zoom into that segment would, therefore, not find the correct result.
=> Correct Hinge Whiskers Bug

meerk40t/gui/choicepropertypanel.py, meerk40t/newly/device.py
=> Allow deletion / duplication of entries in newly raster chart

meerk40t/core/svg_io.py
This PR simply changes the way the svgio.SvgProcessing is laid out, rather than in a large monolithic code block, it's now sent out to smaller well controlled functions.
* The intention is to set the stage for improved parsing with regard to effects being part of groups. This also requires that operations be made groups too. Which deviates from the previous set of methods.
=> Simplify and Correct SVG writing.

meerk40t/core/elements/clipboard.py, meerk40t/core/elements/element_treeops.py, meerk40t/core/svg_io.py, meerk40t/gui/scenewidgets/selectionwidget.py
Address the reported qrcode, barcode crash: https://github.com/meerk40t/meerk40t/issues/2204
=> Use mk-specific properties not in parameters.py

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/shapes.py, meerk40t/core/node/effect_hatch.py, meerk40t/core/node/effect_wobble.py, meerk40t/core/node/node.py, meerk40t/gui/icons.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py, meerk40t/kernel/kernel.py
Node:
* Add `has_ancestor()` function
* Add `swap_nodes()` function to swap to node in same structure.
* Add `set_root()` function to set all sub functions.
* Fixes an error where loaded operation functions would not set the root.
Effect Hatch/Wobble:
* Adding a hatch to a hatch will nest them if they started at siblings. And will structure-swap them if they are not siblings.
* Allow PyEmbeddedImage.message_icon() classmethod to create an icon from a message. Utilizing EmptyIcon and PNGwriter.
* Kernel `sub_register` does not catch AttributeErrors that occur deeply into the code.
* `effect-hatch` command wraps the current selected items into hatch.
GUI:
* Hatch Button Added to create a hatch.
* Right-click elem `Apply Special` to apply specials rather than add specials.
=> Expand Hatch Effects

meerk40t/core/node/elem_image.py
Cursory change with Pillow for Pillow 10 to deprecate some usages.
Needs some testing.
=> Basic update for pillow 10 deprecations

meerk40t/gui/about.py, meerk40t/gui/consolepanel.py, meerk40t/gui/icons.py, meerk40t/gui/laserpanel.py, meerk40t/gui/mkdebug.py, meerk40t/gui/plugin.py, meerk40t/gui/ribbon.py, meerk40t/gui/spoolerpanel.py, meerk40t/gui/themes.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmscene.py
Addition of a ``context.themes`` service to centralise color/UI element lookups
=> Color Theme scaffolding

meerk40t/gui/propertypanels/attributes.py
Just to make more use of the icons ;-)
=> Display icon in id panel

meerk40t/balormk/device.py, meerk40t/device/dummydevice.py, meerk40t/device/mixins.py, meerk40t/grbl/device.py, meerk40t/lihuiyu/device.py, meerk40t/moshi/device.py, meerk40t/newly/device.py, meerk40t/ruida/device.py
Some attempt to standardize the device API with a mixin for the redundant code.
=> Pause Fix, Mixin and Status Standarization

meerk40t/core/node/elem_line.py, meerk40t/extra/imageactions.py, meerk40t/gui/imagesplitter.py, meerk40t/gui/toolwidgets/toolimagecut.py, meerk40t/gui/toolwidgets/toolline.py, meerk40t/gui/wxmscene.py, meerk40t/image/imagetools.py, meerk40t/tools/geomstr.py
* Add `tool line`
* Add `tool imagecut`
* `render_keyhole` command has more consistent options.
* Adds `image linecut` command to slice an image via a line.
* Line uses Functional Parameters.
* Improve `imageactions.py` calls to be documented and simplified.
* Add in Geomstr `append_lines` command
* Add in Geomstr `divide()` command
* Add in optional `breaks` flag for split.
* Add in optional `breaks` flag for polycut.
TODO:
=> Line Tool and ImageCut Tool, other background improvements.

meerk40t/tools/geomstr.py, test/test_geomstr.py
Essential we apply Bentley-Ottmann algorithm to create essentially a graph like this concerning polygons that already exist.
We can then use the chart to solve a variety of things from Point in Polygon to CAG operations fairly quickly. Since essentially this is all the needed information out of a single scanline. Each static beam has the list of active segments for that beam (and since we found the intersections) we have those segments already in sorted order. We also, change the events from being purely a `y-scanline` into being a point based scanline where x-values break the tie.
The result of this is that we will be able to identify valid purely horizontal lines. And since all these lines are valid and we know they are in order, we can find the insideness of a single polygon by …
=> ScanTable Computational Geometry

meerk40t/core/cutplan.py, meerk40t/core/planner.py
=> Raster optimisations: clustering of elements

.github/workflows/win/file_version.txt, README.md, meerk40t/core/cutplan.py, meerk40t/core/elements/element_treeops.py, meerk40t/core/planner.py, meerk40t/core/treeop.py, meerk40t/device/dummydevice.py, meerk40t/device/mixins.py, meerk40t/dxf/dxf_io.py, meerk40t/extra/imageactions.py, meerk40t/grbl/controller.py, meerk40t/grbl/device.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py, meerk40t/gui/wxmtree.py, meerk40t/gui/wxutils.py, meerk40t/image/imagetools.py, meerk40t/lihuiyu/device.py, meerk40t/main.py, meerk40t/moshi/device.py, meerk40t/ruida/device.py, meerk40t/tools/geomstr.py, setup.cfg, test/test_geomstr.py, test/test_kernel.py
=> 0.9.3 Beta 2: Final Touches

meerk40t/core/elements/element_treeops.py, meerk40t/core/node/elem_image.py, meerk40t/gui/propertypanels/imageproperty.py, meerk40t/image/imagetools.py
Add context menu to split images in the middle of relevant white areas.
~~Suffers currently from an image crop issue that needs resolution first.~~
=> elem image fix - automatic image split

.github/workflows/win/file_version.txt, meerk40t/core/elements/elements.py, meerk40t/core/node/elem_image.py, meerk40t/core/node/elem_rect.py, meerk40t/extra/lbrn.py, meerk40t/lihuiyu/gui/lhycontrollergui.py, meerk40t/lihuiyu/gui/tcpcontroller.py, meerk40t/main.py, setup.cfg
=> Final touches for version 0.9.3

meerk40t/gui/scenewidgets/laserpathwidget.py, meerk40t/gui/spoolerpanel.py
=> Spooler update during laser waits

meerk40t/core/elements/elements.py, meerk40t/core/elements/undo_redo.py, meerk40t/core/undos.py, meerk40t/gui/wxmmain.py
Address the new-undo issues.
Internalize the undo signals.
=> Internalize Undo Signals, Fix #2234

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/element_types.py, meerk40t/core/elements/elements.py, meerk40t/core/node/bootstrap.py, meerk40t/core/node/effect_warp.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_engrave.py, meerk40t/device/gui/formatterpanel.py, meerk40t/gui/laserrender.py, meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/toolwidgets/toolparameter.py, meerk40t/gui/wxmtree.py, meerk40t/tools/geomstr.py, meerk40t/tools/pmatrix.py, test/test_pmatrix.py
* Make functional parameters work for warp.
*  Allow it to apply to Effects allow nodes without matrixes to process points.
* Add Warp Special UI (tree menu item)
* Add in PMatrix perspective matrix.
* Add in Geomstr for warping a perspective matrix.
=> Effect Warp

meerk40t/core/elements/element_treeops.py
=> Issue #2272: Open containing folder for file

meerk40t/core/elements/shapes.py, meerk40t/gui/icons.py, meerk40t/gui/wxmmain.py
=> Add option to choose from registered hatches to toolbar

meerk40t/core/svg_io.py, meerk40t/dxf/dxf_io.py, meerk40t/image/imagetools.py
Some images have an exif rotation applied to them purely in metadata. This will provide those rotations if they exist.
=> Exif image rotation

meerk40t/gui/plugin.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py, meerk40t/kernel/__init__.py, meerk40t/kernel/kernel.py, meerk40t/main.py
Without actually swapping out the reference, patches in the ability to shift the languages at the kernel level.
=> Isolated Kernel Translation Features

meerk40t/grbl/controller.py, meerk40t/grbl/driver.py, meerk40t/grbl/emulator.py, meerk40t/tools/geomstr.py
Fix some GRBL assumptions for GRBLHal.
* [OPT parsing has exactly 3 elements.
* $$ will only have int and float values.
* Corrected \r\n `ok` reply. In GRBLHal that provides 1 ok, not 2. (Empty 0 byte commands do not get an ack).
=> GRBLHal compatibility corrections.

meerk40t/core/elements/element_treeops.py, meerk40t/tools/geomstr.py, test/test_geomstr.py
* Add Geomstr.image() to convert to path of image using pure numpy.
=> Add `Convert To Path` for Images

meerk40t/newly/driver.py
=> Newly-Driver Changes, Interpolation

.github/workflows/win/file_version.txt, meerk40t/extra/updater.py, meerk40t/gui/laserpanel.py, meerk40t/main.py, setup.cfg
If a bug or issue is found with the full release this should get any added bug fixes and be released shortly after the 0.9.3000 release.
=> 0.9.3 Post 2 (Candidate)

meerk40t/extra/param_functions.py, meerk40t/gui/icons.py, meerk40t/gui/toolwidgets/toolparameter.py, meerk40t/gui/toolwidgets/toolpolygon.py
Made regular polgyon design more logical. Added another tool
=> Polygon tool

meerk40t/gui/tips.py
=> Single-checkbox consent to interactive tips.

meerk40t/gui/laserpanel.py, meerk40t/gui/navigationpanels.py, meerk40t/gui/wxmeerk40t.py
=> Arbitrary size correction for Linux

meerk40t/gui/toolwidgets/toolimagecut.py, meerk40t/gui/toolwidgets/toolline.py, meerk40t/gui/toolwidgets/toolmeasure.py, meerk40t/gui/toolwidgets/toolpointlistbuilder.py, meerk40t/gui/toolwidgets/toolpolygon.py, meerk40t/gui/toolwidgets/toolpolyline.py
As quite a few tools use nearly the same code and the same logic (click on a couple of points and create an element from it), I have created a helper class the encapsulates all the ToolWidget logic and just needs a couple of overloaded functions per tool.
=> Unify all line based tools

meerk40t/tools/geomstr.py, test/test_geomstr.py
* Add test for BeamTable edge case.
* Correct edge case of overlapping position along a horizontal value
=> Fix BeamTable edge case.

meerk40t/gui/wxmmain.py
Supported clipboard formats:
- filenames: will be imported
- bitmap: an image object will be created
- text: a text element wil be created
=> Allow pasting from system clipboard

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/shapes.py, meerk40t/gui/wxmmain.py
- Icons did not call the right hatch
- Removal of a singe node out of a effect did not recalculate effect
=> A couple of hatch fixes

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/element_types.py, meerk40t/core/node/image_raster.py, meerk40t/core/node/op_raster.py, meerk40t/core/svg_io.py, meerk40t/device/gui/formatterpanel.py, meerk40t/gui/operation_info.py, meerk40t/gui/propertypanels/attributes.py, meerk40t/gui/propertypanels/imageproperty.py, meerk40t/gui/propertypanels/rasterwizardpanels.py, meerk40t/gui/wxmtree.py, meerk40t/image/imagetools.py
Update Image Passthrough Code to allow switching of images from passthrough to non-passthrough modes.
* Update the formatting value to show correctly.
* Auto-update the switched DPI from the image.
* Passthrough right-click values.
* Currently takes over the image drag-in loading.
=> Image Passthrough

.github/workflows/win/file_version.txt, meerk40t/core/elements/element_treeops.py, meerk40t/core/node/image_raster.py, meerk40t/device/gui/formatterpanel.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/image/imagetools.py, meerk40t/main.py, setup.cfg
* Version bump. Using the tens place of the minor releases.
* Stash Passthrough behind a `developer_mode()` check.
* Stash Warp behind a `developer_mode()` check.
=> Final Touches for 0.9.4 Beta 1

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/shapes.py, meerk40t/core/node/effect_hatch.py, meerk40t/core/node/effect_warp.py, meerk40t/core/node/effect_wobble.py, meerk40t/gui/propertypanels/hatchproperty.py, meerk40t/gui/wxmmain.py
- Allow substructures (groups, files) under effect hatch and effect wobble
- Fix inconsistent angle treatment in hatch propertypanel
=> Hatch fixes

meerk40t/balormk/controller.py, meerk40t/balormk/gui/balorcontroller.py, meerk40t/grbl/controller.py, meerk40t/grbl/device.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/moshi/driver.py, meerk40t/newly/controller.py, meerk40t/newly/gui/newlycontroller.py, meerk40t/ruida/controller.py, meerk40t/ruida/gui/ruidacontroller.py
* Reset on Connect.
* Require starting sequence.
=> GRBL Connection Robustness.

meerk40t/gui/simulation.py
=> Allow suppression of travel path

meerk40t/gui/busy.py, meerk40t/gui/navigationpanels.py, meerk40t/gui/position.py, meerk40t/gui/propertypanels/imageproperty.py
Addresses some comments in Issue #2328
=> Some layout adjustments

meerk40t/lihuiyu/driver.py
* Fixes dwell position for Lihuiyu driver
=> Lihuiyu driver move position for firing

meerk40t/core/node/elem_image.py, meerk40t/image/dither.py, meerk40t/image/imagetools.py, requirements-optional.txt
#2332
Brings speeds of dithers down to on par with Pillow.
We fallback to to the non-dithered versions if `numba` is not installed.
`pip install numba`
=> Implement Numba Fast Dithers

meerk40t/kernel/channel.py, meerk40t/network/tcp_server.py, meerk40t/ruida/control.py, meerk40t/ruida/driver.py, meerk40t/ruida/emulator.py, meerk40t/ruida/plugin.py, meerk40t/ruida/rdjob.py
=> RuidaControl - Bridge Mode.

meerk40t/balormk/driver.py, meerk40t/grbl/driver.py, meerk40t/kernel/kernel.py, meerk40t/lihuiyu/driver.py, meerk40t/moshi/driver.py, meerk40t/rotary/gui/gui.py, meerk40t/rotary/gui/rotarysettings.py, meerk40t/rotary/rotary.py, test/test_drivers_galvo.py, test/test_drivers_grbl.py, test/test_drivers_lihuiyu.py, test/test_drivers_moshi.py, test/test_drivers_newly.py
* All devices that previously had y-replace rotaries will have them again.
* Rotaries are individually linked to devices
=> Service Delegate Rotary

locale/de/LC_MESSAGES/meerk40t.po, locale/es/LC_MESSAGES/meerk40t.po, locale/fr/LC_MESSAGES/meerk40t.po, locale/hu/LC_MESSAGES/meerk40t.po, locale/it/LC_MESSAGES/meerk40t.po, locale/ja/LC_MESSAGES/meerk40t.po, locale/messages.po, locale/nl/LC_MESSAGES/meerk40t.po, locale/pt_BR/LC_MESSAGES/meerk40t.po, locale/pt_PT/LC_MESSAGES/meerk40t.po, locale/zh/LC_MESSAGES/meerk40t.po, meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/placements.py, meerk40t/gui/propertypanels/placementproperty.py, meerk40t/gui/wxutils.py
- Add ``placement_grid`` command (and use it in the tree context menu)
- Add ``place current`` to tree context menu
- Fix ``tree current`` operation property panel
=> Placement improvements

meerk40t/core/elements/align.py, meerk40t/core/elements/elements.py, meerk40t/core/node/node.py
=> Fix missing parent bound invalidation on element move/scale

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/gui/materialmanager.py, meerk40t/gui/statusbarwidgets/defaultoperations.py
- Import from Lightburn / ezcad can transform power / speed values if source and target environment have different Laser power and / or lens sizes
- Some internal code revision
=> Additional information in Material Manager

meerk40t/kernel/kernel.py, meerk40t/moshi/builder.py, meerk40t/moshi/controller.py, meerk40t/moshi/driver.py
* Speed limit 127 crash issue.
* Improve holding of driver.
* Clamp int16le values.
=> Update Moshi Driver (Checks and Corrections)

locale/de/LC_MESSAGES/meerk40t.po, meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/placements.py, meerk40t/core/node/place_point.py, meerk40t/gui/laserrender.py, meerk40t/gui/propertypanels/placementproperty.py
=> Proper placement grid

meerk40t/core/elements/element_treeops.py, meerk40t/core/node/place_point.py, meerk40t/gui/propertypanels/placementproperty.py
- A couple of fixes 
- Optional 180° rotation for every other row / column
- Triangular tiling 
- Option to create a tiling template
=> Placement - tiling improvements

meerk40t/extra/hershey.py
The effective calculation time for the rendering of a vector font has been improved:
a) Use of LRU_CACHE to remove the need to reload the fontfile for every character changed / every recalculation
b) Migration from SVGElements path inside FontPath to pure GeomStr
Both together make a visible difference:
Before
After
=> Speed up font rendering

locale/de/LC_MESSAGES/meerk40t.po, meerk40t/core/elements/elements.py, meerk40t/gui/icons.py, meerk40t/gui/scenewidgets/rectselectwidget.py, meerk40t/gui/wxmmain.py
A little tool to copy attributes from one element to another:
=> Format painter

meerk40t/gui/materialmanager.py, meerk40t/gui/wxmtree.py
=> Matman fix

meerk40t/core/svg_io.py, meerk40t/extra/hershey.py, meerk40t/gui/hersheymanager.py, meerk40t/tools/geomstr.py, meerk40t/tools/jhfparser.py, meerk40t/tools/shxparser.py, meerk40t/tools/ttfparser.py
- Allow "welding" of overlapping characters
- Allow kerning adjustments
- A more generic way to reload meerk40t specific attributes from svg files
=> Fontwelding

meerk40t/core/elements/branches.py, meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/tree_commands.py, meerk40t/core/node/groupnode.py, meerk40t/core/node/rootnode.py, meerk40t/core/svg_io.py, meerk40t/device/gui/formatterpanel.py, meerk40t/gui/scenewidgets/elementswidget.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmtree.py
- Recognising inkscape-layers and loading them into regmarks
- Acceleration of file load for designs with a lot of elements inside groups and subgroups
=> Inkscape Layer-Support / Accelerate loading

meerk40t/core/cutplan.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/offset_clpr.py, meerk40t/core/elements/offset_mk.py, meerk40t/core/elements/shapes.py, meerk40t/extra/hershey.py, meerk40t/tools/geomstr.py, test/test_geomstr.py
* Eliminates the main for loop. 
* Finds all sections of contiguous lines
* Required to make simplify respect the .settings value of the info complex value
=> Update Simplify Code

meerk40t/grbl/gui/grblhardwareconfig.py
Validate several values in the GRBL Hardware GUI Window
=> Grbl-Hardware Validate

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/gui/materialmanager.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/gui/statusbarwidgets/defaultoperations.py, meerk40t/gui/wxmtree.py
=> Matman fixes + tweaks

meerk40t/core/elements/elements.py, meerk40t/core/node/util_goto.py, meerk40t/core/planner.py, meerk40t/device/gui/defaultactions.py, meerk40t/gui/propertypanels/gotoproperty.py
Adds vector based goto adjustments. This means the value entered into the Goto will be +- the native corner rather than absolute position within the scene.
=> Util Goto Vector

meerk40t/core/elements/element_treeops.py, meerk40t/extra/hershey.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/hersheymanager.py, meerk40t/gui/toolwidgets/toollinetext.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmscene.py, meerk40t/tools/jhfparser.py, meerk40t/tools/shxparser.py, meerk40t/tools/ttfparser.py
A couple of improvements for vectortext:
- There's no longer the need to copy / import TrueType fonts to the meerk40t directory. mk will read and use the ttf font files from the system directories 
- Multi-line text support including vertical kerning and horizontal line alignment
- Some refactoring behind the scenes
=> Enhanced vector fonts

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/core/node/op_cut.py, meerk40t/core/node/op_dots.py, meerk40t/core/node/op_engrave.py, meerk40t/core/node/op_image.py, meerk40t/core/node/op_raster.py
Resolves the unwanted duplication / additional assignment of elements to operations if a hit was already and found (and the break flag was set for these operations).
=> Classification fixes

meerk40t/tools/geomstr.py, test/test_geomstr.py
=> Add in geomstr `remove_0_length`

meerk40t/core/elements/element_treeops.py, meerk40t/core/node/effect_wobble.py, meerk40t/fill/fills.py, meerk40t/gui/propertypanels/wobbleproperty.py, meerk40t/tools/geomstr.py
=> Add some ornamental wobble pattern

meerk40t/grbl/controller.py, meerk40t/grbl/device.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/grbl/gui/grblcontroller.py, meerk40t/grbl/ws_connection.py, requirements.txt
Many of DIY laser engravers use a simple ESP01 to make them wireless (including mine)
This app seems promising but it couldn't connect to WebSockets, so I added this option.
FYI, this is my first encounter with Python, so I'm happy to learn. Don't hesitate to point out the no-nos I just did.
=> GRBL over WebSocket support implementation

meerk40t/gui/propertypanels/imageproperty.py, meerk40t/gui/wxmmain.py, meerk40t/tools/livinghinges.py
Delayed updates on slider selection (user-configurable), as every dragged pixel will cause a recalculation
=> Hinge tweaks

meerk40t/core/node/place_point.py, meerk40t/gui/propertypanels/placementproperty.py
- Fix placement calculation for non lihuiyu devices
- Allow user selection of start / count in grids (useful for bigger templates, where not all material is needed)
=> Fix placement selection

meerk40t/core/elements/elements.py, meerk40t/gui/wxmmain.py
Minimal autosave functionality.
Still missing:
- Delete autosave file on successful save (you could call it a feature too...)
- Make user aware of an autosaved file at startup
=> Minimal autosave functionality

meerk40t/balormk/device.py, meerk40t/core/view.py, meerk40t/grbl/device.py, meerk40t/lihuiyu/device.py, meerk40t/moshi/device.py, meerk40t/newly/device.py, meerk40t/ruida/device.py, test/test_core_viewports.py
=> Add device margins

meerk40t/gui/laserpanel.py, meerk40t/gui/ribbon.py, meerk40t/gui/wxmmain.py
=> Add arm button to ribbonbar

meerk40t/gui/scenewidgets/attractionwidget.py, meerk40t/gui/toolwidgets/toolparameter.py, meerk40t/gui/wxmmain.py, meerk40t/gui/wxmribbon.py, meerk40t/gui/wxmscene.py
- No distracting snap point display during slider movement
- Recognition of node lock status
=> Tweaks for parametric editing

meerk40t/core/units.py, meerk40t/gui/statusbarwidgets/shapepropwidget.py, meerk40t/gui/wxmmain.py
=> Add position/size changer to statusbar panel

meerk40t/core/node/node.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/laserrender.py, meerk40t/gui/preferences.py, meerk40t/gui/propertypanels/attributes.py
Allow Label display for objects:
Establishing a per object display
=> Label display

meerk40t/gui/wxmmain.py
We will ask the user where to place the content if the shift-key was pressed during the time of the load.
If the ctrl-key was pressed then we will place the content in the center of the scene.
=> Ask the user where to place the content of the file

meerk40t/grbl/controller.py, meerk40t/grbl/driver.py, meerk40t/grbl/gui/grblconfiguration.py, meerk40t/grbl/gui/grblhardwareconfig.py, meerk40t/grbl/gui/gui.py
Some tweaks around grbl message processing
=> Grbl Tweaks

meerk40t/core/node/effect_wobble.py, meerk40t/fill/fills.py, meerk40t/tools/geomstr.py
Wobble Radius == gap length
Wobble Speed == # of gaps
Does require to set the stroke color of the inner shape to None to make the tab-shape appear.
Caveat: this functionality is experimental and subject to change.
=> Add path tabs for cutouts

meerk40t/extra/outerworld.py, meerk40t/internal_plugins.py
Adds
- ``call_url <url>`` ( all platforms )
- ``gpio_set <port> <value>`` (raspberry pi only)
to allow signalling to external devices
=> Add simple interface commands to outer world

meerk40t/device/basedevice.py
Add console command to switch devices
=> Add 'device activate'

meerk40t/gui/materialmanager.py
=> Color display in materialmanager

meerk40t/camera/camera.py, meerk40t/camera/plugin.py
Use ``camera0 start 1024 768`` to force 1024x768 resolution (will be used automatically after that)
GUI to follow
=> Camera - console option and fix to set resolution

meerk40t/fill/patterns.py, meerk40t/tools/geomstr.py, meerk40t/tools/livinghinges.py
Living hinge pattern can now be rotated by 90 degrees
=> Allow 90° rotated living hinges

meerk40t/gui/materialmanager.py
The context menu will contain deletion options if you right click on the branches of the library tree:
=> Extended deletion options in Material Manager

meerk40t/fill/patterns.py, meerk40t/tools/geomstr.py, meerk40t/tools/livinghinges.py
- A couple of fixes to deal with invalid parameters 
- Multiple optimisations to avoid calculating the same geometry again and again
=> LivingHinges fixes & optimisations

meerk40t/gui/preferences.py, meerk40t/kernel/settings.py
Adds right click context menu to clear some settings.
=> Hidden menu in property management panel to clear some settings

meerk40t/gui/consolepanel.py
Will allow to set (and persist) the console font:
* ``console_font`` will open a font selection dialog to set the font
* ``console_font -r`` will reset it to standard values
=> Add console_font to command sets

meerk40t/kernel/kernel.py
Adds ``execute <filename>`` to command arsenal.
Will load a file and execute every single line of it (as long as it does not start with a ``#``, i.e. is commented out)
=> Add file execution

README.md
I find that this is a gread piece of software that has great potential. But, similar to freecad, and many other open source projects, is very user unfriendly, so i want to help clean up the rough edges wherever i can.
I feel that this PR will help a lot more new people get into this software, instead of defaulting to the other proprietary options. Eventually, my plan is to have this software be at least usable in comparison to many of the other closed source solutions, because as of right now, this is the only open source 2D laser engraving control software (that i am aware of).
I hope that this is seen as helpful, i am open to changes if people see fit.
=> Minor improvement to readme

meerk40t/core/elements/elements.py, meerk40t/extra/outerworld.py, meerk40t/gui/wxmmain.py, meerk40t/network/console_server.py, meerk40t/network/kernelserver.py, meerk40t/network/web_server.py
* you need to start the httpd by issuing ``webserver`` (will open a http server at port 2080, if you need another port just specify it by adding the port number to the webconsole command)
* meerk40t will then listening to this port and will look at any http-post data: if this contains a field ``cmd`` then it will execute the field content, as it would have been issued at the console
* if mk receives a regular http-get command, like ``http://127.0.0.1:2080``  then it will answer with a minimal web page where you can enter your command
* additionally a ``webload <url> <x> <y> <width> <height>`` has been added to the commands that will load any supported file from the web and (optionally) set it a given point with specific dimensions on the scene
Security concerns (like a challenge response) …
=> Add webconsole interface

meerk40t/gui/wxmmain.py
=> Remove invalid / no longer existing files from recent menu

meerk40t/gui/gui_mixins.py, meerk40t/gui/plugin.py
Implements feature request #2581
=> Allow filtering / suppressing warning indicator

meerk40t/gui/scenewidgets/rectselectwidget.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/toolwidgets/toolparameter.py, meerk40t/tools/geomstr.py
Refactored the type comparisons to make them consistent, as the recent introduction of cutcode artifacts by tat have led to a amalgam of type structures
=> Geomstr changes

meerk40t/balormk/gui/corscene.py, meerk40t/gui/laserrender.py, meerk40t/gui/scenewidgets/rectselectwidget.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/simulation.py, meerk40t/gui/toolwidgets/toolcircle.py, meerk40t/gui/toolwidgets/toolellipse.py, meerk40t/gui/toolwidgets/toolmeasure.py, meerk40t/gui/toolwidgets/toolparameter.py, meerk40t/gui/toolwidgets/toolrect.py, meerk40t/gui/toolwidgets/tooltabedit.py
Revise inverse scaling logic for scale = 0 in Gc.GetTransform
=> Fix linewidth issues in simulation (and others)

meerk40t/device/basedevice.py, meerk40t/gui/devicepanel.py
* Add 'Duplicate device' in device manager
* add ``device duplicate`` and ``device delete`` to commands
=> Add device duplication

meerk40t/balormk/controller.py, meerk40t/balormk/driver.py, meerk40t/balormk/galvo_commands.py, meerk40t/balormk/usb_connection.py
If you did not have a balor device attached then MeerK40t would crash - thid has been covered
=> Cover balor connection crashes

meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py
MK will now recognize if it crashed during the previous session and will offer you to reload the autosave-file
=> Add recovery opportunity on start

meerk40t/extra/hershey.py, meerk40t/gui/choicepropertypanel.py, meerk40t/gui/hersheymanager.py, meerk40t/gui/propertypanels/propertywindow.py, meerk40t/gui/propertypanels/regbranchproperties.py, meerk40t/gui/propertypanels/textproperty.py, meerk40t/gui/scenewidgets/elementswidget.py, meerk40t/gui/toolwidgets/toollinetext.py, meerk40t/gui/toolwidgets/toollinetext_inline.py, meerk40t/gui/toolwidgets/tooltext.py, meerk40t/gui/wxmeerk40t.py, meerk40t/gui/wxmmain.py
- Change vector text input method - will now immediately open the property window
- Fix (hopefully for the last time) the empty property panel issue
=> Change vector text input method

meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/grid.py, meerk40t/core/elements/render.py, meerk40t/core/elements/shapes.py, meerk40t/core/node/elem_image.py, meerk40t/core/node/op_image.py, meerk40t/core/svg_io.py, meerk40t/gui/gui_mixins.py, meerk40t/gui/laserrender.py, meerk40t/gui/propertypanels/imageproperty.py, meerk40t/gui/propertypanels/rasterwizardpanels.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/wxmscene.py, meerk40t/image/imagetools.py, meerk40t/tools/geomstr.py
Implementation of a proper keyhole functionality
=> Proper keyhole functionality

meerk40t/gui/propertypanels/imageproperty.py, meerk40t/gui/propertypanels/propertywindow.py, meerk40t/gui/propertypanels/rasterwizardpanels.py
=> Dynamical ordering of subpanels for image properties

meerk40t/gui/scenewidgets/selectionwidget.py
Addresses bugreport from elz in discord channel
=> Remove incomplete middlekey treatment in selection widget

meerk40t/core/elements/elements.py, meerk40t/core/node/effect_hatch.py, meerk40t/core/node/effect_warp.py, meerk40t/core/node/effect_wobble.py, meerk40t/core/node/elem_ellipse.py, meerk40t/core/node/elem_line.py, meerk40t/core/node/elem_path.py, meerk40t/core/node/elem_polyline.py, meerk40t/core/node/elem_rect.py, meerk40t/core/node/mixins.py, meerk40t/core/node/node.py, meerk40t/core/node/rootnode.py, meerk40t/gui/scenewidgets/selectionwidget.py, meerk40t/gui/wxmtree.py
=> Introduce 'interim' mode for translated / scaled events to permit effects to delay updates

meerk40t/core/node/elem_image.py, meerk40t/gui/propertypanels/imageproperty.py
Should cover betaeta findings in discord channel
=> Make croppanel more logical

meerk40t/core/elements/element_treeops.py, meerk40t/core/svg_io.py
Would address issue #2598, but has it's drawbacks. See discussion under the issue
=> Have another filenode under regmarks on file load

meerk40t/core/elements/elements.py, meerk40t/gui/gui_mixins.py
Reparent target node if the template and target nodes have different effect ownerships
=> Format paste extend

meerk40t/tools/geomstr.py, test/test_geomstr.py
This PR implements systematic performance optimizations for core Geomstr conversion methods, delivering significant speedup improvements while maintaining 100% backward compatibility and output accuracy.
| Method | Average Speedup | Best Case | Compatibility |
|--------|-----------------|-----------|---------------|
| `as_path()` | 1.08x | 1.16x | ✅ 100% |
| `svg()` | 1.45x | 1.60x | ✅ 100% |
| `as_equal_interpolated_points()` | **1.98x** | **9.70x** | ✅ 100% |
| `as_equal_interpolated_segments()` | **1.98x** | **9.70x** | ✅ 100% |
**Overall Impact**: Up to 9.70x performance improvement for equal-distance interpolation with complete output compatibility.
**Files Modified**: `meerk40t/tools/geomstr.py`
**Key Improvements**:
- Implemented `batch_as_path_optimized()` with vectorized segment …
=> Geomstr optimisations

meerk40t/core/elements/branches.py, meerk40t/core/elements/clipboard.py, meerk40t/core/elements/element_treeops.py, meerk40t/core/elements/elements.py, meerk40t/core/elements/geometry.py, meerk40t/core/elements/grid.py, meerk40t/core/elements/offset_clpr.py, meerk40t/core/elements/offset_mk.py, meerk40t/core/elements/placements.py, meerk40t/core/elements/render.py, meerk40t/core/elements/shapes.py, meerk40t/core/elements/trace.py, meerk40t/core/elements/tree_commands.py, meerk40t/core/elements/undo_redo.py, meerk40t/core/planner.py, meerk40t/core/svg_io.py, meerk40t/extra/cag.py, meerk40t/extra/ezd.py, meerk40t/extra/imageactions.py, meerk40t/extra/lbrn.py, meerk40t/extra/param_functions.py, meerk40t/extra/xcs_reader.py, meerk40t/gui/operation_info.py, meerk40t/gui/propertypanels/operationpropertymain.py, meerk40t/gui/wxmmain.py, meerk40t/image/imagetools.py, meerk40t/tools/kerftest.py
The introduction of the ``threaded`` command requires safety measures to make mk thread safe
=> Introduce node_lock for tree modifying operations
