meerk40t/meerk40t

- LaserProject.py
When "Design->Transform->Rotate tau/4" is clicked with empty project, following exception is being raised:
```
Traceback (most recent call last):
File "meerk40t/MeerK40t.py", line 516, in transform_rotate_right
self.project.menu_rotate(0.25 * tau)
File "meerk40t/LaserProject.py", line 332, in menu_rotate
position = self.selected.center
AttributeError: 'NoneType' object has no attribute 'center'
```
in
https://github.com/meerk40t/meerk40t/blob/57c4c3c957bece764ea27cdab91ed1f0a511a759/LaserProject.py#L327-L339
Is it OK to fix it like that?
> Exception raised when rotating empty design

- Kernel.py
- wxMeerK40t.py
Currently there's no way to "Add" an operation, and if you have paths that don't match up color-wise with operations, they are just binned as raster. This makes it so you can define different paths as different colors, and each color gets its own operation.
I also implemented the "Convert Operation" context menu, for ease of conversion.
Test plan:
open an SVG with an orange line, a blue line, and a red line.
the blue and red lines should get binned into the preexisting operations, and a new orange operation should be created.
right-click the orange auto-created "engrave" operation, use "Convert Operation" to change it to a `Cut`. Double-click on it to see that in the edit window it also appears as a "Cut".
> Auto-create operations for any encountered colors & enable context-menu conversion

- Console.py
- DefaultModules.py
- Kernel.py
- LhystudiosDevice.py
- MeerK40t.py
- OperationPreprocessor.py
- PathProperty.py
- RasterScripts.py
- Settings.py
- svgelements.py
- wxMeerK40t.py
> Initial -H home command.

- Kernel.py
- LhystudiosDevice.py
- Settings.py
- svgelements.py
- wxMeerK40t.py
With regard to #233 the correct initial values are stroke `none`, fill `black`, and color=`black` which only defines the `currentColor` value which would have to be expressed within the file. This is corrected within svgelements.
> 0.6.7 Minor Development

- meerk40t/gui/wxmeerk40t.py
This fixes dragging within operations multiplying on GTK.
> use GetPoint and HitTest to determine the node which is dragged

- DefaultModules.py
- svg-namespace.html
Wiki pages URLs are subject to change by anyone (like me 😄 this evening) and should not be linked to in this way.
We need an immutable URL which contains sufficient HTML to give a brief description and a link to the actual Wiki page.
> Make xml link to meerk40t svg namespace immutable.

- meerk40t/gui/operationproperty.py
Also update the tooltip to hint that "Values of 100 or less are generally used only for dotted lines."
> Add a warning icon to operation power label if power <= 100

- meerk40t/core/elements.py
1. Use distance_sq to avoid unnecessary sqrt
2. Use a larger distance for red = cut classification
3. Classify black = raster for distance up to 48. Keep Engrave for all other colours
4. Only add fill-only element to Raster Operation of same fill colour not to all Raster Operations
5. Add operation for fill-only element if no existing matching raster op
> Various operation classification enhancements

- meerk40t/core/planner.py
Amazingly, one character should do it (for perfect matches).
So for closed paths (which are the primary issue I see with this) where path segments are exactly the same points, this should make these always forwards.
> Prefer forward paths to backward paths in greedy

- meerk40t/core/planner.py
This ensures point burns are done before move burns which would otherwise result in additional travels.
> Make greedy prefer shorter paths all other equal

- meerk40t/gui/wxmeerk40t.py
Fix situation where when you widen the pane bar holding the tree pane, the bar gets wider, but the tree only widens to a fixed point and then stops
> Prevent Tree pane from limiting width

- meerk40t/core/drivers.py
- meerk40t/core/spoolers.py
- meerk40t/device/lhystudios/lhystudiosdevice.py
- meerk40t/device/moshi/moshidevice.py
- meerk40t/gui/lhystudios/lhystudioscontrollergui.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/kernel.py
Keeps the current spooler item in the spooler until it is finished.
Adds in `channel: spooler` to log time between spooled objects.
> Spooler time

- meerk40t/core/elements.py
Adds several operation commands for mass renaming. Also allows a range command.
```
operation* range 0 50 10 power 100
operation* range 1 50 10 power 200
operation* range 2 50 10 power 300
operation* range 3 50 10 power 400
...
operation* range 0 10 1 speed 8
operation* range 10 20 1 speed 10
operation* range 20 30 1 speed 15
...
```
Was used to quickly assign the operations groups for sven's project rather than doing all 50 one at a time.  Specifically it's work for #494
> Operation Commands

- meerk40t/core/elements.py
An element with both stroke and fill of different colours should be both a vector and raster operation.
This change fixes a situation whereby for a specific stroke color, after one object has caused a vector op to be added, following elements with same color stroke and fill do not also get classified to a raster op.
> Fix element with stroke/fill not added to raster

- meerk40t/gui/scene/scenewidgets.py
1. If object is too small to reasonably have both sizing and move icons, then prioritise move.
2. Otherwise increase to size of the border area to up to twice the size but never more than 1/4 of the total.
> Improve mouse sizing icon area in scene

- meerk40t/core/elements.py
Many shapes have paths where last actual segment ends on the exact same point as the initial move, yet these still have a Close segment with the same start and and point.
These close segments should **not** create a null LineCut - these contribute to twitches.
> Avoid null closes which cause twitches.

- meerk40t/core/elements.py
- meerk40t/core/svg_io.py
- meerk40t/device/lhystudios/lhystudiosemulator.py
- meerk40t/device/ruida/ruidadevice.py
- meerk40t/dxf/dxf_io.py
- meerk40t/image/imagetools.py
Backwards compatibility so that Raster Ops not matched exactly to any elements are treated as default.
Note: svg_io classified elements individually (which is suboptimal anyway) but does not work with this approach - consequently changes were needed with how various file loaders dealt with things - they now return either False or None (failed), True (succeeded but no file / elements in tree, or the file_node.
> Raster Ops not matched to exact colors as default

- meerk40t/core/elements.py
- meerk40t/core/svg_io.py
Raster elements will now be classified as follows:
1. By exact colour to a Raster op of the exact same color
2. After all raster elements have been classified by color, then any raster elements not previously classified are classified as follows:
1. If there are one or more existing default Raster ops, they are classified into these.
2. If there are one or more empty non-default Raster ops, they are classified into these.
3. Otherwise a new Default Raster op is created and they are classified into this.
This should be fully backward compatible.
Note: Because of the way this works, it only works for the first file when elements are classified in a single group. Later classifications for e.g. changes of color or a 2nd file, will work the same way, but the empty Raster groups when you loaded …
> Second attempt to improve classification of Raster elements.

- meerk40t/core/elements.py
`get_elem_node` is not currently used anywhere but this is a typo as it is currently same code as `get_elem`.
> Fix typo in get_elem_node.

- meerk40t/core/elements.py
```
MeerK40t crash log. Version: 0.7.0 RC-10s on win32
Traceback (most recent call last):
File "c:\users\lexan\appdata\local\programs\python\python38-32\lib\site-packages\meerk40t\gui\wxmeerk40t.py", line 2578, in on_drop_file
if self.load(pathname):
File "c:\users\lexan\appdata\local\programs\python\python38-32\lib\site-packages\meerk40t\gui\wxmeerk40t.py", line 2539, in load
results = self.context.load(
File "c:\users\lexan\appdata\local\programs\python\python38-32\lib\site-packages\meerk40t\core\elements.py", line 5369, in load
results = loader.load(self.context, self, pathname, **kwargs)
File "c:\users\lexan\appdata\local\programs\python\python38-32\lib\site-packages\meerk40t\dxf\dxf_io.py", line 112, in load
elements_modifier.classify(elements)
File …
```
> Fix add_classify_op if existing special op

- meerk40t/core/elements.py
previous code did context("element delete") when it really should have been context("operation delete") for remove_n_ops.
> Fixed remove_n_ops functionality

- meerk40t/gui/icons.py
- meerk40t/gui/wxmeerk40t.py
Allows operation color to be applied to the icons, replacing black with the color. Grey scale is handled by transparency.
The idea was to use icon color to reflect the colour of the operation / element rather than coloring the text (because it is hard to read white text on a white background).
However, if the operation color is close to the tree background color (assumed to be white in normal mode and black in dark mode) this will not contrast well.  So we replace the transparency with a white or black background and removing the alpha channel.
1. When I tested this, I found that the icons do NOT have the same impact as text color - so we probably need to do something similar with text color i.e. if close to the background color then change the background or use a different means to show …
> Operation icons in color

- meerk40t/core/elements.py
Filled items match exact color vector ops.
Unfilled items match exact color raster ops.
> Reimplement colour matching

- meerk40t/device/lhystudios/lhystudiosdevice.py
- meerk40t/device/moshi/moshidevice.py
- meerk40t/extra/README.md
- meerk40t/extra/winsleep.py
- meerk40t/gui/mwindow.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/main.py
* Implements Windows sleep mode disable and enable.
* Adds windows only plugin `winsleep` which adds hidden commands `winsleep_disable` and `winsleep_enable`
* Corrects `pipe;running` value for lhystudios driver
* Adds window_close_veto to mwindow.
* Adds feature to prevent shutdown of MeerK40t if device is running.
* Corrected Moshiboard `pipe;running` value for those drivers to only enable when sending data rather than all the time.
* While this might be another issue with the shutdown blocking while sending there is no issue with winsleep and multiple drivers running. The routine only turns when anything is marked as running.
> Winsleep Plugin / Correct Shutdown while running.

- meerk40t/core/planner.py
Fix a buggette (potentially burning a segment an extra time). 
Stay on current path rather than travel away, if path is not closed i.e. a small gap <= 1/20".
> Further optimize tweaks

- meerk40t/core/bindalias.py
- meerk40t/core/plotplanner.py
- meerk40t/device/lhystudios/lhystudiosdevice.py
- meerk40t/gui/wxmscene.py
* Tests jog at speed.
* Adds `move_at_speed`
* Fixes keydown overtriggering.
* Fixes alias bug where -left couldn't be aliased because `-left` counts as OPT tokens. Permits quoting correctly
```
alias +down egv IV2232511NBRS1Ez#$z#$z#$
alias +left egv IV2232511NRTS1Ez#$z#$z#$
alias +right egv IV2232511NRBS1Ez#$z#$z#$
alias +up egv IV2232511NBLS1Ez#$z#$z#$
alias "-down" egv I$I$I$
alias "-left" egv I$I$I$
alias "-right" egv I$I$I$
alias "-up" egv I$I$I$
```
> Adds `move_at_speed` command. Prevents Keydown overtrigger. Fix alias -keyword registration.

- meerk40t/core/elements.py
- meerk40t/core/planner.py
This also fixes an issue when classify_reverse is True whereby images are rastered in the wrong sequence.
Note: This does not include raster area optimisation when there is a lot of white space. I still need details of accelerations from Joe to calculate the minimum whitespace so as to know when to group raster elements into the same raster image and when to create separate raster images.
> Fix #667 - include stroke width when making image of raster elements

- meerk40t/core/cutcode.py
- meerk40t/core/elements.py
- meerk40t/core/planner.py
1. Fixes various merge issues, specifically:
a. Merge operations not working when passes >=2 and merge passes not set (because CutCode sequence was inappropriate)
b. Operations being merged when Merge passes set and Merge ops not set because operations of same type were being incorrectly merged. Fixes #656 and reported in #528 and #465.
c. Merge passes reversing direction unncessarily.
2. Improves Greedy optimisation with Merged Passes by reducing the size of the CutCode object being optimised by holding only a single copy of each CutGroup and continuing to burn this object rather than having to find the next copy of the same CutGroup. Implements #655.
> Merge fixes and optimisation improvements

- .github/workflows/unittests.yml
We should be more sparing with resources.
Might be out of minutes for the month.
OSX unit tests do not complete.
Unittests do not have Timeout.
> Limit Resource Usage

- meerk40t/core/elements.py
The issue was using the double-set of quotes. Rather than running
$ xdg-open file.svg
it was trying to run
$ "xdg-open file.svg"
which doesn't work. Instead, do this:
$ xdg-open 'file.svg'
Tested working on 2 different linux distros and mac.
Didn't test on pi, but xdg-open exists there, I see no reason why it wouldn't work.
> Fix for mac and linux open in system

- meerk40t/extra/updater.py
- meerk40t/gui/preferences.py
- meerk40t/main.py
1. New Preference for checking for beta versions
2. Checks for beta if above setting checked or currently (temporarily) on a beta.
To-Do:
3. GUI ability to check for updates and report new version
4. GUI automated periodic (daily) check for new version, weekly reminders of previously reported new version
5. Download new version(s) if executable, and executable directory is writeable and new versions not already downloaded (with correct size).
> Basic check for updates

- meerk40t/kernel.py
- test/test_kernel.py
1. Fix bug from #702
2. Remove single reference to pathlib for consistency and replace with equivalent os.path functions.
3. Add support for unit testing all O/S'
> Fix #702 and switch to os.path

- meerk40t/gui/wxmmain.py
1. Add Zoom to Bed = Zoom to Size with nothing selected.
2. Rename Zoom-to-Size to Zoom-to-Selected
3. Make Zoom-to-Bed be closer fit to scene area (104% rather than 110%)
4. Make Zoom-to-Selected have same fill factor (104%)
> Improve scene zoom menu

- meerk40t/core/elements.py
Open-in-system runs synchronously on Windows i.e. MK hangs until the process completes (I can't speak for other o/s). I am unclear whether this is by design or not.
When run from a pyinstaller exe additionally a CMD window is opened (probably due to this: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess ).
This PR changes the `os.system` call with `os.startfile` when running on Windows which runs it asynchronously - unclear whether we will still get a CMD window under pyinstaller on Windows or not.
> Fix open-in-system when run on windows from exe

- meerk40t/core/cutcode.py
- meerk40t/device/lhystudios/laserspeed.py
- meerk40t/device/lhystudios/lhystudiosdevice.py
- meerk40t/gui/lhystudios/lhystudiosdrivergui.py
- test/test_core_cutcode.py
This is mostly for testing unless there's a better reason to add it than it exists.
The core of this is understanding that G001 mode turns the switch of right moving raster or left moving raster into what is apparently the same as `N<step>SE` so if we're going right (B) we can switch, turn off the laser, and reverse with the command `T` which means turn right. The G001 flagged the scanline step at 1.
With NSE scanline switching we can simply replace the `T` in that case with `NLcSE` assuming we're stepping towards the top (L) and our step size for that step is 3 (c). We are going to be wasting 4 characters each scanline, however this type of scanline can be set dynamically. So we could do interlace rastering. Or raster with a variable step such as a 3,3,4 pattern which would give you a …
> NSE scanline switching / twitchless mode

- meerk40t/core/elements.py
1. Debug channel with summary of major actions / decisions
2. Edge case 1: Non-grey stroke, white fill at back i.e. fill not on top of anything else - now classifies as vector rather than raster
3. Edge case 2: No fill path same colour as overlapping raster elements of same colour
Note: This is a PR against the 0.8.0 services branch as it should probably have a decent beta period.
> Improve classification edge cases

- meerk40t/gui/wxmeerk40t.py
Crash due to e.g. infinite loop creates a wide dialog box and lacks a vertical scroll bar.
Switch back to `MessageDialog` from `GenericMessageDialog` resolves this.
> Fix crash dialog width.

- meerk40t/kernel.py
1. Fix buffer length bug (always 10 less than stated buffer_size)
2. Use `deque` instead of `list` for buffer because it is quicker (and this is exactly what it was designed for)
3. Avoid double application of indent or timestamp on `channel open`
> Various minor tweaks to channels

- meerk40t/core/elements.py
- meerk40t/kernel.py
1. Improves the Add Ops / Special Ops context menus: Can now add special ops after specific LaserOperations as well as append them to the end. Also add Home/Beep/Interrupt in one go as a commonly used operation to give access to the material part way through.
2. Now saves and reloads Special Operations when you Save/Use operations and when you close and restart MK.
However, during testing I found a couple of oddities:
a. Attribute "type" is not always saved when you persist operations - no idea why. I have coded around this - and it may be necessary to avoid point b. when user upgrades to a version with this PR.
b. If persistent settings are invalid, then MK can crash before starting - this really needs to be more robust esp. on load. I will try to add this before it gets merged if I can …
> Improve special ops handling

- meerk40t/gui/panes/camerapanel.py
When a closing pane closes the camera stream any open stream will restart it.
Allows fast fps in camera panes, set to whatever the window sets it as.
Fixes #734
> Camera: Sync Pane and Window - FPS, Open Stream

- meerk40t/core/svg_io.py
Vertical_raster is saved in the test file but setting vertical_raster is not possible because it's a @property. To rectify we go ahead and except the attribute error for the setattr. there.
Fixes #724
> Fix issue #724

- meerk40t/core/planner.py
- meerk40t/kernel.py
1. Set timestamp on optimize channel since timing is key
2. Apply timestamp if specified and channel already exists
3. Avoid double printing if channel is printing and copied to console and console is also printing
> Optimize channel improvements

- pyproject.toml
@tatarize reported the following on [Discord](https://discord.com/channels/910979180970278922/932716887404601364/933944551188602940):
>  Trying to apply black I get a config error for main. 
`Error: Could not open file 'C:\\Users\\Tat\\PycharmProjects\\meerk40t\\pyproject.toml': Error reading configuration file: Invalid value (at line 13, column 11)`
`exclude = svgelements\.py`
> Must require being a proper string there.
> also, line 17 requires black to be quoted.
> Attempt to fix pyproject.toml

- meerk40t/core/cutcode.py
- meerk40t/core/elements.py
- meerk40t/core/planner.py
- meerk40t/gui/executejob.py
1. Burn Complete Subpaths - with this option, closed subpaths can be entered anywhere, but non-closed subpaths will always be burned from one of the ends.
2. Group Inner Burns - when the first inner element has been burned, the rest of the matching inner burns will be burned next, followed by the outer path before moving on to other elements. For a design with multiple parts, this will normally burn each part in turn rather than e.g. doing inner burns for one part then outer burns for another then returning for outer burns for the first. This reduces the risk of a shift ruining all parts by completing one part before moving onto another.
Additionally, minor fixes for:
a. Repeat step and multiple passes without Travel optimisation; 
b. Default values changed for Travel Optimisation and Cut …
> Additional optimisation options

- meerk40t/kernel.py
Forces \n if one doesn't exist within console `__call__` methods.
> Force append \n for normal context calls

- meerk40t/core/drivers.py
- meerk40t/core/elements.py
- meerk40t/core/planner.py
- meerk40t/device/lasercommandconstants.py
- meerk40t/gui/consoleproperty.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/gui/wxmmain.py
Fixes #764 
Here's my first stab at it! I left in the original interrupt menu item so I could compare behavior, I'm happy to take them out once this is in good shape.
https://user-images.githubusercontent.com/112170/150663972-47504b97-5f61-4295-9001-da3a20b6c793.mp4
> Add "ConsoleOperation" to allow interrupts to have notes and custom labels

- meerk40t/core/cutcode.py
- meerk40t/core/elements.py
- meerk40t/core/planner.py
This PR does three things:
a. Fixes VectorMontonixer having too few polygon points to ensure that small inner burns are not mistakenly considered outside.
b. Fixes Rasters not being considered for inner burns, and treats rasters correctly as being inside even if it extends outside;
c. Improves performance by maintaining burns_done at a group level rather than iterating over segments to find out.
> Fix Group Inner Burns

- meerk40t/core/elements.py
Proposed rules
1. Disallow drop of anything other than an Image onto Image Ops.
2. Disallow drop of images onto a Dot Op.
Do this for drops onto "op" or "opnode" nodes.
Test what happens if drop of single node fails, and where multiple nodes partly success and partly fail.
> Disallow Drag / Drop of some invalid image combinations

- meerk40t/core/elements.py
`tree selected` was actually using emphasised rather than selected. So e.g. deleting an image under an image operation also deleted the image under elements.
> Make delete key usage consistent

- meerk40t/kernel.py
In rare cases while this buffer is changing you can watch the function.
```
self.context.channel("%s/usb" % active, buffer_size=500).watch(self.update_text)
File "C:\Users\Tat\PycharmProjects\meerk40t\meerk40t\kernel.py", line 2766, in watch
for line in self.buffer:
RuntimeError: deque mutated during iteration
```
> Correct RuntimeError, dequeue mutated

- meerk40t/gui/panes/navigationpanels.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
1. Add accelerators for Zoom selected/bed menu items
2. Align initial zoon to zoom-to-scene values
3. Default move to corners when nothing selected
4. Additional navigation tooltips
> Various minor UI improvements

- meerk40t/core/elements.py
Offset X and Y were always put to zero - fixes [#829](https://github.com/meerk40t/meerk40t/issues/829)
> Fix outline statement

- .github/workflows/centos.yml
- .github/workflows/linux/meerk40t.spec
- .github/workflows/ubuntu.yml
- .github/workflows/win.yml
Issue with locale paths in linux meerk40t.spec file highlighted issue with needing separate build yml for the different platforms.
This fixes the original issue, and also does the split.
CentOS build will need to be rerun for 0.7.5000
> Fix CentOS build, split ci.yml into separate build platforms.

- meerk40t/gui/scene/scene.py
- meerk40t/gui/scene/scenewidgets.py
a) Optics: Draw two indicators in the selection rectangle to make it clearer to see even if mouse select left up (was covered by the mouse pointer before), change symbol from ! to ^
b) Keypress-behaviour, anticipates Sophist-UKs PR for keybinds, Ctrl+ should be more consistent with other keys on MacOS
> Selection-Rectangle: optics + make Ctrl-Key more MacOS-aware

- locale/de/LC_MESSAGES/meerk40t.po
- meerk40t/core/elements.py
- meerk40t/kernel.py
In preparation for some graphical tools I've extended 
by a new parameter origin, that describes where the orginal element(s) shall be located in respect to the grid . The parameter needs to be provided in the format:
````
grid ... --origin ox,oy    or       grid ... -o ox,oy
````
so e.g. 
````
grid  3 3 -o "2,2"
````
will create a 3x3 grid with the original elements right in the middle.
that takes some parameters to create (potentially rotated) copies on a circular arc around the orginal element(s)
```
circ_copy <copies> <radius> [ <startangle> <endangle> <rotate> <deltaangle> ]
```
The optional parameters can be provided like:
--rotate --startangle 0deg etc.
Notabene: normally you will equally distribute the amount of copies between startangle and endangle. If you omit the endangle and …
> Extend grid and add circ_copy, radial and shape

- meerk40t/core/cutplan.py
- meerk40t/gui/executejob.py
I haven't added a GUI because I am hopeful that this will be robust and just work correctly - but just in case, here is a setting that you can use (via console) to turn it off and go back to a single raster image per Raster op.
> Add raster optimisation on/off switch (no gui)

- meerk40t/kernel.py
When using abbreviated options i.e. 'rotate 30deg -a' they get recognized but cause an additional errromessage to be displayed (in this instance "a is not a registered command...").
This change should fix it
> Fix errormessage when using abbreviated options 

- meerk40t/core/bindalias.py
The former rect / circle defaults have become rather useless due to the change of internal units. This is reestablishing the former behaviour.
> Alter keybind defaults for rect / circle

- meerk40t/core/elements.py
- meerk40t/core/exceptions.py
- meerk40t/core/svg_io.py
- meerk40t/dxf/dxf_io.py
- meerk40t/extra/inkscape.py
- meerk40t/gui/wxmmain.py
- meerk40t/kernel/exceptions.py
- meerk40t/kernel/kernel.py
- meerk40t/ruida/device.py
1. Separate out Console and Python Syntax Errors.
2. Provide a msg property for backwards compatibility for any non-MK plugins that still use a msg property.
3. Replace CommandSyntaxError in ruida device with a ruida specific exception because this is not a Console Command Syntax error.
4. Switch CommandSyntaxError handling to use `str(e)` rather than e.msg.
Unit tests pass, so this is not repeating the problems with #892.
> 2nd attempt at getting CommandSyntaxError correct

- meerk40t/core/elements.py
If you  right-click on a selected element in the scene, then there's no option to remove the element. This has been changed.
> Make sure delete operation appears in menu

- meerk40t/core/bindalias.py
Keybind gets a "ctrl+letter" delivered while the majority of the predefined binds expect a "control+letter". This code translates these two into each other (well only ctrl to control, not vice versa).
Can be disregarded if theres consensus about the new terminology - I found it very annoying myself ...
> Bypass ctrl, control confusion

- meerk40t/core/svg_io.py
> Switch from cElementTree to ElementTree

- meerk40t/core/cutcode.py
- meerk40t/core/plotplanner.py
- meerk40t/device/lhystudios/lhystudiosdevice.py
- test/test_core_plotplanner.py
The idea is to fix the clickity clack on ruidacontrol rasters. We do this by refusing direct moves along certain axis, but only as smooth moves at an angle when we travel along the other axis.
> Smooth raster intergrations for ruidacontrol+

- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/gridwidget.py
- meerk40t/gui/scenewidgets/guidewidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
- meerk40t/gui/simulation.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
Some fixes / improvements about the drawing of the grid and the rulers on the sides of the scene:
- The grid was always showing a 10x10 mm grid and was not linked to the rulers . They are now synchronised.
- The rulers tickmarks were somewhat arbitrary they are now showing more 'usual segmentation'
- If you are zooming in/out of the scene then the scale of the rulers / grid follow that zoom factor and try to provide a meaningful segmentation
- This autoscale feature can be turned off by rightclicking on the ruler area on the top / left:
There is a new functionality now to quickly align elements: magnet-lines. You are creating them by double-clicking on the ruler-area (and if you click on that area again then the line will be removed).
Whenever you move an element (group of elements), if …
> Add magnet functionality to grid and make grid more flexible

- meerk40t/device/ruida/ruidadevice.py
- meerk40t/gui/wxmmain.py
Ruida devices flag certain bits for the state of the device. In Ruidacontrol mode we should emulate this so that the laser can be paused and stopped.
> Ruidacontrol States, pause/stop 

- meerk40t/gui/navigationpanels.py
- meerk40t/gui/scenewidgets/laserpathwidget.py
If you right click on one of the alignment buttons then the laser will move to the indicated position of the selected elements (regular click behaviour so far), but from then on the selection will remain at its relative position to the laser head, so if you move the laser then the selection will follow the movement. This behaviour ends when you either right click the same button again (laser head remains at its current position) or do a normal click of an alignment button (laser head will move).
The current lock state will be indicated by highlighting the button (visually not extremely appealing but a clear indicator).
NB there might be some limits to this when it comes to manual physical movement of the laserhead.
Additionally the laserpath has become less obtrusive and therefore easier …
> Lock selection to laser movement

- meerk40t/gui/scene/guicolors.py
- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/attractionwidget.py
- meerk40t/gui/scenewidgets/gridwidget.py
- meerk40t/gui/scenewidgets/guidewidget.py
- meerk40t/gui/scenewidgets/laserpathwidget.py
- meerk40t/gui/scenewidgets/rectselectwidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmribbon.py
- meerk40t/gui/wxmscene.py
Nearly all colors used in the scene by different gui elements are now configurable:
Syntax: you can specifiy the colour for an element by providing a color_code for it (hex representation in the format: 0xRRGGBBAA with RR the 2-digit hexvalue for the red component, GG for the green component, BB for the blue component and AA for the transparency (00 invisible to FF fully opaque))
```
set color_xxxx 0xRRGGBBAA
```
The following elements can be user-colored:
- color_manipulation - The manipulation rectangle plus modification elements
- color_laserpath - The laserpath
- color_grid - Grid-Lines
- color_guide - The guide on top / to the left of the scene
- color_background - The background beyond the bed
- color_magnetline - Magnetlines
- color_snap_visible - Color for visible snap-indicators …
> Make Scene colors configurable

- meerk40t/gui/scene/scenewidgets.py
- meerk40t/gui/wxmscene.py
* adds in command `scene color` which lets you list the colors that can be changed or do `scene color unset`.
* Does not create pens or colors during the drawing cycle.
* Implements a theme signal to update the scene information of different colors.
> Tweaks to 0.7.x Color Selection Tweaks

- meerk40t/gui/scene/scenewidgets.py
- meerk40t/gui/wxmscene.py
Subset of [PR#977](https://github.com/meerk40t/meerk40t/pull/977) - limited to manipulation and grid color:
Syntax: you can specifiy the colour for an element by providing a color_code for it (hex representation in the format: 0xRRGGBBAA with RR the 2-digit hexvalue for the red component, GG for the green component, BB for the blue component and AA for the transparency (00 invisible to FF fully opaque))
```
set color_xxxx 0xRRGGBBAA
```
The following elements can be user-colored:
- color_manipulation - The manipulation rectangle plus modification elements
- color_grid - Grid-Lines
> User defined color (0.7)

- meerk40t/gui/scenewidgets/rectselectwidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
If you click ctrl+shift while resizing then the resizing operations will affect opposing sides / corners simultaneously allowing a resize operation with the center remaining unchanged:
> Allow simultaneous sizing of opposing sides/corners

- meerk40t/gui/scene/guicolors.py
- meerk40t/gui/scenewidgets/attractionwidget.py
- meerk40t/gui/scenewidgets/gridwidget.py
- meerk40t/gui/scenewidgets/guidewidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
- meerk40t/gui/wxmscene.py
(Applied the same logic as in PR979 for the legacy branch)
NB: breaking change for the internal storage of the colors, so please use 'scene color unset' if you have already used a previous version.
Nearly all colors used in the scene by different gui elements are now configurable:
Syntax: you can specifiy the colour for an element by providing a color_code for it: 
- either as a hex representation in the format: #RRGGBBAA with RR the 2-digit hexvalue for the red component, GG for the green component, BB for the blue component and AA for the transparency (00 invisible to FF fully opaque))
- or as 'regular' colorcode: yellow, green, red, blue...
```
scene color <aspect> #RRGGBBAA
```
The following elements can be user-colored (aspect):
- manipulation - The manipulation rectangle 
- …
> Color-Scheme changes

- meerk40t/gui/icons.py
- meerk40t/gui/lasertoolpanel.py
- meerk40t/gui/scenewidgets/selectionwidget.py
Add an additional option to lasertools:
just mark opposing corners and meerk40 will create the frame between the two (not awfully difficult I know). Together with the reference - feature you can then align / move any selection to this frame. If necessary the selection will be autorotated to fit better:
That should effectively cover https://github.com/meerk40t/meerk40t/issues/876
> Extend Lasertools

- meerk40t/gui/position.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
- Two fixes (File Import + Position Panel) plus
Addition of a quick color selector for stroke and fill (including reclassification) and an option to change the stroke-width:
Left click on the color will change the stroke-color of all selected elements, right click the fill-color.
You may change the stroke-width for the selected elements as well:
You may turn this feature off in preferences:
> Quick color / stroke selector

- meerk40t/gui/propertypanels/pathproperty.py
- meerk40t/gui/wxmeerk40t.py
This is not yet fully working, as it crashes with a node.label = None error in wxmtree.py 
```
File "/home/jens/daten/meerk40t-itemmanipulation/meerk40t/core/node/node.py", line 449, in altered
self.notify_altered(self)
File "/home/jens/daten/meerk40t-itemmanipulation/meerk40t/core/node/node.py", line 373, in notify_altered
self._root.notify_altered(node=node, **kwargs)
File "/home/jens/daten/meerk40t-itemmanipulation/meerk40t/core/node/rootnode.py", line 173, in notify_altered
listen.altered(node, **kwargs)
File "/home/jens/daten/meerk40t-itemmanipulation/meerk40t/gui/wxmtree.py", line 347, in altered
node.label = None
AttributeError: can't set attribute
```
> Amend propertypanel

- meerk40t/gui/wxmmain.py
Elements for stroke-width were truncated in Linux
> Ensure minimum statusbar height

- meerk40t/core/elements.py
- meerk40t/gui/wxmtree.py
A couple of behavioural inconsistencies removed:
a) Context-menus for element-nodes do no longer show non-working actions if a node is a regmark
b) Adding menu-items to easily move nodes into/out regmark
c) Refresh the tree after node-modifying operations (i.e. dnd, delete and others)
> Rebuild tree after dnd operations

- meerk40t/gui/wxmscene.py
- meerk40t/gui/wxmtree.py
Should fix the missing cursor movement in the tree as well as the selection of all elements belonging to an operation
> Some fixes for treepanel

- meerk40t/gui/wxmmain.py
As the propertypanel needs to listen to the selected flag of a node we need to sync the scene-selection (i.e. emphasized) to the tree selection (i.e. selected). This hack does ensure that the selected status is as well set if the emphasized status is set.
It does not do the inverse, de-"selecting" when de-"emphasizing"
> Sync selected to emphasized

- meerk40t/core/elements.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/svg_io.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/propertypanels/textproperty.py
a) stroke and fill colors were not always properly saved - fixed
b) save and load text-font-attributes properly 
c) Fixed copying of a text element
d) Fixed invalid node.fill check for images in elements.classify leading to a duplicate loading of the file
A technical comment: the italic state font_style is attached to the node and not to the text element (that would have required a change to svgelements as far as I could see) - I may have overlooked something essential here, so if there's a better i.e. consistent way then please let me know.
> SVG-io Fixes / extensions: colors, font attributes

- meerk40t/core/elements.py
- meerk40t/core/node/op_hatch.py
- meerk40t/gui/propertypanels/operationpropertymain.py
* Adds in penbox commands. This is chiefly to set `penbox value` commands and should be used to test `rainbow rastering` where each value of a raster image results in a different set of settings. This would permit an image to have 255 different settings one for each level of grey in an image.
* This should add in enough cursory setting commands to set the penboxes and to let you set settings, perhaps loading and saving, and connect the penbox value to the lookup table if a value penbox is set on a particular operation. In theory, we could a series of penboxes for hatches and hatch them repeatedly, with each iteration using the next set of values. A pass-penbox rather than pixel value one.
This might also be useful for setting values if these can be defined for particular colors etc.
> Penbox: Settings Resources

- meerk40t/gui/scenewidgets/selectionwidget.py
Was still using node.bbox() ...
> Fix for refobject align

- meerk40t/core/fonts.py
- meerk40t/core/node/elem_text.py
- meerk40t/gui/laserrender.py
- Assigning font-properties could have reset the font-size. The order has been changed, so stuff should look better now...
E.g. the famous wiki-svg-file (https://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg) looks now:
- The text bboxes take now the font-attribute descent into consideration:
before:
now:
> Fix sizing of fonts

- meerk40t/core/elements.py
- meerk40t/gui/toolwidgets/tooltext.py
- meerk40t/kernel/settings.py
- Survive a corrupted configuration file (happened during a computer crash)
- Fix one wordlist issue (there are more...)
- Extended the Text-Tool (a simple textentry so far):
> Extended Text-Entry + some fixes

- meerk40t/core/elements.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/node.py
- meerk40t/core/svg_io.py
- meerk40t/gui/laserrender.py
Addresses issue https://github.com/meerk40t/meerk40t/issues/1019
Recognises SVG stroke-linecap and stroke-linejoin attributes 
Adds linecap and linejoin commands:
```
[21:39:50] help linecap
[21:39:50]     	linecap <cap:str>
[21:39:50]     	(elements) -> linecap -> (elements)
[21:39:50]     	Argument: str 'cap':
[21:39:50]     		Linecap to apply to the path (one of butt, round, square)
[21:39:50]     	Option: str ('--filter', '-f'):
[21:39:50]     		Filter indexes
[21:39:57] help linejoin
[21:39:57]     	linejoin <join:str>
[21:39:57]     	(None) -> linejoin -> (elements)
[21:39:57]     	Argument: str 'join':
[21:39:57]     		jointype to apply to the path (one of arcs, bevel, miter, miter-clip, round)
[21:39:57]     	Option: str ('--filter', '-f'):
[21:39:57]     		Filter indexes …
```
> Add linecap and linejoin for lines/paths

- .github/workflows/win.yml
pyinstaller 4.10 updated to commit e319ae3d00 which implemented
a normalize icon function, but fixes for bug introduced there
(assuming $PWD instead of $SPECPATH) were added to 5.0 branch not v4.
Locking to v4.9 for now.
> Lock pyinstaller to v4.9 to fix issue with Icon not found in v4.10

- meerk40t/core/elements.py
- meerk40t/gui/scenewidgets/elementswidget.py
Allow two fundamentally different single-click selections:
- left-click - choose the smallest element under the mouse-cursor
- ctrl+left-click - choose the largest element under the mouse-cursor
This default behaviour can be toggled under preferences
> Change single click selection

- .github/workflows/win/file_version.txt
- meerk40t/balormk/BalorDriver.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_hatch.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
- meerk40t/core/parameters.py
- meerk40t/fill/fills.py
- meerk40t/grbl/device.py
- meerk40t/gui/plugin.py
- meerk40t/gui/propertypanels/operationpropertymain.py
- meerk40t/main.py
- setup.cfg
- test/bootstrap.py
- test/test_elements_penbox.py
- test/test_fill.py
Hatches use fill types and this code is needed in multiple places. For example:
* Hatch Operation
* Preview of Hatch Operation
* Potentially Hatch Elements with real time viewing
There is currently not an easy way to define these or allow plugins to extend these. This PR seeks to implement hatch fill types dynamically.
> Create a standard API for fill types

- .github/workflows/win.yml
Ports the pyinstaller lock at v4.9 to main branch.
Removes wx4.0.7-post2 executable building.
> Fixes for main branch Windows autobuild

- meerk40t/gui/scenewidgets/selectionwidget.py
Double-clicking and right-clicking an element did not acknowledge new selection behaviour
> Fix behaviour for selection

- meerk40t/core/elements.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
- meerk40t/gui/wxmtree.py
While trying to figure out while it always took two clicks on the colorbar to get a classification i did a couple of things
a) I tried to document the classify method a bit for my own benefit and (re)instated the pure red = cut op
b) I added an optional parameter to stroke and fill to allow for immediate classification of the object (imho that should be the default anyway but I left the current behaviour unchanged) 'stroke red --classify' or 'fill blue --classify'
c) I fixed the behaviour of "declassify" to swallow the emphasized flags
d) I fixed the behaviour of rebuild_tree to swallow the emphasized flags  
Before:
Now:
> Consistent classification, some bugfixes

- meerk40t/core/elements.py
Should fix the unwanted behaviour that if you delete an operation the contained elements are deleted as well
> Deleting op will no longer delete contained elems

- meerk40t/core/elements.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
a) Amend display of affected nodes for node-deletion: If there are ops selected then they take precedence and will only be counted
b) The recent changes removed the default stroke / fill behaviour, this has been reestablished
> Improved Tree-menu-Display / Fix for default

- meerk40t/camera/gui/camerapanel.py
Try to look for cameras to assign them as default for camera0 to camera4. Needs testing on Darwin.
> Identifying cameras

- meerk40t/gui/wxmmain.py
Ctrl-U or "pane toggleui" will hide all panes except scene / restores the previous config.
> Toggle UI-Elements

- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toolrect.py
Fix the ghost circles, ellipses, rectangles that appear if you try to rapidly try to draw something (internally considered to be a leftclick and not a sequence of leftdown leftup).
> Compare too rapid draw attempts

- meerk40t/core/svg_io.py
- meerk40t/gui/fonts.py
- meerk40t/gui/laserrender.py
- Improved fontface selection
- Load and save text-anchor and text x and y attributes, better recognition of "class" provided font-attributes
- Some tweaks around bound-box calculation for a text
There's a fundamental flaw in wxPython to get the right fontsize.
Both GetTextExtent as well as GetFullTextextent provide the fontmetric-size as result for the font-height and dont take the real glyphs into account. That means that ".", "a", "g" and "T" all have the same height...
Consequently the size is always off... This can be somewhat compensated by taking the descent from the font-metric into account.
A 'real' height routine would most probably need to draw the string on an empty canvas and find the first and last dots on a line. I was wondering whether the imagetools provide such a …
> Some font tweaks

- meerk40t/gui/scenewidgets/rectselectwidget.py
The previous PR was effectively consuming the leftclick event and not chain it to the elementswidget, preventing single click selections.
> Fix the fix

- meerk40t/core/elements.py
- meerk40t/gui/wxmtree.py
- meerk40t/gui/wxutils.py
a) Try to make the tree context-menu somewhat more comprehensible - especially around the deletion from ops / from scene stuff
b) Recreate the state of expanded tree-branches after tree manupulation actions that  require a tree_rebuild
> Tree stuff

- meerk40t/gui/laserrender.py
- meerk40t/gui/wxmtree.py
Preserve the aspect ratio (before all rects/ellipses looked identical)
> Make tree element icons closer to reality

- meerk40t/core/elements.py
- meerk40t/core/node/filenode.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/propertypanels/groupproperties.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmtree.py
Fixed:
a) Context menu "Remove all items from operations" recognises multiple ops selected
b) "Move to regmarks" touches all selected elements
c) "Move back to elements" touches all selected elements
d) MakeRaster translates variable text
e) Fix align behaviour, if you select elements in a group jointly with some outside (or just some inside a group for that matter)
f) Adjust zoom when resizing main window (configurable in prefrerences)
g) Only display short filename for file nodes
h) Fix non-appearing textnodes in raster
Outstanding:
- ~~Text nodes icons not initially populated when loading a file~~
- ~~Text still not appearing fully in preview...~~
> Multiple fixes

- meerk40t/balormk/device.py
- meerk40t/balormk/driver.py
- meerk40t/core/drivers.py
- meerk40t/core/elements.py
- meerk40t/core/node/branch_ops.py
- meerk40t/core/planner.py
- meerk40t/core/spoolers.py
- meerk40t/device/ch341/README.md
- meerk40t/device/ch341/ch341.py
- meerk40t/device/ch341/ch341libusbdriver.py
- meerk40t/device/dummydevice.py
- meerk40t/grbl/README.md
- meerk40t/grbl/device.py
- meerk40t/gui/propertypanels/opbranchproperties.py
- meerk40t/gui/spoolerpanel.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/lihuiyu/README.md
- meerk40t/lihuiyu/device.py
- meerk40t/lihuiyu/gui/gui.py
- meerk40t/lihuiyu/gui/lhyaccelgui.py
- meerk40t/lihuiyu/gui/lhycontrollergui.py
- meerk40t/lihuiyu/gui/lhydrivergui.py
- meerk40t/moshi/device.py
- meerk40t/moshi/gui/moshicontrollergui.py
- meerk40t/ruida/device.py
"""
Laser jobs are a generic outline for the types of jobs which can be sent to a spooler.
* Laser jobs need to provide a run-count and expected run-count this how many times it should be executed.
* Laser jobs must be able to be cancelled. Jobs running an infinite number of times must be able to be interrupted.
* Lowest priority jobs should be interrupted. They should be stopped, aborted at the earliest possibility.
* Realtime jobs should run even if the current device is paused. This is to permit resuming a backend device.
* Some, but not all, jobs should permit the serialization of the job. To permit saving the job to disk or moving it over a network.
* Dynamic laser jobs like Live-Outline mode for galvo should be a type of job, this doesn't permit saving or canceling.
* Jobs should …
> Upgrade Spooler

- meerk40t/gui/fonts.py
- meerk40t/gui/propertypanels/textproperty.py
- meerk40t/svgelements.py
* Fix redos, got rid of the entire section there.
* Uses built in `.font_list` routine instead of rolling up it's own.
* Accounts for three or more potential fonts in the font-family.
> Eliminated reDoS progress through font-list

- meerk40t/core/elements.py
- meerk40t/gui/choicepropertypanel.py
- meerk40t/gui/opassignment.py
- meerk40t/gui/plugin.py
- meerk40t/gui/preferences.py
- meerk40t/gui/scenewidgets/elementswidget.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmtree.py
- meerk40t/kernel/kernel.py
a) Fix missing icon for op dots in tree
b) Reorganise Preferences (and add snap-options to it, which were only accessible via Pane)
c) Allow quick tool reset: just press right-click on scene
d) Make opassign panel less annoying by remaining visible and become aware of additions / removal of operations
> Prefs reorg / simpler end of tool

- meerk40t/gui/wxmmain.py
a) Append operation assignments to status-bar
b) Make panel sizes more fit for purpose
Open: need to show the status-text for panel 2 + 3 differently (as two will always be concealed by the ops buttons)
> More panel actions

- meerk40t/core/elements.py
I've encountered some strange effects with the area routine, where the path is first split into its subpaths and then interpolated.
```
for subpath in path.as_subpaths():
subj = Path(subpath).npoint(linspace(0, 1, interpolation))
subj.reshape((2, interpolation))
s = list(map(Point, subj))
subject_polygons.append(s)
```
If you use this routine with interpolation = 100 on the following file, all works well, if on the other hand you use interpolation = 1000 then completely absurd values are generated.
Testfile:
open console and type
```
area
````
> Avoid overflow runtime errors for area-calculation

- meerk40t/gui/about.py
- meerk40t/gui/wxmtree.py
a) Show 'real' configpath in about
b) Allow drag and drop of node of simlar types (right now you can only drag two or more rectangles but not a rectangle and a circle, ie allowed only identical node types)
> Two minor fixes

- meerk40t/core/elements.py
- meerk40t/gui/alignment.py
- meerk40t/gui/wxmmain.py
The `align` command context allowed mode sets to happen with `alignmode` and a specified `modus`. You could also call the actual alignment code with either a `0` or `1`. These are not typical for how the command structure is intended to work, rather we should define the command `align` as a command context and perform in-line actions. 
The principle things are that this permits chaining of mode sets. Since we're not reusing the modes `default`, `first`, `last`, `ref`, `bed` with our actual alignment commands `left`, `right`, `top`, `bottom`, `xy`. We can string these commands. Also we get rid of the need for the group flag by allowing `group` and `individual` commands to be part of `align`.
I preserved all the code and functionality and that included the push and pop features as well as …
> Advance alignments with more regular command functions.

- meerk40t/core/elements.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_image.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_numpath.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_point.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/filenode.py
- meerk40t/core/node/groupnode.py
- meerk40t/core/node/node.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_hatch.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/wxmtree.py
- meerk40t/lihuiyu/device.py
* Set bounds to pure geometric bounds.
* Add paint_bounds() for the paint bounds.
I guess switch everything to using no-stroke width for the nodes but also include a paint_bounds() which gives the area the node paints in. I'm thinking that could also be useful if we want to cache the display buffer or whatever.
> Add paint bounds rather than pure geometric bounds for nodes

- meerk40t/core/svg_io.py
- meerk40t/svgelements.py
Svgelements version 1.8 uses a different and more correct method of parsing the Use flags. This required as tweak to svgio.py to process them correctly.
> Upgrade svgelements to version 1.8 (Corrects some uses of `Use`).

- meerk40t/core/node/elem_image.py
The DPI change triggered a bug by actually matching the values required to trigger the use of passthrough and avoid modifications of the image. This gave it a wrong matrix which moved it wronlgly. This set of code changes fixes that error and divides up the `ImageNode` process_image into different functions that serves to assist readability greatly.
> Correct Image Matrix Bug, Improve Readability

- meerk40t/grbl/device.py
- meerk40t/gui/wxmmain.py
Corrects a few issues in GRBL with regards to realtime commands. This also corrects multiple devices having different running states and the main quit message needing all of them to to be False. We correct the device purging within grbl when you call abort and ensure that realtime pause and resume are sent outside the regular channel.
> Grbl Realtime

- meerk40t/main.py
The plugin system for 0.8.x was removed due to various conflicts with older code. Reflecting this the entry point was changed to `meerk40t.extensions` and the code was otherwise corrected.
> Restore Dynamic Extensions

- meerk40t/core/elements.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/svg_io.py
- meerk40t/dxf/dxf_io.py
- meerk40t/gui/materialtest.py
- meerk40t/gui/scenewidgets/elementswidget.py
- meerk40t/gui/toolwidgets/toolcircle.py
The core idea behind this is to fix the vector text object jump on recreation. The nodes can store offset in either the actual points or matrix. This PR intends to preserve the difference. The actual parameters used here are given overtly, and the matrix it creates is preserved. So that if we create a vector text object the movement/rotation matrix gets preserved independently. So rebuilding the object with the same properties maintains the position.
Typically loading and saving causes a few lossy issues. First, the ellipse, rect, line, and polyline objects get reified, and lose their matrix. This means resetting them restores them to their initial load position. These objects also get saved as `<path>` type objects rather than their valid native forms.
The lack of native form loading …
> Less Lossy Save

- meerk40t/balormk/driver.py
- meerk40t/grbl/device.py
- meerk40t/gui/statusbarwidgets/infowidget.py
- meerk40t/lihuiyu/device.py
- meerk40t/moshi/device.py
* The PlotPlanners were not useful since they had to compute everything ahead of time and cause massive delays causing the project to start running suddenly without the user knowing which was a safety hazard.
* This was to accurately solve for the time estimate; It did not provide very successful time estimates. 
* The PlotPlanner code also confused the driver, where there was mostly repeated code in order to count the number of cuts in a strange fashion.
> Remove Dummy PlotPlanners

- meerk40t/core/element_commands.py
- meerk40t/gui/laserrender.py
The subvariant --outer requires one additional pass where we disassemble
the first outline and fill the subpaths, This will effectively deal with
donut-type shapes
The need for --inner was't high on my priority list (as it is somewhat
difficult to implement, --outer just uses a clever hack to deal with
topology edge cases. So if we are in need of inner we need to create
the outline shape, break it in subpaths and delete the outer shapes
manually. Sorry.
> outline --outer can deal now with more topologies

- locale/de/LC_MESSAGES/meerk40t.po
- meerk40t/core/element_commands.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/scenewidgets/machineoriginwidget.py
- meerk40t/gui/wxmmain.py
Sorry, two independent changes combined, did it only realise after the commit. Anyway:
- Fix for circ_copy and radial crash
- Allow suppression of machine origin widget
> Allow suppression of machine origin widget / Fix two commands

- meerk40t/core/cutcode.py
- meerk40t/gui/simulation.py
- meerk40t/gui/toolwidgets/toolcontainer.py
Allow a time-based view of simulation.
While the usual simulation jumps from one completed cutcode operation to the next, you can now choose a timed mode: the simulation jumps from one second to the next and displaying the progress so far:
There are some limitations still:
- intermediate cutcode operations are interpolated with a linear move from cutcode start to end 
- Raster operations are only shown as a growing rectangle
- Very fast units like balor might need a subsecond resolution
> Timed simulation (beta)

- meerk40t/core/element_commands.py
- meerk40t/core/elements.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_hatch.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
a) Drag & drop of regmark nodes directly to an operation was possible -> prevented
b) Drag & drop of regmark nodes back to elements did not classify (if option set)
> Fix drag&drop for regmark nodes

- meerk40t/core/element_treeops.py
- meerk40t/core/planner.py
* on an op, `duplicate elements n times` will duplicate these references in series rather than in parallel.
The reasoning here is that elements are always elsewhere duplicated in parallel.
* Adding a pass to the operation pass value.
* Duplicating the operation as a whole.
* Setting the Job Run passes to a pass value. 
Each duplicates the passes, such that they run in parallel. One full pass finishes then another full pass occurs. Here we modify this to occur in series so that an an unoptimized job will run in series if duplicated in this fashion.
> Duplicate Reference Elements in Series. Optimization Disables.

- meerk40t/gui/simulation.py
- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toolrect.py
Some small changes for Simulation-panel
a) Display icons in operations panel
b) Allow reverting cutcode into operations:
(intentionally nearly hidden...)
> Cosmetics and cutcode 2 operation

- meerk40t/core/element_commands.py
- meerk40t/core/elements.py
- meerk40t/kernel/kernel.py
The use case of `classify` is that it should happen once a command completing data is executed. However, due to the nature of command chaining there's not a good indication of when that would be.
`circle 3in 3in 1in stroke blue fill green rotate 0.4turn` -- is 4 commands. If classification happened after `circle` then it might miss that `stroke blue` happened which changed the classification. If it happened after `stroke blue` it might miss the `fill green` command which could change the classification. And if we looked at the `rotate 0.4turn` we might not consider that this shape requires classification at all.
We expand the kernel commands adding in `post` which is a list of commands to be executed. This command is fed the final chained information, channel, data, data_type it ended …
> Add in PostExec kernel commands

- meerk40t/core/node/op_image.py
- meerk40t/gui/propertypanels/imageproperty.py
- meerk40t/gui/wxmtree.py
a) Cover crash for invalid keys in Tree node format string
b) Provide 'dpi' as possible key for image operation
c) Update elem image tree node
- Still the discussion around the use of the dpi parameter as had in the discord dev group needs to be brought forward.
> DPI display in Tree

- meerk40t/core/core.py
- meerk40t/core/logging.py
- meerk40t/gui/spoolerpanel.py
- meerk40t/kernel/settings.py
- meerk40t/main.py
This PR primarily adds a logging service. The service is mostly a stub. It loads and saves the `.logs` dictionary at `logging.logs` with literals. So any `int` placed in that dictionary of dictionaries will be loaded and saved as an integer. Feel free to add any logic you need into the service. 
This is intended to replace the `.json` and `.csv` currently doing that logging. These are not easily human-readable but if stored as a dictionary entry with keys corresponding to what that data is, this should increase readability. The current implementation is a list of lists in the "history" entry of the "spooler" dictionary. This is mostly for consistency since it requires no major changes.
Current logging suffers from several problems.
* Logging is done through signals sent and gui caught …
> Logging Service for Spooler History

- meerk40t/core/element_commands.py
- meerk40t/core/elements.py
- meerk40t/gui/propertypanels/pathproperty.py
- meerk40t/tools/livinghinges.py
Extend simplify to use a multi-pass approach:
1) Delete zero length lines generated from the algorithms (new)
2) Simplify lines that have a lot of in-between points (old)
3) Join path segments that have a coinciding end points (new)
4) Join subpaths that end in a line segment that are coinciding
> Extended path simplification

- meerk40t/kernel/kernel.py
- meerk40t/lihuiyu/driver.py
- test/test_drivers_lihuiyu.py
* Jogs between objects ignored the settings for traveling at restricted speed.
* Correct the jog directions to combine the x and y at the speed of the slower when the slower is longer.
* If x is faster and y is slower but x is longer, does a proper zig at the respective speeds.
> Lihuiyu: Correct Override-Speed Fix

- meerk40t/camera/gui/camerapanel.py
- meerk40t/gui/wxmribbon.py
After 'Identify cameras' the ribbonbar button switches to the first identified camera
> Switch Camera button to first identified camera

- meerk40t/core/element_commands.py
```python
MeerK40t crash log. Version: 0.8.1000 on Windows: Python 3.7.9: AMD64 - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
File "meerk40t\gui\navigationpanels.py", line 622, in on_button_align_trace_quick
File "meerk40t\kernel\context.py", line 33, in __call__
File "meerk40t\kernel\kernel.py", line 2097, in console
File "meerk40t\kernel\kernel.py", line 2146, in _console_parse
File "meerk40t\kernel\functions.py", line 279, in inner
File "meerk40t\core\elements.py", line 6429, in trace_trace_spooler
File "meerk40t\core\elements.py", line 6362, in generate_hull_shape
TypeError: 'NoneType' object is not subscriptable
```
Object bounds is None. Crash.
```python
MeerK40t crash log. Version: 0.8.1002 on Windows: Python 3.7.9: AMD64 - wxPython: 4.1.1 msw …
```
> Hull methods divided. Correct two main crashes.

- meerk40t/core/element_commands.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_geomstr.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/mixins.py
- meerk40t/core/svg_io.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/statusbarwidgets/strokewidget.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
Intended to fix #1596 and #1507.
This affects the drawn size of the paths so as to avoid the `round()` then `scale()` issues within wxPython. Where if we have a scale of 2800 then we round to 1, 2, 3 etc then scale by 2800 giving our values units of 2800, 5600, 8400 etc. This causes a number of very detectable artifacts. The number system used is 1/65535 of an inch because it won't show any artifacts even at the sub-mil level and can still do designs in linux the size of a football field (2^24 range).
This messes with the stroke-scaling and stroke-width since they expected to be scaled up and then manipulated. For most cases the default native stroke value is correct, but this doesn't work for stroke scaling.
> Modify `make_path` transformed segments

- meerk40t/core/element_commands.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/mixins.py
- meerk40t/core/node/node.py
The nuked attempt at a Beta3 was nuked because stroke-size changes caused all rasters to suppose their stroke sizes were always massive.
This happens because there's two modes for stroke scaling. None and scaling. Basically if at transform `matrix0` we are exactly equal to `stroke-size` then at a different transform `matrix1` we are at a different scaling. If we are non-scaling the stroke size at `matrix1` is the same as at `matrix0` since the stroke size remains constant. If we are scaling then the stroke size is different by `sqrt(abs(det(matrix1))) / sqrt(abs(det(matrix0)))` Which is to say the difference in 1d scaling at those two matrix positions.
For SVGs that are loaded this tends to discount all the the official scaling but not the viewport of the `height`, `width` and `viewbox` …
> Fix Stroke-Sizes for Rasters

- meerk40t/gui/opassignment.py
- meerk40t/gui/wxmtree.py
a) If op property was open and context menu 'Convert operation' was done then a crash could occur
b) Reestablish logic to force + sign at op nodes.
> op nodes show + sign

- meerk40t/core/spoolers.py
- test/bootstrap.py
- test/test_spooler.py
Sends a job to the spooler that is not a laser job to test for the regular fail conditions for non-regular jobs.
> Add Test for Spooler Non-Regular Job

- meerk40t/core/node/elem_text.py
- meerk40t/gui/laserrender.py
There were a couple of deficiencies around the treatment of text elements:
File:
Was:
a) Some font-properties like font-size and others were not properly recognised
after fixing this it became evident 
b) that the treatment of establishing the text size was flawed as the size of the text box needed to be established every single time as paint_bounds was dirty by defintion
c) A large font-size that was reduced by a viewport would generate huge preview pictures (25000 x 6000 pixels) which made the manipulation of such elements nearly impossible
> Missing font fix - speedup of large font-sizes

- meerk40t/core/element_commands.py
- meerk40t/gui/wxmtree.py
Weren't update after a stroke/fill command (as used eg by the stroke-color widget in the statusbar)
> More consistent update of icons in tree

- meerk40t/core/cutcode/plotcut.py
- meerk40t/ruida/emulator.py
- meerk40t/ruida/plugin.py
0.8.x required some changes to the rasters and caused some garbling of the rasters. This is an attempt to finally fix those.
1. Converts ruidaemulator to a driver-like emulator. This means that the code operates on a something that works like a driver.
2. Converts the rapid movement objects to movements at a speed. The move panel lets you do movements at a speed, this was a complaint in the older version, the speed was not respected.
3. Use plotcut more centrally as the core data structure.
> Ruidacontrol Fixes

- meerk40t/core/svg_io.py
Fixes treatment of files like this:
where ``fill='currentColor'`` or ``stroke='currentColor'`` are used.
Addresses: https://github.com/meerk40t/meerk40t/discussions/1657
> Fix treatment of fill='currentColor'

- meerk40t/core/element_treeops.py
- meerk40t/core/spoolers.py
- meerk40t/grbl/control.py
- meerk40t/grbl/emulator.py
- meerk40t/grbl/gcodejob.py
- meerk40t/grbl/plugin.py
- meerk40t/tools/driver_to_path.py
- test/test_spooler.py
A principle reason why realtime commands don't work in the 0.8.2 version is that the emulator is really two parts. One governs the control over the laser. This is the reverse of the controller. Whereas the other governs the execution of code, this is the inverse of the driver. It's possible to use GRBL-like control interfaces while sending data that is not strictly grbl (except jog which is written in grbl code but is done in a non-modal fashion. 
So even with properly different threads to write the code to the emulator as to execute it, the realtime commands cannot execute until the execution catches up. The result is that we need a realtime commands to control the laser and the programmed commands to send to the laser as a program.
> Divide Emulator and Job for GRBL and Ruida

- meerk40t/core/element_treeops.py
The use case to adjust some speed / power settings globally to acknowledge a different material can be quite cumbersome to perform, especially if the laser does not have a global external power setting as found in most K40s, like for Diode Lasers.
> Add speed/power scaling option for all ops

- meerk40t/core/element_treeops.py
- meerk40t/core/wordlist.py
- meerk40t/gui/hersheymanager.py
Vectortext (or regular text) might crash during copying if they were containing just numbers (ie "5").
> Fix text with pure numbers

- meerk40t/balormk/elementlightjob.py
- meerk40t/balormk/gui/gui.py
- meerk40t/balormk/livefulllightjob.py
- meerk40t/balormk/liveselectionlightjob.py
- meerk40t/grbl/device.py
- meerk40t/gui/wxmribbon.py
The goal of this PR is to ensure that the ribbon toggle state is compatible with the choices panel signals of the same varieties.
Currently the state is the opposite of the sent signal state. So `stop_tracing True` would tell make the trace button state toggle to unpressed. This is the opposite of what the choice panel would send for the same sort of state. So if they reference the same variable they cannot be made to agree as things are currently set.
This changes that.
* We add `toggle_attr` for triggering the setting the toggle state's attr rather than `identifier` which is typical for multi-based buttons.
* We flip the current buttons for Galvo-Trace buttons. GRBL-RedLight buttons. And we will also switch Newly AutoExecute button.
> Signals RibbonToggle State

- meerk40t/core/element_commands.py
- meerk40t/core/elements.py
- meerk40t/gui/wxmmain.py
Element distribution routines do recognise groups now
Start:
Before the fix (distribute vertically):
After the fix:
> Fix spacev/spaceh distribution logic

- meerk40t/gui/wxmmain.py
The delete key binding was useless as the menu entry under "Edit - Delete" was called first.
> Fix delete behaviour

- meerk40t/core/cutplan.py
- meerk40t/core/node/node.py
* register previous bounds on preprocess. If you somehow do phased additions to a plan it will maintain the correct bounds merging previous bounds into them.
* Only check for bounds union if the element has bounds.
*  This should prevent cutcode crash as well as utility operations which should also crash.
* If our bounds are infinite, in that there are no bounds (negative space). We set outline equal to none.
> Correct CutPlan Crash on Bounds

- meerk40t/balormk/driver.py
- meerk40t/core/core.py
- meerk40t/core/elements/elements.py
- meerk40t/core/elements/penbox.py
- meerk40t/core/node/op_hatch.py
- test/test_elements_penbox.py
Penbox was added to the elements service but isn't needed there. It merely stores a list of settings within ranges and shifts to allow mapping of value to particular overloaded settings or a different setting for each pass.
> Move penbox to being its own service.

- meerk40t/gui/wxmmain.py
Fixes #1397
This was turned into a feature but it is ambiguous, if you resize something and maintain the zoom. You expect to not change the zoom. However, with maintain_zoom on it would issue the `scene focus` command to discard the zoom you were using.
Further this defaulted to True, meaning that refocus on resize was the default behavior.
Fixing this requires a name change to correct the ambiguity and to more correctly set default `autofocus_resize` to False, which means do not autofocus on resize.
> Change `maintain_zoom_reseize` to `autofocus_resize` default off

- meerk40t/core/elements/element_treeops.py
- meerk40t/gui/wxmscene.py
- Sync status properly
- Allow regmarks to become ref object via context menu (needed previously to assign the status to a regular element and move it to regmark)
> Some changes around reference object

- meerk40t/ch341/libusb.py
- meerk40t/ch341/mock.py
- meerk40t/ch341/windll.py
- meerk40t/gui/laserpanel.py
- meerk40t/lihuiyu/controller.py
* `bulk` as an option for the different ch341 drivers.
* `loop_cond` threading.Condition() used rather than 
* notify loop_cond on state change.
* notify loop_cond on abort retry
* notify loop_cond on write/realtime_write
* Replace sleep if paused and realtime buffer is empty.
* Replace sleep with wait() if aborted_retries
* Rather than counting up for no-packet, wait()
* Move buffer-transfer and check for blank packet into `thread_loop`
> CH341 M3Nano Status

- meerk40t/gui/scenewidgets/machineoriginwidget.py
* The main angles for widget start from 0,0 and point x (red), and y (green). But the red rect actually is the machine origin which is not necessarily the same point as the display 0,0.
> Position the Machine Origin Widget at the device origin (always).

- meerk40t/gui/wxmtree.py
> Mac OSX: Tree too large vs. Laser Pane

- meerk40t/core/bindalias.py
- meerk40t/gui/wxmmain.py
Anything that is already exists in Menubar cannot be a keybind here (at least by default)
Linux will execute both. Causing double-undos.
> Remove double bound commands. 

- meerk40t/camera/plugin.py
Changed 'localhost' to '0.0.0.0'
Restricting who can access a TCP connection in this way is only useful in protecting dev environments, not production.
> camserver was set to listen on localhost only. Fixed.

- meerk40t/kernel/kernel.py
- meerk40t/lihuiyu/controller.py
Use Control Transfer with first 10 attempts being without delay. Then above 10 attempts we delay 0.001 seconds incrementing for each attempt or to a max of 0.1 seconds over a total of 500 attempts.
The last 400 attempts would be 40 seconds, which would not typically happen without a real break.
> Safe Lihuiyu Status Control-Transfer

- meerk40t/core/elements/align.py
- meerk40t/core/elements/element_treeops.py
- meerk40t/core/elements/element_types.py
- meerk40t/core/elements/offset.py
- meerk40t/core/elements/shapes.py
- meerk40t/core/node/bootstrap.py
- meerk40t/core/node/effect_hatch.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/node.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_engrave.py
- meerk40t/device/gui/formatterpanel.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/propertypanels/pathproperty.py
- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/elementswidget.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/gui/wxmtree.py
- meerk40t/tools/geomstr.py
* Adds `effect hatch` as an effect node type.
* Contains a list of operands geometry.
* If the effect is enabled, the operands are used to build a hatch structure.
* If the effect is disabled, children are given rather than operands and the object works like a group.
* Adds tree effect on, effect off toggles.
* Effect nodes very similar to elem nodes.
* `op cut` and `op engrave` accept `effect hatch`.
* Adds `render_tree()` command (unused) in laserrender
> Effect hatch

- .github/workflows/mac11_pyinst.yml
- .github/workflows/win.yml
This does a few things differently from Tat's build yml work.
It does a `pip install .` instead of a `pip install .[all]`
This prevents it from installing any extra deps from setup.py's [all]
Extra deps are explicitly listed in `pip install` commands
Updates the subactions used (actions/checkout@v2 -> v3 etc) to satisfy a runner warning.
Removes the explicit x64 architecture (it is the default, specifying it at all was in order to get x32)
Restablishes the version lock of opencv so that the build has the camera again.
Comments add/moved around so that everything is more readable.
This was tested in tiger12506's fork to produce Windows builds that seem valid.
Also, there is an update to the mac11 runner which fixes a build error.
A little cleanup of redundant comments.
And I removed the …
> Build fixes

- meerk40t/lihuiyu/driver.py
DPI would typically only be a change of 1 or so, and while a few differences from a missing scanline is fine we're probably better off just aborting since lateral moves near 15 make a knock.
> Fix knocking for scanline distances between 15 and 5.

- meerk40t/gui/laserpanel.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmribbon.py
- meerk40t/gui/wxmtree.py
Changes Design to first, adds in the load option and regular design tools. The Project tab still has the windows.
Request for Comments, might need more tweaks or remission.
> Version 0.9.x UI tweaks

- meerk40t/balormk/device.py
Force abort of a working job, rather than waiting for the spooler thread to try to cause the abort.
As notified by Bzzrd in discord. This probably needs functional testing.
Light jobs have a faster cycle of data being sent and thus abort much faster and are constantly sending new data and the `live` version will abort anytime the backing data changes.
Whereas jobs that are sent via the spooler could be entirely composed and sent to the controller and live in memory and estop will not take effect on that until additional data is sent. 
---
Waiting on testing by @tiger12506 or @joerlane, but we should ensure that the estop button works instantly for galvo in all cases.
> Estop for Galvo works too slow.

- .github/workflows/win.yml
Tested. This fixes the libusb issue.
Recommendations:
Don't fix stuff that ain't broke.
Python architecture should show in About -> System Information? Is this possible?
> Restore the Win build architecture: x86 for libusb

- meerk40t/gui/icons.py
- meerk40t/gui/ribbon.py
Should recognise system settings, but can be forced via console 'set force_darkmode True'
> Implement a dark mode for the ribbon bar

- .github/workflows/win.yml
Untested, but these are the same changes we just made in legacy8
> Lock pillow==9.5.0, unlock pyinstaller. Fixes builds.

- meerk40t/gui/devicepanel.py
- meerk40t/gui/laserpanel.py
In Laser-Control:
In device manager:
NB: only for active device! Not sure how to open the registered guis for non-active services
> Add config option near device selection

- meerk40t/balormk/device.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_hatch.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
- meerk40t/device/gui/formatterpanel.py
- meerk40t/grbl/device.py
- meerk40t/gui/propertypanels/operationpropertymain.py
- meerk40t/gui/wxmtree.py
- meerk40t/lihuiyu/device.py
- meerk40t/newly/device.py
Allow a per device setting whether power should be displayed as ppi (default) or as percentage.
Addresses [Issue #1943](https://github.com/meerk40t/meerk40t/issues/1943)
> Device specific power display in tree

- locale/de/LC_MESSAGES/meerk40t.po
- meerk40t/gui/materialtest.py
- meerk40t/kernel/settings.py
Parameter-test allows now to save/restore the settings for repeated use:
Contains as well a fix for the deletion of a single key in kernel.settings - did never raise its head as it was not used so far...
> Persistent storage of materialtest templates

- meerk40t/core/elements/element_treeops.py
A disabled operation will not appear in simulation, so makes no sense to offer that option
> Suppress 'Simulate' in op context menu if inactive

- meerk40t/grbl/device.py
- meerk40t/lihuiyu/device.py
- meerk40t/moshi/device.py
- meerk40t/ruida/device.py
The rotary settings do not save because the rotary attributes are part of ViewPort.__init__() but are not called so regardless that the `rotary` choice actually loads the settings these settings are not passed to the init routine and thus are set to the default in that initialization routine thereby losing those parameters.
> Correct Issue #2027

- meerk40t/core/elements/element_treeops.py
- meerk40t/core/elements/elements.py
- meerk40t/core/planner.py
- meerk40t/gui/wxmtree.py
a) Make the warnicon in the tree aware of disabled operations as they won't be burnt either
b) Reestablish lost functionality to simulate disabled operations (only if the disbaled operation is the single selected one).
> Disabled op treatment

- meerk40t/core/elements/elements.py
.eps files for instance were covered by ImageLoader, which most of the time fails. If no information was loaded then mk will now use the next available loader for that type - in our .eps example inkscape would be called, too.
> Keep on using loaders if no information was loaded

- meerk40t/core/elements/elements.py
- meerk40t/ruida/emulator.py
- meerk40t/ruida/loader.py
- meerk40t/ruida/rdjob.py
Several examples of crashing due to control software sending different values, but all control software sends a request for the CardID. Checking that we can determine the expected swizzle and automatically adjust for it.
> Correct RuidaControl/RD-loading.

- meerk40t/gui/scenewidgets/guidewidget.py
Ugly fix: no guides will be displayed if scene is rotated. Could need some distinction for 90 / 180 / 270 deg.
> Prevent endless loop if scene is rotated

- meerk40t/core/elements/elements.py
- meerk40t/gui/basicops.py
- meerk40t/gui/statusbarwidgets/defaultoperations.py
- meerk40t/gui/wxmmain.py
- meerk40t/kernel/settings.py
a) Centralize code to load/save/generate default operations to elements.py
b) Allow to have device dependent default operations (save them under ``_default_``_devicelabel_) (so if your current device is called 'balor-device' then use ``_default_balor-device``)
c) a fix for the derivable function in the settings class to make the above work
> Some fixes / improvements for default / basic ops

- meerk40t/core/elements/elements.py
- meerk40t/core/node/node.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
- meerk40t/core/node/place_current.py
- meerk40t/core/node/place_point.py
- meerk40t/core/parameters.py
- test/test_operations.py
Several operations have .attr values like `id` and `stopop` and these would be lost since they aren't stored in the .settings dictionary. This is not a problem with Elem nodes, where they copy the node dictionary correctly.
Here we standardize the op dictionary copying for operations.
> Improve/Standardize Op Dictionary Copying

- meerk40t/gui/ribbon.py
- meerk40t/gui/toolwidgets/toolnodeedit.py
- meerk40t/gui/toolwidgets/toolpolygon.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmribbon.py
- meerk40t/gui/wxmscene.py
The Node-Editor got reestablished. The corresponding tool is using ``tool edit`` again (``tool nodemove`` is still around but no longer exposed in the GUI)
The toolwidget uses a newly established functionality to use the secondary tool ribbonbar. This is usable for all toolwidgets if they register some buttons. As an example - more a proof of concept than the intent to create something really useful - the polygon tool got some subtools to play with.
> Node editor + secondary tools

- meerk40t/core/elements/elements.py
- meerk40t/core/svg_io.py
- meerk40t/gui/wxmmain.py
Allow loading of svg files without the operations branch (uses a custom loader)
That required = introduces the opportunity to overrid the default = first loader that would fit the file extension. If you have selected a certain wildcard (corresponding to a loader) that will be honored.
> Plain svg loader

- meerk40t/core/node/effect_hatch.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_image.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_point.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/groupnode.py
If you drag e.g. a Cut operation onto an element then that element will be added to the operation (drag = dropped element to be adopted, reverse drag = dropped operation will be assigned)
> Allow dragging of an operation node onto an element

- meerk40t/core/elements/elements.py
- meerk40t/gui/icons.py
- meerk40t/gui/statusbarwidgets/defaultoperations.py
- meerk40t/gui/wxmmain.py
- A couple of visual improvements for the icons at the bottom of the screen
- Better reaction to changes of devices / changed material sets
- Ad-hoc loading of material sets
- User defined ordering of icons
-
> Default operations

- meerk40t/balormk/balor_params.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_point.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/mixins.py
- meerk40t/core/node/node.py
- meerk40t/core/parameters.py
The Stroked mixin is different and implies different things than the FunctionalParameter mixin. This makes sure that `super()` is correctly called by Node, Stroke, and FunctionalParameter (needed to traverse the class tree init commands).
This also ensures that .mkparam is always initialized correctly.
Point is not a `Stroked` but is `FunctionalParameter` since you could have a point with a functional parameter but not one with a stroke.
> Subdivide the Mixins for the Element nodes

- meerk40t/core/node/node.py
Root is always there. Sometimes notification might not occur from nodes which are not part of the active tree. But rather than directly contact the root, it will filter the notifications up from the child to parent until reaching the root. The distinction being that parents can override the notification to receive the notice.
> Propagate node notify_modifiers through parents rather than directly through roots for extensibility.

- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/attractionwidget.py
- meerk40t/gui/statusbarwidgets/selectionwidget.py
- meerk40t/gui/statusbarwidgets/statusbar.py
- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toollinetext.py
- meerk40t/gui/toolwidgets/toolplacement.py
- meerk40t/gui/toolwidgets/toolpoint.py
- meerk40t/gui/toolwidgets/toolpolygon.py
- meerk40t/gui/toolwidgets/toolpolyline.py
- meerk40t/gui/toolwidgets/toolrect.py
- meerk40t/gui/toolwidgets/tooltext.py
- meerk40t/gui/toolwidgets/toolvector.py
- meerk40t/gui/wxmmain.py
If you had snap to grid or elements active the very first point was still unaware of snapping. That has been fixed.
Old:
New:
> Improved snap behaviour for first point

- meerk40t/tools/geomstr.py
geomstr did not recognise intentional moves inside a path if the point before and after the move had the same coordinates.
> Introduce break subpaths when parsing a svg path

- meerk40t/gui/scene/scene.py
* Add in `invalidate()` for specific scene clipped scene redraws.
* Add in multiple buffers for redraw elements
Tools should be able to call `request_refresh()` to refresh entire scene. But, should also be able to call `invalidate()` to mark sections of the screen as dirty. This permits a clipped redraw of just the needed sections.
We should also permit multiple buffers for specific draw layers. If we have an interaction layer we don't need to redraw everything each time we select something with a rectangle or the like. We can draw the selection rectangle (and other widgets) within that layer by only invalidating the relevant part of the relevant layer.
> Scene Optimizations

- meerk40t/core/elements/element_treeops.py
- meerk40t/core/elements/element_types.py
- meerk40t/core/node/elem_image.py
- meerk40t/core/node/op_raster.py
- meerk40t/image/imagetools.py
* Restore default image load class is `elem image`
* Fix display of `elem image`
* Permit creation of `image raster` from `elem image`.
> Correct issues for the 0.9.3 merges

- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toolimagecut.py
- meerk40t/gui/toolwidgets/toolline.py
- meerk40t/gui/toolwidgets/toolrect.py
- meerk40t/gui/wxmmain.py
- File operations reset the tool to ``tool none``
- Singleclicks could not generate element primitives (circle, ellipse, rect etc.) but weren't passed along either
> Selection fixes

- locale/de/LC_MESSAGES/meerk40t.po
- locale/es/LC_MESSAGES/meerk40t.po
- locale/fr/LC_MESSAGES/meerk40t.po
- locale/hu/LC_MESSAGES/meerk40t.po
- locale/it/LC_MESSAGES/meerk40t.po
- locale/ja/LC_MESSAGES/meerk40t.po
- locale/messages.po
- locale/nl/LC_MESSAGES/meerk40t.po
- locale/pt_BR/LC_MESSAGES/meerk40t.po
- locale/pt_PT/LC_MESSAGES/meerk40t.po
- locale/zh/LC_MESSAGES/meerk40t.po
- meerk40t/grbl/gui/grblcontroller.py
- meerk40t/lihuiyu/gui/lhycontrollergui.py
- meerk40t/lihuiyu/gui/lhydrivergui.py
- meerk40t/lihuiyu/gui/tcpcontroller.py
Made control sizes a bit more compact for Lihuiyu controller:
Added device info to controll button for GRBL + reduced bitmap size a bit
> Make m2nano controller window a bit more compact

- meerk40t/dxf/dxf_io.py
The different segments of a dxf path were added with different stroke-widths
> Consistent use of stroke attributes for all dxf path elements

- meerk40t/grbl/driver.py
- meerk40t/tools/geomstr.py
- test/test_geomstr.py
See Discord discussion (11-21-2023 11:29 PM PST). The GRBL code interpolates a curve into 50 subpoints regardless how intricate the curve is. This means small fragments of curve are made more fragmented and does not account for the speed change within bezier curves ( https://youtu.be/aVwxzDHniEw?si=nUytSTNjguAWS1nn&t=907 ).
The algorithm around this is usually to use a lookup table of distance and slice into that lookup table. Here I did a bit of a different thing but it mostly would work slightly inferior.
> Add in GRBL Interpolation tweaks.

- meerk40t/core/svg_io.py
- meerk40t/dxf/dxf_io.py
- meerk40t/image/imagetools.py
Image loading in place is not reasonably universal for versions of Pillow.
> Fix `in_place` flag compatibility for image loading.

- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_point.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/gui/wxmtree.py
- meerk40t/tools/geomstr.py
Some wxmtree calls delegated to the `.shape.` call, these were slower.
In the case of rect with rounded corners calling `node.shape.length` was actually prohibitively expensive because calculating the length of an arc without scipy is non-trivial
> Simplify geometric calls in wxmtree.

- meerk40t/gui/toolwidgets/toolpointmove.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
- Line tool added
- The finger icon will either launch parameteric edit (as before) or - if the element does not support the feature - a simple node point mover. All the extended functionalities found in node edit will remain there.
> Line-tool / add simplified point move

- meerk40t/kernel/kernel.py
A rare edge case could occur during shutdown where if the signal job `MainThread` processing could occur at the same time as the shutdown `run` and both called `process_signals()` the previous mechanism was using a double-buffer where the `message_queue` used to store new messages and the `processing` would swap the two. So the messages to be processed would be put into processing, and messaging would be the empty dictionary (after processing). This allowed for additional `signals` to be added to the messaging queue while the processing queue was processing the process data.
However, this would end very poorly during shutdown which explicitly calls `process_signals()` before preventing any additional signals to get added, and then processing anything that got added during that gap. …
> MKernel: Improve Signal Swap

- meerk40t/extra/ezd.py
Fixes hatch counts for some versions of ezcad2 with hatches only up to 42 elements.
> Correct hatches for those lacking count values (#2331)

- meerk40t/lihuiyu/device.py
- test/bootstrap.py
- test/test_drivers_grbl.py
- test/test_drivers_lihuiyu.py
Fix rotary commands for after the 0.9.2 coordinate system update.
The coordinate system was switched to 4-to-4 point mapping system since its significantly easier to use consistently and covers things like rotation clockwise, etc. This however, broke the older system which was used for the rotary system and setup. This corrects that oversight.
> Rotary Corrections

- meerk40t/gui/materialmanager.py
- Persists changes to materials to disk immediately
- Recognise ezcad3 files (same format as ezcad2 but just different extension)
> Matman: saving + ezcad3 support

- meerk40t/core/elements/elements.py
- meerk40t/gui/wxmribbon.py
- meerk40t/kernel/kernel.py
- meerk40t/kernel/settings.py
if you use the ``create_backup`` parameter when instantiating a Settings object then it will maintain copies of the old config file before writing the new version: it will generate up to 6 previous versions of the file
``.bak``, ``.ba1`` .. ``.ba5`` - ``.bak`` the most recent one, ``.ba5`` the oldest
> Settings backup

- meerk40t/balormk/controller.py
- meerk40t/balormk/device.py
- meerk40t/balormk/gui/balorcontroller.py
- meerk40t/device/dummydevice.py
- meerk40t/grbl/controller.py
- meerk40t/grbl/device.py
- meerk40t/lihuiyu/controller.py
- meerk40t/lihuiyu/device.py
- meerk40t/lihuiyu/gui/lhycontrollergui.py
- meerk40t/moshi/controller.py
- meerk40t/moshi/device.py
- meerk40t/moshi/driver.py
- meerk40t/moshi/gui/moshicontrollergui.py
- meerk40t/newly/controller.py
- meerk40t/newly/device.py
- meerk40t/newly/gui/newlycontroller.py
- meerk40t/ruida/controller.py
- meerk40t/ruida/device.py
- meerk40t/ruida/driver.py
- meerk40t/ruida/gui/ruidacontroller.py
- meerk40t/ruida/mock_connection.py
- meerk40t/ruida/serial_connection.py
- meerk40t/ruida/udp_connection.py
* Add in `device.safe_label` property universally to all drivers.
* Replace code-level safe_label with property
* Fix several controller open (listens) vs close (unlisten) where the label could have changed and thus crashed.
> Device.safe_label + Bug Fixes

- meerk40t/gui/laserpanel.py
- meerk40t/rotary/rotary.py
I was looking for quite a lot of time for bugs in my code until I realised that I had rotary mode activated - so a clearer indicator of this being acctive was required.
> Clearer visual indicator that rotary mode is active

- meerk40t/gui/scenewidgets/selectionwidget.py
Moving a selection will be a bit smarter - until now it tried to snap the center of the selection to either grid or element points.
Now it will check (in hierarchical order)
1. would any point of the selected elements (=start + end points of geomstr segments) snap to a point of the non-selected elements (needs flag ``snap to element`` active) 
2. would any of the 4 corners + center of the selection snap to a grid point (needs flag ``snap to grid`` active)
3. would the center of the selection snap to a point (old logic)
4. both 2. and 3. are followed by a magnetline attraction (if any)
> Extended snap logic

- meerk40t/kernel/functions.py
- meerk40t/kernel/kernel.py
- test/bootstrap.py
- test/test_kernel.py
* Correct return for `kernel.console` call
* Testing.bootstrap now allows adding test plugins
* added _command_attach/_command_detach
* Hooked to lifecycle: kernel.boot`, `service.added`.
* Removed from lifecycle `remove_delegate`, `kernel.preshutdown`, `service.shutdown`.
The chief purpose of this PR is to allow kernel to use `@service_console_command` and `@kernel_console_command` decorators in the kernel (or delegate thereof) or in a service or delegate thereof.
The _() command is usually located in the kernel and so it's decidedly much harder to get this to work correctly if they are class methods.
> Add service/kernel console command applied to lifecycle objects

- meerk40t/gui/scenewidgets/rectselectwidget.py
Special case: if the user did not move the mouse within the first 0.5 seconds after
the initial mouse press then we assume a drag move.
> Use element dragging instead of selection rectangle after some time

- meerk40t/extra/hershey.py
- meerk40t/gui/hersheymanager.py
- meerk40t/tools/jhfparser.py
- meerk40t/tools/shxparser.py
- meerk40t/tools/ttfparser.py
- Autocad fonts were no longer rendered correctly (did not reset the internal position)
- Added support for a poor man kerning ie character gap adjustment
> Vectorfont - fixes and poor man's kerning

- meerk40t/core/node/branch_elems.py
- meerk40t/core/node/branch_regmark.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_image.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_point.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/groupnode.py
- meerk40t/core/node/image_processed.py
- meerk40t/core/node/image_raster.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/refnode.py
Most nodes check for `type.startswith("elem")` rather than whether they give geometry and as such would not accept an effect which has geometry but is not an an `elem` type.
> Effect Drag-and-Drop treatment correction.

- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/toolcontainer.py
- meerk40t/gui/toolwidgets/tooldraw.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toolimagecut.py
- meerk40t/gui/toolwidgets/toolline.py
- meerk40t/gui/toolwidgets/toollinetext.py
- meerk40t/gui/toolwidgets/toolmeasure.py
- meerk40t/gui/toolwidgets/toolnodeedit.py
- meerk40t/gui/toolwidgets/toolnodemove.py
- meerk40t/gui/toolwidgets/toolparameter.py
- meerk40t/gui/toolwidgets/toolplacement.py
- meerk40t/gui/toolwidgets/toolpoint.py
- meerk40t/gui/toolwidgets/toolpointlistbuilder.py
- meerk40t/gui/toolwidgets/toolpointmove.py
- meerk40t/gui/toolwidgets/toolpolygon.py
- meerk40t/gui/toolwidgets/toolpolyline.py
- meerk40t/gui/toolwidgets/toolrect.py
- meerk40t/gui/toolwidgets/toolrelocate.py
- meerk40t/gui/toolwidgets/toolribbon.py
- meerk40t/gui/toolwidgets/tooltext.py
- meerk40t/gui/toolwidgets/toolvector.py
- meerk40t/gui/wxmscene.py
* Add in a small alteration to the tools api. Rather than just the tool name, the `tool <tool> <extra>` data is sent to the tool to process additional modal information.
* Rewrite's ribbon to allow for more advanced and different mode ribbons.
* Default ribbon made ribbon `gravity`.
Ribbon Variants Added:
* gravity
* line
* smooth
* speedzig
* reverb
* calligraphy
* nudge
* bendy_calligraphy
* rake
* crescent
> Advanced Ribbon Tool, Tool Modes

- meerk40t/core/elements/element_treeops.py
- meerk40t/core/elements/offset_clpr.py
- meerk40t/extra/cag.py
a) Polybool was not using the absolute paths, so transformation matrices were ignored
b) clipper cag routines did not combine subpaths of subjects properly
c) Adding merge = extend path routines for any two or more selected graphics primitives without the need for having them in a group. Addresses Issue #2348
> Merger fixes

- meerk40t/core/cutplan.py
- meerk40t/core/elements/branches.py
- meerk40t/core/elements/element_treeops.py
- meerk40t/core/node/util_goto.py
- meerk40t/gui/propertypanels/gotoproperty.py
- meerk40t/gui/wxmeerk40t.py
* Fix use of `Length` by default for GotoOperation.
* Preprocess to native units, allowing default to be converted to correct units.
* Add Tree Operation to add GotoOperation.
* Add GotoProperty window to allow you to modify the properties of a Goto Location operation.
> GotoOperation Corrections

- meerk40t/core/bindalias.py
- meerk40t/gui/helper.py
- meerk40t/kernel/kernel.py
Allow lock/unlock of the helper pane updates via Ctrl+Shift+l to give the user the opportunity to thoroughly study the displayed text.
(Added a 'signal' command under the hood to allow sending of signals via the console)
> lock/unlock of the helper pane updates 

- meerk40t/core/cutplan.py
- meerk40t/core/elements/offset_clpr.py
- meerk40t/core/elements/offset_mk.py
- meerk40t/core/elements/shapes.py
- meerk40t/core/planner.py
- meerk40t/tools/geomstr.py
- Replace the existing simplify method of geomstr (which was based on the old svg path paradigm anyway) with an implementation of the Ramer-Douglas-Peucker algorithm to reduce the amount of points in a polyline section of the geometry.
- Changing the ``simplify`` command to use this
- Fixing a bug within ``Geomstr.as_contiguous`` 
- Kerf offset calculation will automatically call the simplify method (with minimal tolerance to just reduce the amount of points a bit)
- Added an optimisation option to apply polyline simplification. By default off
> Geomstr simplify

- meerk40t/camera/gui/camerapanel.py
- meerk40t/gui/navigationpanels.py
- meerk40t/gui/position.py
- meerk40t/gui/ribbon.py
- meerk40t/gui/statusbarwidgets/defaultoperations.py
- meerk40t/gui/wordlisteditor.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/gui/wxmribbon.py
Fixing a lot of places where a button needs an image of a certain size. This wxpython issue is only appearing on windows displays where a user_scale factor has been set beyond 150% (at least on my system).
> High dpi fixes

- meerk40t/grbl/device.py
- meerk40t/grbl/driver.py
- meerk40t/grbl/emulator.py
- meerk40t/grbl/gui/grblcontroller.py
Allow an optional parameter to reset the device too when clearing an alarm status as this seems to be required for some devices.
> Alarm reset

- .github/workflows/win/file_version.txt
- meerk40t/balormk/device.py
- meerk40t/balormk/driver.py
- meerk40t/core/elements/elements.py
- meerk40t/grbl/device.py
- meerk40t/grbl/driver.py
- meerk40t/grbl/emulator.py
- meerk40t/gui/materialmanager.py
- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/attractionwidget.py
- meerk40t/gui/scenewidgets/rectselectwidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
- meerk40t/gui/statusbarwidgets/defaultoperations.py
- meerk40t/gui/toolwidgets/toolmeasure.py
- meerk40t/gui/toolwidgets/toolnodeedit.py
- meerk40t/gui/wxmmain.py
- meerk40t/gui/wxmscene.py
- meerk40t/gui/wxutils.py
- meerk40t/main.py
- meerk40t/moshi/device.py
- meerk40t/moshi/driver.py
- meerk40t/newly/device.py
- meerk40t/newly/driver.py
- setup.cfg
Requires:
--- Added PRs
* Recognize device rename in device manager by @jpirnay in https://github.com/meerk40t/meerk40t/pull/2322
* Update check by @jpirnay in https://github.com/meerk40t/meerk40t/pull/2323
* Translations by @jpirnay in https://github.com/meerk40t/meerk40t/pull/2324
* GRBL Connection Robustness. by @tatarize in https://github.com/meerk40t/meerk40t/pull/2321
* Allow suppression of travel path by @jpirnay in https://github.com/meerk40t/meerk40t/pull/2325
* Provide additional feedback by @jpirnay in https://github.com/meerk40t/meerk40t/pull/2326
* 0.10.x+, Geomstr Backend, Phase 1 by @tatarize in https://github.com/meerk40t/meerk40t/pull/2320
* Correct hatches for those lacking count values (#2331) by @tatarize in https://github.com/meerk40t/meerk40t/pull/2334
* Some layout …
> 0.9.4-beta2 Fixes and Checks

- meerk40t/tools/ttfparser.py
* Adds in `TrueTypeFont.query_name()` functionality which can do 126 fonts in about 4ms to get their names. We do this by parsing the file completely in place, without reading anymore data than we require.
* We also add in `parse_name` to the full true type font definition, giving the user of that routine access to the `font_family`, `font_subfamily`, and `font_name` through normal parsing.
> TTF Naming Table

- meerk40t/tools/ttfparser.py
If a matching cmap signature was found it would try to parse and exit. However, in many cases if this cmap used a format that was not correctly parsed it would be better to continue looking for valid cmap formats.
> Fix parsing of ttf:cmaps

- meerk40t/core/node/effect_hatch.py
- meerk40t/core/node/effect_wobble.py
- meerk40t/gui/laserrender.py
Adding a couple of path default parameters to effects
> Avoid drawing artifacts for effects

- meerk40t/core/elements/elements.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
- Allow optional dnd from regmarked nodes directly to an operation
- Fix improper treatment of dragged substructures under regmark on operations (direct children were vetoed, substructured ones were referenced)
> dnd of regmark nodes

- meerk40t/core/svg_io.py
- meerk40t/extra/ezd.py
- meerk40t/image/imagetools.py
...otherwise a valid svg file could throw an error (most noticeable, if the file only contained regmark nodes)
> Add missing clearance status on load

- meerk40t/extra/coolant.py
There was a small mismatch in M7 M8 callbacks where M7 and M8 were inverted. 
Tested on arduino GRBL testbench
> Fix to M7 M8 mismatch in callbacks

- meerk40t/lihuiyu/controller.py
- meerk40t/lihuiyu/driver.py
The M3-Nano board requires a padding byte to make sure the "S1P" command will be sent appropriately
Covers Issue # 2490
> Fix rapid move issue for M3nano

- meerk40t/core/elements/elements.py
- meerk40t/gui/materialmanager.py
- meerk40t/kernel/settings.py
This allows sharing of your own ``operations.cfg`` file (to be found in the meerk40t configuration directory) with others who then can import the file via the material manager
> Add import of meerk40t operations.cfg to material manager

- meerk40t/core/parameters.py
- meerk40t/grbl/driver.py
- meerk40t/grbl/gui/grbloperationconfig.py
- meerk40t/grbl/gui/gui.py
Half hearted Z-Support for operations: you can now set a desired z-Value for an operation. Use-case for motorized z-Axis: have multiple cut operations where you lower the z-Axis every pass (ie for every cut operation)
Requires testing
> Grbl z support

- meerk40t/balormk/device.py
- meerk40t/balormk/gui/balorconfig.py
- meerk40t/core/elements/shapes.py
- meerk40t/device/devicechoices.py
- meerk40t/device/dummydevice.py
- meerk40t/device/gui/effectspanel.py
- meerk40t/grbl/device.py
- meerk40t/grbl/gui/grblconfiguration.py
- meerk40t/gui/wxmmain.py
- meerk40t/lihuiyu/device.py
- meerk40t/lihuiyu/gui/lhydrivergui.py
- meerk40t/moshi/device.py
- meerk40t/moshi/gui/moshidrivergui.py
- meerk40t/newly/device.py
- meerk40t/newly/gui/newlyconfig.py
- meerk40t/ruida/device.py
- meerk40t/ruida/gui/ruidaconfig.py
[Screencast from 2024-06-13 14-56-31.webm](https://github.com/meerk40t/meerk40t/assets/1604942/7824cd57-bc27-465f-ab07-e0e76492c6d3)
This PR makes two effective changes.
It changes the hatch button on the toolbar to an Effects Button that is populated by registered effects (currently wobble and hatch).
Additionally, it adds the ability to set default values for these effects that are device specific by adding a new Effects tab to each device config dialog.
One current weirdness that is perhaps added by this pr is that the preview in the hatch properties dialog is strange until you manually change it.  It might be an issue in conversion from str to Angle in that preview.  The hatch applies correctly to the object(s).
> Effects Toolbar Button and Default Effects Settings

- meerk40t/balormk/gui/gui.py
- meerk40t/grbl/gui/gui.py
- meerk40t/gui/devicepanel.py
- meerk40t/gui/laserpanel.py
- meerk40t/gui/wxmeerk40t.py
- meerk40t/gui/wxmmain.py
- meerk40t/lihuiyu/gui/gui.py
- meerk40t/main.py
- meerk40t/moshi/gui/gui.py
- meerk40t/newly/gui/gui.py
- meerk40t/ruida/gui/gui.py
Introduce two command line options:
```
-u, --lock-device-config
lock device config from editing
-U, --lock-general-config
lock general config from editing
```
> Allow suppression of config options for classroom sessions

- .github/workflows/unittests.yml
- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/tooldraw.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toolpoint.py
- meerk40t/gui/toolwidgets/toolpointlistbuilder.py
- meerk40t/gui/toolwidgets/toolrect.py
- meerk40t/gui/toolwidgets/tooltext.py
- meerk40t/gui/toolwidgets/toolvector.py
- meerk40t/gui/wxmmain.py
When you design an element, e.g. a line, then MeerK40t will allow you to immediately create the next instance of this type.
If this new option is active then it will create just a single element and return to selection mode.
Hint: Escape or a right-click will leave creation mode as well.
> User option for single node creation

- meerk40t/core/elements/shapes.py
- meerk40t/core/node/effect_wobble.py
- meerk40t/fill/fills.py
- meerk40t/gui/propertypanels/wobbleproperty.py
- meerk40t/tools/geomstr.py
Basic dash-pattern as outline for path like objects (lines, polylines, circle, ellipse, rect, path...)
To have the dashed outline only, you should set the stroke color of the object to None
As usual wobble interval defines the resolution of the shape trace and wobble radius will establish the length of the dash.
For the time being we have equal spaced dashes only (blank space equals dash length)
> Basic dash wobble pattern

- meerk40t/camera/gui/camerapanel.py
- meerk40t/camera/plugin.py
- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/bedwidget.py
- meerk40t/gui/wxmscene.py
Meerk4t supports multiple camera setups - every setup is attached to an USB port or an URI:
Every camera can now be attached to a specific device and update the scene background of the specific device automatically.
> Implement multiple camera timers for device specific background updates

- meerk40t/core/elements/element_treeops.py
- meerk40t/core/elements/elements.py
- meerk40t/core/node/effect_hatch.py
- meerk40t/core/node/effect_wobble.py
- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_image.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_point.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
- meerk40t/core/node/elem_text.py
- meerk40t/core/node/groupnode.py
- meerk40t/core/node/mixins.py
- meerk40t/core/node/op_cut.py
- meerk40t/core/node/op_dots.py
- meerk40t/core/node/op_engrave.py
- meerk40t/core/node/op_image.py
- meerk40t/core/node/op_raster.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/propertypanels/attributes.py
- meerk40t/gui/scenewidgets/rectselectwidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
- meerk40t/gui/wxmtree.py
You can now set for all basic elements a flag (which is *not* stored and loaded, so only during runtime) that will hide it on the scene and that will eliminate it from the set of the to be burnt elements. This flag can be set / unset either via the property panel:
or via the tree / element context menu:
> Add element hide status to suppress display & burning

- meerk40t/core/node/elem_ellipse.py
- meerk40t/core/node/elem_line.py
- meerk40t/core/node/elem_path.py
- meerk40t/core/node/elem_polyline.py
- meerk40t/core/node/elem_rect.py
Rmove simplify call, as the default tolerance of 25 is much too coarse for device resolution
> Fix broken path display

- meerk40t/core/elements/shapes.py
- meerk40t/extra/param_functions.py
- meerk40t/gui/wxmtree.py
- meerk40t/kernel/kernel.py
If you issued commands via the telnet console that were using the node.focus() method, then these commands crashed, ie ended up in an endless loop within wxpython as the methods to clear the selection status of all / individual tree items failed.
> Console server fix

- meerk40t/gui/choicepropertypanel.py
- meerk40t/gui/plugin.py
- meerk40t/gui/ribbon.py
- meerk40t/gui/wxmmain.py
- Honors the tooltip delay within a ribbon bar appear -  as we do have a single control, this had prevented wxPython from resetting the timer when hovering to a different button
- Adding the tooltip timer values to preferences
> Ribbon tooltip fixes

- meerk40t/balormk/controller.py
- meerk40t/balormk/device.py
- meerk40t/balormk/driver.py
- meerk40t/grbl/device.py
- meerk40t/grbl/driver.py
- meerk40t/gui/spoolerpanel.py
- meerk40t/lihuiyu/device.py
- meerk40t/lihuiyu/driver.py
- meerk40t/moshi/device.py
- meerk40t/moshi/driver.py
- meerk40t/newly/controller.py
- meerk40t/newly/device.py
- meerk40t/newly/driver.py
- meerk40t/ruida/device.py
- meerk40t/ruida/driver.py
Not extremely beautiful but somewhat useful to see progress. Looks at internal driver queue.
Most notable difference the K40 as it does have a different implementation compared to all other devices.
* Make them appear for Balor
* Make them suppressable for each device
> Add additional insights into internal device queue

- meerk40t/extra/outerworld.py
- meerk40t/gui/wxmmain.py
``xload`` and ``webload`` do allow the (relative) positioning of a file to load:
```
[20:29:50]     	xload <filename> <x> <y> <width> <height> Gets a file and puts it on the screen
[20:29:50]     
[20:29:50]     
[20:29:50]     	xload <filename:str> <x:str> <y:str> <width:Length> <height:Length>
[20:29:50]     	(None) -> xload -> (None)
[20:29:50]     	Argument: str 'filename':
[20:29:50]     		Filename to load
[20:29:50]     	Argument: str 'x':
[20:29:50]     		Sets the x-position of the image
[20:29:50]     	Argument: str 'y':
[20:29:50]     		Sets the y-position of the image
[20:29:50]     	Argument: Length 'width':
[20:29:50]     		Sets the width of the given image
[20:29:50]     	Argument: Length 'height':
[20:29:50]     		Sets the width of the given image
[20:29:50]     	Option: str …
```
> Add extended load

- meerk40t/core/elements/elements.py
- meerk40t/core/svg_io.py
- meerk40t/gui/preferences.py
When loading a file alongside existing operations that are in use, we create every single operation that is defined in that file, regardless whether an "identical" operation exists. Try to load the same file several times along each other (Recent or Import).
This has been amended that we will look for identical operations and use these instead of creating new ones. 
The criteria list for being identical is intentionally rather strict, the following attributes need to be the same:
- Optype 
- ID
- Speed
- Power
- Passes
- Color
If you want to have the old behaviour back then disable the flag in the settings (which have been slightly rearranged).
> Reuse operations on load

- meerk40t/core/elements/element_treeops.py
- meerk40t/core/node/op_image.py
- meerk40t/gui/materialtest.py
- meerk40t/gui/propertypanels/imageproperty.py
- meerk40t/gui/propertypanels/operationpropertymain.py
- meerk40t/image/dither.py
The dpi setting in an image op did not have any relevance so far. The image node dpi was the relevant value. 
(Reason: historical copy + paste issue from raster operation where the dpi setting is very relevant).
You can now use this value to override any defined dpi value in the image node. For compatibility reasons this will only become active if the corresponding override_dpi has been set, too:
The material test has been updated to take this into account
> Change dpi meaning in op image

- meerk40t/moshi/driver.py
- meerk40t/tools/geomstr.py
This request is needed for Moshiboard based laser cutter since Moshiboard do not interpolate as expected as in the Meerk40t codes.
Moshiboard does not correctly cut an oblique line like in following image. 
When Moshiboard is requested to cut a oblique line, it cuts with two lines. One is 45 degrees angled line and the other is horizontal or vertical line. The following image shows this.
Above shows the issue and below shows the result with the changes included in this pull request.
> Change driver.py and geomstr.py to do interpolation for a line.

- meerk40t/core/elements/element_treeops.py
- meerk40t/core/elements/tree_commands.py
- meerk40t/core/treeop.py
- meerk40t/gui/wxutils.py
The existing methodology of creating a structure inside the context menu became tiresome to maintain / to amend.
So a new grouping tag has been added to the context menu entries that will determine its position,
| New            | Old            |
| ------------ | ----------- |
| <img src="https://github.com/user-attachments/assets/558ee7aa-904e-4b2b-8aed-c25e6f0bee18" width=250> | <img src="https://github.com/user-attachments/assets/e8c555c5-218d-461a-bcdb-7e410b7359db" width=250> |
| <img src="https://github.com/user-attachments/assets/245d7fdd-5d93-44fd-99d9-1ea48eb22ba0" width=250> | <img src="https://github.com/user-attachments/assets/87589c60-4bc1-4ac0-91e6-d910a7a17edc" width=250> |
| <img src="https://github.com/user-attachments/assets/a6620126-cc6c-41cb-b032-d1a021ce0009" …
> Sort and separate tree/node context menu according to tags

- meerk40t/core/elements/branches.py
- meerk40t/tools/geomstr.py
The (faulty) issue described in #1875 was a bit difficult to resolve with meerk40t itself, as break subpaths and merge items would have recreated the same issue. Now merge items will stitch subpaths together if they would fit perfectly.
> Allow stitching subpaths together

- meerk40t/balormk/gui/corscene.py
- meerk40t/gui/laserrender.py
- meerk40t/gui/scene/scene.py
- meerk40t/gui/scenewidgets/attractionwidget.py
- meerk40t/gui/scenewidgets/rectselectwidget.py
- meerk40t/gui/scenewidgets/selectionwidget.py
- meerk40t/gui/simulation.py
- meerk40t/gui/toolwidgets/toolcircle.py
- meerk40t/gui/toolwidgets/toolellipse.py
- meerk40t/gui/toolwidgets/toolmeasure.py
- meerk40t/gui/toolwidgets/toolnodeedit.py
- meerk40t/gui/toolwidgets/toolparameter.py
- meerk40t/gui/toolwidgets/toolrect.py
- meerk40t/gui/toolwidgets/tooltabedit.py
- meerk40t/gui/wxutils.py
Simulation view for balor devices was not properly displayed on Darwin (and probably not on Linux either).
Cause: the scale of the current GraphicsContext Transformation Matrix was relying solely on the 'regular' scale values. This fails for rotated / mirrored matrices like the one we need for Balor.
> Simulation balor fix

- meerk40t/gui/ribbon.py
We seem to have every now and then an error, where we try to get the dc, while it's still in use:
```
MeerK40t crash log. Version: 0.9.5202 on Windows: Python 3.9.10: AMD64 - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
File "meerk40t\gui\ribbon.py", line 946, in on_paint
File "meerk40t\gui\ribbon.py", line 962, in _paint_main_on_buffer
wx._core.wxAssertionError: C++ assertion "!bitmap.GetSelectedInto() || (bitmap.GetSelectedInto() == GetOwner())" failed at ..\..\src\msw\dcmemory.cpp(114) in wxMemoryDCImpl::DoSelect(): Bitmap is selected in another wxMemoryDC, delete the first wxMemoryDC or use SelectObject(NULL)
```
This change should cover it
> Put dc acquisition inside lock
